import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buttonRecipe, selectRecipe } from "@axiom/recipes";
import {
  collectAppearanceArtifacts,
  collectRecipeAppearances,
  renderArtifactsCss,
} from "../src/compiler.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = resolve(packageRoot, "src/generated");
const recipes = [buttonRecipe, selectRecipe];
const appearances = recipes.flatMap((recipe) => collectRecipeAppearances(recipe));
const artifacts = collectAppearanceArtifacts(appearances);
const manifest = Object.fromEntries(
  artifacts.map((artifact) => [artifact.key, artifact.className]),
);

const module = `// Generated by packages/adapter-tailwind/scripts/generate.ts. Do not edit.\n\n` +
  `import type { AtomicClassManifest } from "../compiler.js";\n\n` +
  `export const atomicClassManifest = ${JSON.stringify(manifest, null, 2)} as const satisfies AtomicClassManifest;\n`;

await mkdir(outputDirectory, { recursive: true });
await Promise.all([
  writeFile(resolve(outputDirectory, "atomic-manifest.ts"), module),
  writeFile(resolve(outputDirectory, "styles.css"), renderArtifactsCss(artifacts)),
]);
