/** Package-wide parser profile and diagnostic constants. */
export const DTCG_PROFILE_VERSION = "2025.10" as const;
export const DTCG_SOURCE_UNITS: ReadonlySet<string> = new Set(["px", "rem", "ms", "s"]);
export const UNKNOWN_SOURCE_NAME = "<unknown>";
export const TOKEN_DIAGNOSTIC_PHASE = "token" as const;
export const ERROR_DIAGNOSTIC_SEVERITY = "error" as const;
export const ROOT_JSON_POINTER_PREFIX = "#";
export const ROOT_JSON_POINTER_PREFIX_LENGTH = ROOT_JSON_POINTER_PREFIX.length;
export const EMPTY_JSON_POINTER = "";
export const PARSER_SKIP_LINT = true;
export const TOKEN_FOUNDATION_GENERATOR_VERSION = "0.4.0" as const;
export const TOKEN_GENERATED_SCHEMA_VERSION = "0.2" as const;
export const TOKEN_SOURCE_PROFILE_PATH = "spec/token/token-source-profile.json" as const;
export const TOKEN_FOUNDATION_POLICY_PATH =
  "spec/token/foundation-token-policy.json" as const;
export const TOKEN_SEMANTIC_VOCABULARY_PATH =
  "spec/token/semantic-token-vocabulary.json" as const;
export const TOKEN_DOMAIN_REGISTRY_PATH = "spec/token/token-domain-registry.json" as const;
export const TOKEN_MODIFIER_REGISTRY_PATH =
  "spec/token/resolver-modifier-registry.json" as const;
export const TOKEN_RESOLVED_MANIFEST_PATH =
  "spec/token/foundation-resolved-token-manifest.json" as const;
export const TOKEN_PATH_TYPES_PATH =
  "packages/tokens/src/generated/token-paths.ts" as const;
export const TOKEN_SOURCE_FILES = [
  { context: "base", path: "tokens/base.tokens.json" },
  { context: "light", path: "tokens/theme-light.tokens.json" },
  { context: "dark", path: "tokens/theme-dark.tokens.json" },
] as const;
export const TOKEN_SOURCE_DIGEST_ALGORITHM = "sha256" as const;
export const TOKEN_SOURCE_DIGEST_PREFIX = `${TOKEN_SOURCE_DIGEST_ALGORITHM}:`;
export const TOKEN_GENERATED_FILE_HEADER = [
  "// AUTO-GENERATED by @axiom/token-tooling.",
  "// DO NOT EDIT. Run `pnpm tokens:generate` after changing normative Token sources.",
] as const;
export const TOKEN_GENERATED_FILE_INDENT = "  ";
export const TOKEN_STABLE_SORT_LOCALE = "en";
export const ASPECT_RATIO_DECIMAL_PRECISION = 10;

export const PARSER_DIAGNOSTIC_CODE = {
  MISSING_SOURCE: "AXT0001",
  PARSE_FAILURE: "AXT0002",
  UNSUPPORTED_DTCG_TYPE: "AXT1200",
  UNSUPPORTED_DTCG_UNIT: "AXT1203",
  INVALID_DTCG_VALUE: "AXT1204",
} as const;

export const FOUNDATION_POLICY_DIAGNOSTIC_CODE = {
  MISSING_REQUIRED_TOKEN: "AXF1001",
  SEMANTIC_PRIMITIVE_NAME: "AXF1002",
  INVALID_COLOR_SCALE: "AXF1101",
  INVALID_SPACE_SCALE: "AXF1102",
  INVALID_DIMENSION_UNIT: "AXF1103",
  INVALID_TYPOGRAPHY_SCALE: "AXF1104",
  INVALID_COLOR_PROFILE: "AXF1105",
  INVALID_COLOR_FALLBACK: "AXF1106",
  INVALID_SEMANTIC_SCALE: "AXF1107",
  REMOVED_SEMANTIC_PATH: "AXF1108",
  INVALID_ASPECT_RATIO: "AXF1109",
  INVALID_CONTRAST: "AXF1201",
} as const;

export const FOUNDATION_POLICY_ERROR_MESSAGE =
  "Axiom Token Foundation policy validation failed.";

export const PARSER_ERROR_MESSAGE = {
  MISSING_SOURCE: "At least one Token source is required.",
  PARSE_FAILURE: "DTCG source parsing failed.",
  NORMALIZATION_FAILURE: "Axiom Token normalization failed.",
} as const;

export const TOKEN_REFERENCE_PATTERN = /^\{([^{}]+)\}$/;
