import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import {
  checkReferenceContractDrift,
  checkReferenceContractDriftInTemporaryDirectory,
  generateReferenceContracts,
  writeReferenceContracts,
} from "./contracts-generator.js";

const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
const readSpecJson = async (path: string): Promise<unknown> =>
  JSON.parse(await readFile(join(repoRoot, path), "utf8")) as unknown;

describe("generated reference contracts", () => {
  it("generates deterministic public artifacts with source provenance", async () => {
    const first = await generateReferenceContracts(repoRoot);
    const second = await generateReferenceContracts(repoRoot);

    expect(first).toEqual(second);
    expect(first.map((artifact) => artifact.destination)).toEqual([
      "packages/behavior-contracts/src/generated/reference-contracts.ts",
      "packages/condition-registry/src/generated/reference-contracts.ts",
      "packages/motion-schema/src/generated/reference-contracts.ts",
    ]);
    expect(first.map((artifact) => artifact.content)).toEqual(expect.arrayContaining([
      expect.stringContaining("GENERATED by @axiom/spec-tooling"),
      expect.stringContaining("schemaOrProfileVersion"),
      expect.stringContaining("canonicalInputDigest"),
      expect.stringContaining("https://axiom.dev/schemas/motion/ir/0.1"),
      expect.stringContaining("CollisionTrace"),
    ]));
  });

  it("reports generated-contract drift and restores it through deterministic generation", async () => {
    const temporaryRoot = await mkdtemp(join(tmpdir(), "axiom-contracts-"));
    try {
      await writeReferenceContracts(repoRoot, temporaryRoot);
      expect(await checkReferenceContractDrift(repoRoot, temporaryRoot)).toEqual([]);

      const target = join(
        temporaryRoot,
        "packages/condition-registry/src/generated/reference-contracts.ts",
      );
      await writeFile(target, `${await readFile(target, "utf8")}// drift\n`, "utf8");

      expect(await checkReferenceContractDrift(repoRoot, temporaryRoot)).toEqual([
        "packages/condition-registry/src/generated/reference-contracts.ts",
      ]);
    } finally {
      await rm(temporaryRoot, { force: true, recursive: true });
    }
  });

  it("changes each public family when its authoritative schema or registry shape changes", async () => {
    const baseline = await generateReferenceContracts(repoRoot);
    const stateRegistry = structuredClone(await readSpecJson("spec/state/canonical-state-registry.json")) as {
      states: unknown[];
    };
    stateRegistry.states.push({ id: "reviewState" });
    const motionSchema = structuredClone(await readSpecJson("spec/motion/motion-ir.schema.json")) as {
      $defs: { track: { required: string[] } };
    };
    motionSchema.$defs.track.required = motionSchema.$defs.track.required.filter(
      (field) => field !== "allowDiscrete",
    );
    const behaviorSchema = structuredClone(await readSpecJson(
      "spec/behavior/behavior-criteria-source-manifest.schema.json",
    )) as { properties: { packages: { maxItems: number } } };
    behaviorSchema.properties.packages.maxItems = 3;
    const mutated = await generateReferenceContracts(repoRoot, {
      sourceOverrides: {
        "spec/state/canonical-state-registry.json": stateRegistry,
        "spec/motion/motion-ir.schema.json": motionSchema,
        "spec/behavior/behavior-criteria-source-manifest.schema.json": behaviorSchema,
      },
    });

    const byDestination = (artifacts: readonly { readonly destination: string; readonly content: string }[], destination: string): string =>
      artifacts.find((artifact) => artifact.destination === destination)?.content ?? "";
    expect(byDestination(mutated, "packages/condition-registry/src/generated/reference-contracts.ts"))
      .not.toBe(byDestination(baseline, "packages/condition-registry/src/generated/reference-contracts.ts"));
    expect(byDestination(mutated, "packages/condition-registry/src/generated/reference-contracts.ts"))
      .toContain('"reviewState"');
    expect(byDestination(mutated, "packages/motion-schema/src/generated/reference-contracts.ts"))
      .toContain("readonly allowDiscrete?: boolean");
    expect(byDestination(mutated, "packages/behavior-contracts/src/generated/reference-contracts.ts"))
      .toContain("readonly [(BehaviorSourcePackage), (BehaviorSourcePackage), (BehaviorSourcePackage)]");
  });

  it("checks checked-in artifacts against a clean temporary regeneration", async () => {
    expect(await checkReferenceContractDriftInTemporaryDirectory(repoRoot)).toEqual([]);
  });
});
