/** Package-wide protocol, policy, and diagnostic constants. */
export const CSS_PROFILE_ID = "axiom-css" as const;
export const CSS_PROFILE_SCHEMA_VERSION = "0.1" as const;
export const CSS_PROFILE_GENERATOR_VERSION = "0.1.0" as const;
export const EFFECTIVE_PROPERTY_REGISTRY_SCHEMA_VERSION = "0.1" as const;
export const CSS_POLICY_SCHEMA_VERSION = "0.1" as const;
export const TOKEN_BINDING_CATALOG_SCHEMA_VERSION = "0.1" as const;
export const WEBREF_PACKAGE_NAME = "@webref/css" as const;
export const WEBREF_PACKAGE_VERSION = "8.7.3" as const;
export const WEBREF_INPUT_PATH = "css.json" as const;
export const CSS_PROPERTY_TYPES_PATH =
  "packages/css-property-profile/src/generated/css-property-names.ts" as const;
export const CSS_GENERATED_FILE_HEADER = [
  "// AUTO-GENERATED by @axiom/css-property-profile.",
  "// DO NOT EDIT. Run `pnpm profile:generate` after changing CSS profile inputs.",
] as const;
export const CSS_GENERATED_FILE_INDENT = "  ";
export const CANONICAL_DIGEST_ALGORITHM = "sha256" as const;
export const CANONICAL_DIGEST_PREFIX = `${CANONICAL_DIGEST_ALGORITHM}:`;
export const JSON_INDENT_SPACES = 2;
export const STABLE_SORT_LOCALE = "en";
export const PROPERTY_DIAGNOSTIC_PHASE = "property" as const;
export const PROPERTY_PROFILE_DIAGNOSTIC_PHASE = "propertyProfile" as const;
export const ERROR_DIAGNOSTIC_SEVERITY = "error" as const;
export const WARNING_DIAGNOSTIC_SEVERITY = "warning" as const;
export const CSS_WIDE_KEYWORDS = new Set([
  "inherit",
  "initial",
  "revert",
  "revert-layer",
  "unset",
]);
export const BLOCKED_CSS_WIDE_KEYWORDS = new Set(["revert-layer"]);
export const DECLARATION_DELIMITER_PATTERN = /[;{}]/;
export const IMPORTANT_PATTERN = /!\s*important\b/i;
export const CUSTOM_PROPERTY_PATTERN = /^--[a-z0-9][a-z0-9-]*$/;
export const VENDOR_PROPERTY_PATTERN = /^-[a-z]+-/;
export const CSS_VARIABLE_MATCH_UNSUPPORTED_MESSAGE =
  "Matching for a tree with var() is not supported";

export const PROPERTY_DIAGNOSTIC_CODE = {
  UNKNOWN_PROPERTY: "AXP1001",
  EXPERIMENTAL_OPT_IN_REQUIRED: "AXP1002",
  VENDOR_PROPERTY_BLOCKED: "AXP1003",
  RAW_CSS_BLOCKED: "AXP1101",
  TOKEN_BINDING_MISSING: "AXP1102",
  TOKEN_DOMAIN_MISMATCH: "AXP1103",
  TOKEN_SERIALIZER_MISSING: "AXP1104",
  PROJECTOR_MISSING: "AXP1105",
  CSS_GRAMMAR_MISMATCH: "AXP1201",
  IMPORTANT_FORBIDDEN: "AXP1202",
  DECLARATION_SYNTAX_FORBIDDEN: "AXP1204",
  PROFILE_INPUT_MISMATCH: "AXP2001",
  UPSTREAM_SHAPE_INVALID: "AXP2002",
  POLICY_CONFLICT: "AXP2003",
} as const;
