import {
  isTokenReference,
  type AppearancePropertyName,
  type AppearanceStyle,
  type AppearanceValue,
} from "@axiom/appearance-schema";
import type { RecipeResolution } from "@axiom/recipe-engine";
import { tokenPathToCssVariable } from "@axiom/tokens";

export interface AtomicArtifact {
  readonly key: string;
  readonly className: `ax_${string}`;
  readonly declarations: readonly string[];
}

const cssPropertyMap = {
  display: ["display"],
  position: ["position"],
  insetBlockStart: ["inset-block-start"],
  insetInlineEnd: ["inset-inline-end"],
  alignItems: ["align-items"],
  justifyContent: ["justify-content"],
  flexDirection: ["flex-direction"],
  flexGrow: ["flex-grow"],
  gap: ["gap"],
  minInlineSize: ["min-inline-size"],
  blockSize: ["block-size"],
  inlineSize: ["inline-size"],
  paddingBlock: ["padding-block"],
  paddingInline: ["padding-inline"],
  padding: ["padding"],
  backgroundColor: ["background-color"],
  foregroundColor: ["color"],
  borderColor: ["border-color"],
  borderWidth: ["border-width", "border-style:solid"],
  borderRadius: ["border-radius"],
  outlineColor: ["outline-color"],
  outlineWidth: ["outline-width", "outline-style:solid"],
  outlineOffset: ["outline-offset"],
  fontFamily: ["font-family"],
  fontSize: ["font-size"],
  fontWeight: ["font-weight"],
  lineHeight: ["line-height"],
  textAlign: ["text-align"],
  whiteSpace: ["white-space"],
  cursor: ["cursor"],
  opacity: ["opacity"],
  overflow: ["overflow"],
  userSelect: ["user-select"],
} as const satisfies Record<AppearancePropertyName, readonly string[]>;

export const serializeAppearanceValue = (
  value: AppearanceValue<AppearancePropertyName>,
): string =>
  isTokenReference(value)
    ? `token:${value.path}`
    : `literal:${typeof value}:${String(value)}`;

export const atomicKey = (
  property: AppearancePropertyName,
  value: AppearanceValue<AppearancePropertyName>,
): string => `${property}|${serializeAppearanceValue(value)}`;

const hash = (input: string): string => {
  let value = 0x811c9dc5;
  for (let index = 0; index < input.length; index += 1) {
    value ^= input.charCodeAt(index);
    value = Math.imul(value, 0x01000193);
  }
  return (value >>> 0).toString(36);
};

const cssValue = (value: AppearanceValue<AppearancePropertyName>): string =>
  isTokenReference(value)
    ? `var(${tokenPathToCssVariable(value.path)})`
    : String(value);

export const compileAtomicArtifact = (
  property: AppearancePropertyName,
  value: AppearanceValue<AppearancePropertyName>,
): AtomicArtifact => {
  const key = atomicKey(property, value);
  const descriptors = cssPropertyMap[property];
  const declarations = descriptors.map((descriptor) =>
    descriptor.includes(":") ? descriptor : `${descriptor}:${cssValue(value)}`,
  );
  return { key, className: `ax_${hash(key)}`, declarations };
};

export const collectAppearanceArtifacts = (
  appearances: readonly AppearanceStyle[],
): readonly AtomicArtifact[] => {
  const artifacts = new Map<string, AtomicArtifact>();
  for (const appearance of appearances) {
    for (const [property, value] of Object.entries(appearance) as [
      AppearancePropertyName,
      AppearanceValue<AppearancePropertyName>,
    ][]) {
      const artifact = compileAtomicArtifact(property, value);
      artifacts.set(artifact.key, artifact);
    }
  }
  return [...artifacts.values()].sort((left, right) =>
    left.key.localeCompare(right.key),
  );
};

export const renderArtifactsCss = (artifacts: readonly AtomicArtifact[]): string =>
  `/* Generated by @axiom/adapter-tailwind. Do not edit. */\n` +
  `@layer utilities {\n${artifacts
    .map(
      (artifact) =>
        `  .${artifact.className} { ${artifact.declarations.join("; ")} }`,
    )
    .join("\n")}\n}\n`;

export const collectRecipeAppearances = (recipe: {
  readonly base: Record<string, AppearanceStyle>;
  readonly variants: Record<
    string,
    Record<string, Record<string, AppearanceStyle>>
  >;
  readonly states: Record<string, Record<string, AppearanceStyle>>;
  readonly compoundVariants: readonly {
    readonly apply: Record<string, AppearanceStyle>;
  }[];
}): readonly AppearanceStyle[] => [
  ...Object.values(recipe.base),
  ...Object.values(recipe.variants).flatMap((options) =>
    Object.values(options).flatMap((slots) => Object.values(slots)),
  ),
  ...Object.values(recipe.states).flatMap((states) => Object.values(states)),
  ...recipe.compoundVariants.flatMap((compound) => Object.values(compound.apply)),
];

export type AtomicClassManifest = Readonly<Record<string, `ax_${string}`>>;

export const compileAppearance = (
  appearance: AppearanceStyle,
  manifest: AtomicClassManifest,
): string =>
  (Object.entries(appearance) as [
    AppearancePropertyName,
    AppearanceValue<AppearancePropertyName>,
  ][])
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([property, value]) => {
      const key = atomicKey(property, value);
      const className = manifest[key];
      if (!className) {
        throw new ReferenceError(
          `Appearance value was not emitted by the adapter compiler: ${key}`,
        );
      }
      return className;
    })
    .join(" ");

export const compileRecipeResolution = <TSlot extends string>(
  resolution: RecipeResolution<TSlot>,
  manifest: AtomicClassManifest,
): Readonly<Record<TSlot, string>> =>
  Object.fromEntries(
    Object.entries<AppearanceStyle>(resolution.slots).map(([slot, appearance]) => [
      slot,
      compileAppearance(appearance, manifest),
    ]),
  ) as Record<TSlot, string>;
