import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { DtcgGroup, ResolvedToken } from "../src/contracts.js";
import { resolveTokens, tokenValueToCss } from "../src/resolver.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(packageRoot, "src/source/tokens.json");
const outputDirectory = resolve(packageRoot, "src/generated");

const source = JSON.parse(await readFile(sourcePath, "utf8")) as DtcgGroup;
const tokens = resolveTokens(source);
const entries = Object.values(tokens);

const union = (values: readonly string[]): string =>
  values.length === 0 ? "never" : values.map(JSON.stringify).join("\n  | ");

const appearanceEntries = entries.filter((token) =>
  ["color", "dimension", "fontFamily", "fontWeight", "number"].includes(token.type),
);

const pathsByType = Object.fromEntries(
  ["color", "dimension", "fontFamily", "fontWeight", "number"].map((type) => [
    type,
    entries.filter((token) => token.type === type).map((token) => token.path),
  ]),
) as Record<string, string[]>;

const tokenPaths = `// Generated by packages/tokens/scripts/generate.ts. Do not edit.\n\n` +
  `export type TokenPath =\n  | ${union(entries.map((token) => token.path))};\n\n` +
  `export type AppearanceTokenPath =\n  | ${union(appearanceEntries.map((token) => token.path))};\n\n` +
  `export interface TokenPathByType {\n` +
  Object.entries(pathsByType)
    .map(([type, paths]) => `  readonly ${type}:\n    | ${union(paths)};`)
    .join("\n") +
  `\n}\n\n` +
  `export const tokenPaths = ${JSON.stringify(entries.map((token) => token.path), null, 2)} as const;\n`;

const tokenValues = `// Generated by packages/tokens/scripts/generate.ts. Do not edit.\n\n` +
  `import type { ResolvedTokenMap } from "../contracts.js";\n\n` +
  `export const resolvedTokens = ${JSON.stringify(tokens, null, 2)} as const satisfies ResolvedTokenMap;\n`;

const css = `/* Generated by packages/tokens/scripts/generate.ts. Do not edit. */\n` +
  `@theme {\n${entries
    .map((token) => `  ${token.cssVariable}: ${tokenValueToCss(token)};`)
    .join("\n")}\n}\n\n` +
  `:root {\n${entries
    .map((token) => `  ${token.cssVariable}: ${tokenValueToCss(token)};`)
    .join("\n")}\n}\n`;

const manifest = Object.fromEntries(
  entries.map((token: ResolvedToken) => [
    token.path,
    {
      type: token.type,
      value: token.value,
      cssVariable: token.cssVariable,
    },
  ]),
);

await mkdir(outputDirectory, { recursive: true });
await Promise.all([
  writeFile(resolve(outputDirectory, "token-paths.ts"), tokenPaths),
  writeFile(resolve(outputDirectory, "token-values.ts"), tokenValues),
  writeFile(resolve(outputDirectory, "tokens.css"), css),
  writeFile(
    resolve(outputDirectory, "token-manifest.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
  ),
]);
