import { catalogReactComposition } from "./catalog-react-composition.ts";
import { catalogReactAuthored } from "./catalog-react-authored.ts";
import { catalogReactBehavior } from "./catalog-react-behavior.ts";
import type { StudioComponent } from "../../ads-core/src/index.ts";
import { componentSymbol } from "./generator-input.ts";
import { catalogProps } from "./catalog-source-types.ts";
import { TargetError } from "./target-error.ts";
import { TARGET_CODE } from "./constants.ts";

/** Each closed semantic branch emits its actual native HTML/ARIA contract. */
export function catalogReactComponent(component: StudioComponent, components: StudioComponent[] = []): string {
  const name = componentSymbol(component), catalog = component.catalog!, semantic = catalog.semantic, api = catalogProps(component, name);
  const root = component.parts.find(part => part.role === "root")!;
  const part = (role: string): string => JSON.stringify(component.parts.find(part => part.role === role)?.id ?? root.id);
  const composition = catalogReactComposition(component, components), authoredBehavior = catalogReactBehavior(component), authored = catalogReactAuthored(component, composition);
  const attrs = `className=${JSON.stringify(name)} data-part=${part("root")} data-variant={variant} ${authoredBehavior.attributes}`;
  const label = `<label htmlFor={id} data-part=${part("label")}>{label}</label>`;
  const description = `<span id={id+"-description"} data-part=${part("description")}>{description}</span>`;
  const body = `<div data-part=${part("body")}>{body}</div>`;
  const input = `id={id} aria-describedby={description?id+"-description":undefined} aria-label={label} data-part=${part("input")}`;
  let hooks = "", output: string;
  switch (semantic.kind) {
    case "button": output = `<button type="button" ${attrs} disabled={disabled} data-disabled={disabled} onClick={()=>onActivate({})}><span data-part=${part("label")}>{label}</span></button>`; break;
    case "text-input": case "textarea": output = `<div ${attrs}>${label}<${semantic.kind === "textarea" ? "textarea" : `input type=${JSON.stringify(semantic.inputType ?? "text")}`} ${input} value={value} placeholder={placeholder} disabled={disabled} readOnly={readOnly} aria-invalid={invalid} onChange={event=>onValueChangeRequest({value:event.currentTarget.value})}/>${description}${semantic.kind === "textarea" ? "" : ""}</div>`; break;
    case "number-input": output = `<div ${attrs}>${label}<input type="text" inputMode="decimal" role="spinbutton" ${input} value={draft} aria-valuemin={min} aria-valuemax={max} aria-valuenow={value??undefined} disabled={disabled} onChange={event=>onDraftChangeRequest({value:event.currentTarget.value})} onBlur={()=>{const parsed=draft.trim()===""?null:Number(draft);if(parsed===null||Number.isFinite(parsed)&&parsed>=min&&parsed<=max)onValueChangeRequest({value:parsed});}}/><button type="button" aria-label={label+" decrease"} data-part=${part("decrement")} disabled={disabled||value===null||value<=min} onClick={()=>onValueChangeRequest({value:Math.max(min,(value??min)-step)})}>−</button><button type="button" aria-label={label+" increase"} data-part=${part("increment")} disabled={disabled||value===null||value>=max} onClick={()=>onValueChangeRequest({value:Math.min(max,(value??min)+step)})}>+</button>${description}</div>`; break;
    case "checkbox": case "radio": case "switch": output = `<div ${attrs} data-disabled={disabled}><${semantic.kind === "checkbox" ? "CatalogCheck indeterminate={indeterminate}" : "input"} id={id} type=${JSON.stringify(semantic.kind === "radio" ? "radio" : "checkbox")} ${semantic.kind === "switch" ? 'role="switch"' : ""} ${semantic.kind === "radio" ? "name={groupName} value={itemKey}" : ""} data-part=${part("control")} checked={checked} disabled={disabled} onChange={event=>onCheckedChangeRequest({value:event.currentTarget.checked})}/><span aria-hidden="true" data-part=${part("indicator")}/>${label}</div>`; break;
    case "toggle": output = `<button type="button" ${attrs} aria-pressed={pressed} disabled={disabled} data-disabled={disabled} onClick={()=>onPressedChangeRequest({value:!pressed})}><span data-part=${part("label")}>{label}</span></button>`; break;
    case "choice-group": {
      const multiple = semantic.selection === "multiple", selected = multiple ? "selectedKeys.includes(item.key)" : "selectedKey===item.key";
      const request = multiple ? "onSelectedKeysChangeRequest({value:selectedKeys.includes(item.key)?selectedKeys.filter(key=>key!==item.key):[...selectedKeys,item.key]})" : "onSelectedKeyChangeRequest({value:item.key})";
      if (["catalog.togglegroup", "catalog.togglebuttongroup", "catalog.segmentedcontrol"].includes(catalog.catalogId)) {
        output = `<div ${attrs} role="group" aria-label={label} data-disabled={disabled}><span data-part=${part("label")}>{label}</span><div data-part=${part("list")}>{items.map(item=><button type="button" key={item.key} aria-pressed={${selected}} data-part=${part("item")} disabled={disabled||item.disabled} onClick={()=>${request}}>{item.label}</button>)}</div>${description}</div>`; break;
      }
      output = `<fieldset ${attrs} disabled={disabled}><legend data-part=${part("label")}>{label}</legend><div data-part=${part("list")}>{items.map(item=><label key={item.key} data-part=${part("item")}><input type=${JSON.stringify(multiple ? "checkbox" : "radio")} name={id} checked={${selected}} disabled={item.disabled||disabled} onChange={()=>${request}}/>{item.label}</label>)}</div>${description}</fieldset>`; break;
    }
    case "select": output = `<div ${attrs}>${label}<select id={id} data-part=${part("trigger")} value={selectedKey??""} disabled={disabled} onChange={event=>onSelectedKeyChangeRequest({value:event.currentTarget.value||null})}><option value="">Choose…</option>{items.map(item=><option key={item.key} value={item.key} disabled={item.disabled}>{item.label}</option>)}</select>${description}</div>`; break;
    case "slider": output = `<div ${attrs}>${label}<input ${input} type="range" min={min} max={max} step={step} value={value} disabled={disabled} onChange={event=>onValueChangeRequest({value:event.currentTarget.valueAsNumber})}/><output htmlFor={id} data-part=${part("value")}>{value}</output></div>`; break;
    case "rating": output = `<fieldset ${attrs} disabled={disabled}><legend>${label}</legend>{Array.from({length:Math.min(10,Math.max(0,Math.floor(max)))}).map((_,index)=><label key={index}><input type="radio" name={id} value={index+1} checked={value===index+1} aria-label={label+" "+(index+1)+" of "+max} onChange={()=>onValueChangeRequest({value:index+1})}/><span aria-hidden="true">{value>=index+1?"★":"☆"}</span></label>)}</fieldset>`; break;
    case "range-slider": output = `<div ${attrs}><span data-part=${part("label")}>{label}</span><input type="range" aria-label={label+" minimum"} min={min} max={value[1]} step={step} value={value[0]} disabled={disabled} data-part=${part("thumb")} onChange={event=>onValueChangeRequest({value:[event.currentTarget.valueAsNumber,value[1]!]})}/><input type="range" aria-label={label+" maximum"} min={value[0]} max={max} step={step} value={value[1]} disabled={disabled} data-part=${part("track")} onChange={event=>onValueChangeRequest({value:[value[0]!,event.currentTarget.valueAsNumber]})}/><output data-part=${part("value")}>{value.join(" – ")}</output></div>`; break;
    case "progress": output = `<div ${attrs}>${label}<progress id={id} aria-label={label} data-part=${part("indicator")} max={max-min} value={indeterminate?undefined:value-min}/><output data-part=${part("value")}>{indeterminate?label:value}</output></div>`; break;
    case "meter": output = `<div ${attrs}>${label}<meter id={id} aria-label={label} data-part=${part("indicator")} min={min} max={max} value={value}/><output data-part=${part("value")}>{value}</output></div>`; break;
    case "loading": output = `<div ${attrs} role="status" aria-label={label} aria-busy={loading}>{loading&&<span data-part=${part("indicator")} aria-hidden="true">◌</span>}<span data-part=${part("label")}>{label}</span></div>`; break;
    case "badge": case "text": {
      const tag = semantic.role === "heading" ? "h2" : semantic.role === "code" ? "code" : component.catalog!.catalogId === "catalog.blockquote" ? "blockquote" : "span";
      output = `<${tag} ${attrs}><span data-part=${part("body")}>{text}</span></${tag}>`; break;
    }
    case "avatar": case "image": hooks = 'const [failed,setFailed]=React.useState<string|null>(null);'; output = `<div ${attrs}>{src&&failed!==src?<img src={src} alt={alt} onError={()=>setFailed(src)} data-part=${part("image")}/>:<span role="img" aria-label={alt} data-part=${part("fallback")}>{fallback}</span>}</div>`; break;
    case "separator": output = `<hr ${attrs} aria-orientation={orientation}/>`; break;
    case "tabs": output = `<div ${attrs}><div role="tablist" aria-label={label} data-part=${part("list")} onKeyDown={event=>catalogMoveFocus(event,'[role="tab"]')}>{items.map(item=><button type="button" role="tab" key={item.key} id={id+"-tab-"+encodeURIComponent(item.key)} aria-controls={id+"-panel-"+encodeURIComponent(item.key)} aria-selected={selectedKey===item.key} tabIndex={selectedKey===item.key?0:-1} disabled={item.disabled} data-part=${part("trigger")} onClick={()=>onSelectedKeyChangeRequest({value:item.key})}>{item.label}</button>)}</div>{items.map(item=><section key={item.key} role="tabpanel" hidden={selectedKey!==item.key} id={id+"-panel-"+encodeURIComponent(item.key)} aria-labelledby={id+"-tab-"+encodeURIComponent(item.key)} data-part=${part("panel")}>{panel??item.label}</section>)}</div>`; break;
    case "accordion": {
      const hasItem = component.parts.some(part => part.role === "item"), hasHeader = component.parts.some(part => part.role === "header");
      const triggerNode = `<button type="button" id={id+"-trigger-"+encodeURIComponent(item.key)} aria-expanded={expandedKeys.includes(item.key)} aria-controls={id+"-panel-"+encodeURIComponent(item.key)} disabled={item.disabled} data-part=${part("trigger")} onClick={()=>onExpandedKeysChangeRequest({value:expandedKeys.includes(item.key)?expandedKeys.filter(key=>key!==item.key):multiple?[...expandedKeys,item.key]:[item.key]})}>{item.label}<span aria-hidden="true" data-part=${part("indicator")}>{expandedKeys.includes(item.key)?"−":"+"}</span></button>`;
      output = `<div ${attrs}>{items.map(item=><section key={item.key} ${hasItem ? `data-part=${part("item")}` : ""}>${hasHeader ? `<h3 data-part=${part("header")}>${triggerNode}</h3>` : triggerNode}<div role="region" aria-labelledby={id+"-trigger-"+encodeURIComponent(item.key)} id={id+"-panel-"+encodeURIComponent(item.key)} hidden={!expandedKeys.includes(item.key)} data-part=${part("panel")}>{panel${component.parts.some(child => child.parent === component.parts.find(part => part.role === "panel")?.id && child.elementKind) || component.instances?.some(instance => instance.ownerPartRef === component.parts.find(part => part.role === "panel")?.id) ? "" : "??item.label"}}</div></section>)}</div>`; break;
    }
    case "dialog": hooks = `useCatalogOverlay();const dialog=React.useRef<HTMLDialogElement>(null);React.useEffect(()=>{const element=dialog.current;if(!element)return;if(open&&!element.open)element.showModal();if(!open&&element.open)element.close();},[open]);`;
      output = `<div ${attrs}><button type="button" data-part=${part("trigger")} onClick={()=>onOpenChangeRequest({value:true})}>{label}</button><dialog ref={dialog} role=${JSON.stringify(semantic.role)} aria-labelledby={id+"-title"} aria-describedby={description?id+"-description":undefined} onCancel={event=>{event.preventDefault();onOpenChangeRequest({value:false});}}><h2 id={id+"-title"} data-part=${part("title")}>{label}</h2>${body}${description}<button type="button" data-part=${part("close")} onClick={()=>onOpenChangeRequest({value:false})}>{${JSON.stringify(component.sampleContent.closeLabel)}}</button></dialog></div>`; break;
    case "tooltip": hooks = "useCatalogOverlay();"; output = `<div ${attrs}><button type="button" data-part=${part("trigger")} aria-describedby={open?id:undefined} onFocus={()=>onOpenChangeRequest({value:true})} onBlur={()=>onOpenChangeRequest({value:false})} onMouseEnter={()=>onOpenChangeRequest({value:true})} onMouseLeave={()=>onOpenChangeRequest({value:false})} onKeyDown={event=>{if(event.key==="Escape")onOpenChangeRequest({value:false});}}>{label}</button>{open&&<span role="tooltip" id={id} data-part=${part("content")}>{content??description}</span>}</div>`; break;
    case "menu": hooks = `useCatalogOverlay();const menu=React.useRef<HTMLUListElement>(null);const trigger=React.useRef<HTMLButtonElement>(null);React.useEffect(()=>{if(open)menu.current?.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();},[open]);`;
      output = `<div ${attrs}><button ref={trigger} type="button" aria-haspopup="menu" aria-expanded={open} data-part=${part("trigger")} onClick={()=>onOpenChangeRequest({value:!open})}>{label}</button>{open&&<ul ref={menu} role="menu" aria-label={label} data-part=${part("list")} onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();onOpenChangeRequest({value:false});trigger.current?.focus();}else catalogMoveFocus(event,'[role="menuitem"]');}}>{items.map(item=><li role="none" key={item.key}><button type="button" role="menuitem" disabled={item.disabled} tabIndex={-1} data-part=${part("item")} onClick={()=>onActionRequest({key:item.key})}>{item.label}</button></li>)}</ul>}</div>`; break;
    case "link": output = `<a ${attrs} href={href}><span data-part=${part("label")}>{label}</span></a>`; break;
    case "navigation": output = `<nav ${attrs} aria-label={label}><ol data-part=${part("list")}>{items.map(item=><li key={item.key} data-part=${part("item")}><button type="button" aria-current={currentKey===item.key?"page":undefined} disabled={item.disabled} onClick={()=>onCurrentKeyChangeRequest({value:item.key})}>{item.label}</button></li>)}</ol></nav>`; break;
    case "table": output = `<table ${attrs}><caption>{label}</caption><thead data-part=${part("header")}><tr>{columns.map(column=><th key={column.key} scope="col">{column.label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.key} data-part=${part("row")}>{row.cells.map((cell,index)=><td key={columns[index]!.key} data-part=${part("cell")}>{cell}</td>)}</tr>)}</tbody></table>`; break;
    case "list": output = `<ul ${attrs} aria-label={label}>{items.map(item=><li key={item.key} data-part=${part("item")}>{item.label}</li>)}</ul>`; break;
    case "surface": output = `<section ${attrs}>{header!=null&&<header data-part=${part("header")}>{header}</header>}${body}{actions!=null&&<footer data-part=${part("actions")}>{actions}</footer>}</section>`; break;
    case "layout": {
      const render = (partId: string): string => {
        const current = component.parts.find(part => part.id === partId)!;
        const slot = catalog.slots.find(slot => slot.ownerPartRef === current.id);
        const text = current.text === undefined ? slot ? `{${current.role}}` : "" : `{${JSON.stringify(current.text)}}`;
        const tag = component.web.elements?.[current.id] ?? "div";
        return `<${tag} ${current.role === "root" ? attrs : `data-part=${JSON.stringify(current.id)}`}>${text}${(component.web.layout[current.id]?.childOrder ?? []).map(render).join("")}${composition.render(current.id)}</${tag}>`;
      };
      output = render(component.parts.find(part => part.role === "root")!.id); break;
    }
    case "field": output = `<fieldset ${attrs} aria-invalid={invalid} aria-required={required}><legend data-part=${part("label")}>{label}</legend>${body}${description}<span data-part=${part("error")}>{invalid?description:""}</span></fieldset>`; break;
    case "alert": output = `<div ${attrs} role="status"><strong data-part=${part("title")}>{label}</strong>${body}{dismissible&&<button type="button" data-part=${part("close")} onClick={()=>onDismissRequest({})}>{${JSON.stringify(component.sampleContent.closeLabel)}}</button>}</div>`; break;
    case "toolbar": output = `<div ${attrs} role=${JSON.stringify(semantic.role)} aria-label={label} onKeyDown={event=>catalogMoveFocus(event,"button")}>${body}</div>`; break;
    default: throw new TargetError(TARGET_CODE.UNSUPPORTED, `React has no catalog realization for ${semantic.kind}`, component.id);
  }
  const required = catalog.slots.some(slot => slot.min !== 0 && !(component.instances ?? []).some(instance => instance.ownerPartRef === slot.ownerPartRef) && !component.parts.some(part => part.parent === slot.ownerPartRef && part.elementKind) && component.parts.some(part => part.id === slot.ownerPartRef && part.role === "body"));
  return `${api.declaration}\nexport function ${name}(props:${name}Props) { ${api.destructure} ${composition.hooks} ${authoredBehavior.hooks} ${semantic.kind === "layout" ? "" : authored.hooks} const id=React.useId(); ${hooks} ${required ? 'if(body==null)throw new Error("This component requires body content");' : ""} return ${semantic.kind === "layout" ? output : authored.wrap(output)}; }\n`;
}
