import type { StudioComponent } from "../../ads-core/src/index.ts";
import { componentSymbol } from "./generator-input.ts";
import { catalogProps } from "./catalog-source-types.ts";
import { TargetError } from "./target-error.ts";
import { TARGET_CODE } from "./constants.ts";

/** Native control and accessibility roles are selected by declared meaning, never by a generic button fallback. */
export function catalogNativeReactComponent(component: StudioComponent): string {
  const name = componentSymbol(component), catalog = component.catalog!, api = catalogProps(component, name), semantic = catalog.semantic;
  const root = component.parts.find(part => part.role === "root")!;
  const part = (role: string): string => JSON.stringify(component.parts.find(part => part.role === role)?.id ?? root.id);
  const availability = catalog.values.some(value => value.name === "disabled") ? ",disabled" : "";
  const style = `visual(${name}Design,${part("root")},variant${availability})`, text = `textVisual(${name}Design,${part("body")},${part("root")},variant${availability})`;
  const label = `<Text style={${text}}>{label}</Text>`, body = `<TextContext.Provider value={${text}}><View>{body}</View></TextContext.Provider>`;
  const group = (content: string): string => `<View style={${style}}>${content}</View>`;
  let output: string;
  switch (semantic.kind) {
    case "button": output = `<Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPress={()=>onActivate({})} style={({pressed})=>[visual(${name}Design,${part("root")},variant,disabled,pressed),{minWidth:48,minHeight:48}]}>{${label}}</Pressable>`.replace(`>{${label}}`, `>${label}`); break;
    case "text-input": case "textarea": output = group(`${label}<NativeTextInput accessibilityLabel={label} accessibilityHint={description} value={value} placeholder={placeholder} editable={!disabled&&!readOnly} multiline={${semantic.kind === "textarea"}} secureTextEntry={${semantic.inputType === "password"}} accessibilityState={{disabled}} onChangeText={value=>onValueChangeRequest({value})} style={[${text},{minHeight:48,borderWidth:1,padding:8}]}/><Text style={${text}}>{description}{invalid?" · Invalid":""}</Text>`); break;
    case "switch": output = group(`${label}<NativeSwitch accessibilityLabel={label} accessibilityHint={description} value={checked} disabled={disabled} onValueChange={value=>onCheckedChangeRequest({value})}/>`); break;
    case "checkbox": case "radio": case "toggle": {
      const selected = semantic.kind === "toggle" ? "pressed" : "checked", request = semantic.kind === "toggle" ? "onPressedChangeRequest({value:!pressed})" : `onCheckedChangeRequest({value:${semantic.kind === "radio" ? "true" : "indeterminate||!checked"}})`;
      output = `<Pressable accessibilityRole=${JSON.stringify(semantic.kind === "toggle" ? "button" : semantic.kind)} accessibilityLabel={label} accessibilityHint={description} accessibilityState={{disabled,${semantic.kind === "toggle" ? "selected" : "checked"}:${semantic.kind === "checkbox" ? 'indeterminate?"mixed":checked' : selected}}} disabled={disabled} onPress={()=>${request}} style={({pressed:active})=>[visual(${name}Design,${part("root")},variant,disabled,active),{minWidth:48,minHeight:48,flexDirection:"row",alignItems:"center"}]}><Text style={${text}}>{${semantic.kind === "checkbox" ? 'indeterminate?"− ":' : ""}${selected}?"✓ ":"○ "}{label}</Text></Pressable>`; break;
    }
    case "choice-group": case "select": {
      const buttons = ["catalog.togglegroup","catalog.togglebuttongroup","catalog.segmentedcontrol"].includes(catalog.catalogId);
      const multiple = semantic.selection === "multiple", selected = multiple ? "selectedKeys.includes(item.key)" : "selectedKey===item.key";
      const request = multiple ? "onSelectedKeysChangeRequest({value:selectedKeys.includes(item.key)?selectedKeys.filter(key=>key!==item.key):[...selectedKeys,item.key]})" : "onSelectedKeyChangeRequest({value:item.key})";
      output = group(`${label}${semantic.kind === "select" ? `<Pressable accessibilityRole="button" accessibilityLabel={label+" clear"} disabled={disabled} onPress={()=>onSelectedKeyChangeRequest({value:null})} style={{minHeight:48,padding:8}}><Text style={${text}}>Choose…</Text></Pressable>` : ""}<View accessibilityRole=${JSON.stringify(buttons ? "none" : multiple ? "list" : "radiogroup")} accessibilityLabel={label}>{items.map(item=><Pressable key={item.key} accessibilityRole=${JSON.stringify(buttons ? "button" : multiple ? "checkbox" : "radio")} accessibilityLabel={item.label} accessibilityState={{${buttons?"selected":"checked"}:${selected},disabled:disabled||item.disabled}} disabled={disabled||item.disabled} onPress={()=>${request}} style={{minHeight:48,padding:8,flexDirection:"row"}}><Text style={${text}}>{${selected}?"✓ ":"○ "}{item.label}</Text></Pressable>)}</View>`); break;
    }
    case "progress": output = group(`${label}<View accessibilityRole="progressbar" accessibilityLabel={label} accessibilityValue={indeterminate?{text:"In progress"}:{min,max,now:value}}>{indeterminate?<NativeActivityIndicator accessibilityLabel={label}/>:<View style={{height:8,backgroundColor:"#d1d5db"}}><View style={{height:8,width:(((value-min)/(max-min)*100)+"%") as DimensionValue,backgroundColor:${text}.color??"#111827"}}/></View>}<Text style={${text}}>{indeterminate?label:value}</Text></View>`); break;
    case "loading": output = group(`<NativeActivityIndicator animating={loading} accessibilityLabel={label}/>${label}`); break;
    case "badge": case "text": output = `<View style={${style}}><Text accessibilityRole=${JSON.stringify(semantic.role === "heading" ? "header" : "text")} style={${text}}>{text}</Text></View>`; break;
    case "separator": output = `<View accessibilityRole="none" style={[${style},{height:orientation==="horizontal"?1:undefined,width:orientation==="vertical"?1:undefined,backgroundColor:${style}.backgroundColor??${text}.color??"#9ca3af"}]}/>`; break;
    case "tabs": output = group(`<View accessibilityRole="tablist" accessibilityLabel={label} style={{flexDirection:"row"}}>{items.map(item=><Pressable key={item.key} accessibilityRole="tab" accessibilityLabel={item.label} accessibilityState={{selected:selectedKey===item.key,disabled:item.disabled}} disabled={item.disabled} onPress={()=>onSelectedKeyChangeRequest({value:item.key})} style={{minHeight:48,padding:8}}><Text style={${text}}>{item.label}</Text></Pressable>)}</View><TextContext.Provider value={${text}}><View>{panel??<Text style={${text}}>{items.find(item=>item.key===selectedKey)?.label}</Text>}</View></TextContext.Provider>`); break;
    case "accordion": output = group(`{items.map(item=><View key={item.key}><Pressable accessibilityRole="button" accessibilityLabel={item.label} accessibilityState={{expanded:expandedKeys.includes(item.key),disabled:item.disabled}} disabled={item.disabled} onPress={()=>onExpandedKeysChangeRequest({value:expandedKeys.includes(item.key)?expandedKeys.filter(key=>key!==item.key):multiple?[...expandedKeys,item.key]:[item.key]})} style={{minHeight:48,padding:8}}><Text style={${text}}>{item.label}</Text></Pressable>{expandedKeys.includes(item.key)&&<TextContext.Provider value={${text}}><View>{panel??<Text style={${text}}>{item.label}</Text>}</View></TextContext.Provider>}</View>)}`); break;
    case "dialog": output = group(`<Pressable accessibilityRole="button" accessibilityLabel={label} onPress={()=>onOpenChangeRequest({value:true})} style={{minHeight:48,padding:8}}>${label}</Pressable><NativeModal visible={open} transparent onRequestClose={()=>onOpenChangeRequest({value:false})}><View style={{flex:1,justifyContent:"center",padding:24,backgroundColor:"rgba(0,0,0,.4)"}}><View accessibilityViewIsModal style={[${style},{backgroundColor:${style}.backgroundColor??"white"}]}><Text accessibilityRole="header" style={${text}}>{label}</Text>${body}<Text style={${text}}>{description}</Text><Pressable accessibilityRole="button" accessibilityLabel=${JSON.stringify(component.sampleContent.closeLabel)} onPress={()=>onOpenChangeRequest({value:false})} style={{minHeight:48,padding:8}}><Text style={${text}}>{${JSON.stringify(component.sampleContent.closeLabel)}}</Text></Pressable></View></View></NativeModal>`); break;
    case "list": output = group(`<View accessibilityRole="list" accessibilityLabel={label}>{items.map(item=><Text key={item.key} style={${text}}>{item.label}</Text>)}</View>`); break;
    case "navigation": output = group(`<View accessibilityLabel={label}>{items.map(item=><Pressable key={item.key} accessibilityRole="button" accessibilityLabel={item.label} accessibilityState={{selected:currentKey===item.key,disabled:item.disabled}} disabled={item.disabled} onPress={()=>onCurrentKeyChangeRequest({value:item.key})} style={{minWidth:48,minHeight:48,padding:8}}><Text style={${text}}>{item.label}</Text></Pressable>)}</View>`); break;
    case "surface": output = group(`<TextContext.Provider value={${text}}>{header!=null&&<View>{header}</View>}<View>{body}</View>{actions!=null&&<View>{actions}</View>}</TextContext.Provider>`); break;
    case "layout": output = group(body); break;
    case "field": output = group(`${label}${body}<Text style={${text}}>{description}{required?" · Required":""}{invalid?" · Invalid":""}</Text>`); break;
    case "alert": output = group(`<Text accessibilityLiveRegion="polite" style={${text}}>{label}</Text>${body}{dismissible&&<Pressable accessibilityRole="button" onPress={()=>onDismissRequest({})} style={{minHeight:48,padding:8}}><Text style={${text}}>{${JSON.stringify(component.sampleContent.closeLabel)}}</Text></Pressable>}`); break;
    default: throw new TargetError(TARGET_CODE.UNSUPPORTED, `React Native has no catalog realization for ${semantic.kind}`, component.id);
  }
  const required = catalog.slots.some(slot => slot.min !== 0 && component.parts.some(part => part.id === slot.ownerPartRef && part.role === "body"));
  return `const ${name}Design:Design=${JSON.stringify(component.mobile)};\n${api.declaration}\nexport function ${name}(props:${name}Props) { ${api.destructure} ${required ? 'if(body==null)throw new Error("This component requires body content");' : ""} return ${output}; }\n`;
}
