import { canonicalJson } from "../../ads-core/src/index.ts";
import type { StudioProjection } from "../../ads-core/src/index.ts";
import { TARGET_DEPENDENCIES, TARGET_PACK_VERSION } from "./constants.ts";
import type { SourceFile, TargetId } from "./contracts.ts";
import { componentSymbol, sourceLiteral } from "./generator-input.ts";

/** Emit independently consumable package metadata with exact, target-specific dependency pins. */
export function packageFiles(projection: StudioProjection, target: TargetId, packageName: string): SourceFile[] {
  const tokenData = { foundationId: projection.foundation.foundationId, contexts: projection.foundation.contexts, tokens: projection.foundation.tokens };
  const tokenJson = `${canonicalJson(tokenData)}\n`;
  const files: SourceFile[] = [{ path: "tokens.json", text: tokenJson }];
  const symbols = projection.components.map((component) => `${componentSymbol(component)} — ${component.name} (${component.archetype}, ADS ${component.id})`).join("\n");
  const usage = target === "react" ? "Run pnpm install, then pnpm build. Import the exported functions from this package and explicitly import this-package/styles.css once in your application. Place notifications inside AxiomToastHost and content inside AxiomThemeProvider. Pass onActivate/onCloseRequest callbacks; the consumer changes open. Card body is required. The CSS and source are user-owned. SSR is supported as source; hydration/browser behavior must be verified with your consumer. This package makes no React Server Component claim." : target === "react-native" ? "Use Expo SDK57 with React19.2.3 and React Native0.86.3. Run pnpm install and pnpm build. Import the package from an Expo application; Metro consumes the react-native source entry. Wrap content in AxiomThemeProvider and notifications in AxiomToastHost. Card body is a React Native node, such as Text. An Expo export verifies the JavaScript bundle, not Android/iOS execution. Do not inherit a Web application's React19.3 version." : target === "swiftui" ? "Add this directory as a local Swift package in an iOS17+ Xcode application, then import AxiomDesign. Wrap notification instances in AxiomToastHost. Supply consumer callbacks and controlled open; Card takes a required ViewBuilder body and optional AnyView header/actions. Build and test an iOS simulator destination discovered with xcodebuild -showdestinations. This iOS SwiftUI package imports UIKit for announcements; Windows Swift and macOS-only swift build do not verify it." : "Use Gradle9.3.1/JDK17 and Android SDK37/build-tools36.0.0. This is an Android library project: gradle assembleDebug lint testDebugUnitTest. AGP9 uses built-in Kotlin; do not add the old Kotlin Android plugin. Generate a dependency lock in your environment with gradle dependencies --write-locks and retain it. Import design.axiom functions into a Compose application. Wrap content in AxiomThemeProvider and notification instances in AxiomToastHost. Pass controlled open/onCloseRequest; set reducedMotion from your accessibility policy. Native build, emulator and assistive-technology tests are required before release.";
  files.push({ path: "README.md", text: `# ${packageName}\n\nGenerated user-owned ${target} source from ADS project ${projection.projectId}, revision ${projection.revision}.\n\n${usage}\n\n## Public component mapping\n\n${symbols}\n\nTokens and the selected theme contexts are fixed to this snapshot. All thirteen resolved DTCG values are retained in tokens.json; component output supports only the declared sRGB/logical-dimension visual mapping. Generate another package revision to adopt another context.\n\nNo package installation, publishing, account connection or runtime network service is required by generation. The manifest records generation separately from independent compilation and platform execution.\n` });
  files.push({ path: "NOTICE.md", text: `Generated source is delivered for the user's own modification and distribution. Keep the source manifest for provenance. React, React Native and Expo dependencies use MIT licenses; AndroidX/Compose, Kotlin, AGP and Gradle use Apache-2.0; Swift uses Apache-2.0 with Runtime Library Exception. Apple SDKs and platform tools are supplied under their own licenses. No third-party font, icon or media asset is embedded by this profile. This notice does not replace dependency notices retained by the consuming package manager.\n` });
  if(target==="react-native")files.find(file=>file.path==="README.md")!.text+="\nUse exported AxiomText inside Card body/header/actions slots to inherit authored root and part color/fontSize. React Native primitive Text does not inherit View text styles and remains consumer-styled. Button and Toast text receive this inheritance automatically.\n";
  const catalog = projection.components.filter(component => component.catalog);
  if (catalog.length) files.find(file => file.path === "README.md")!.text += `\n## Catalog contracts\n\n${catalog.map(component => `${componentSymbol(component)}: ${component.catalog!.catalogId}; semantic ${component.catalog!.semantic.kind}; consumer-owned values ${component.catalog!.values.map(value => value.name).join(", ") || "none"}; requests ${component.catalog!.events.map(event => event.name).join(", ") || "none"}.`).join("\n\n")}\n\n${target === "react" || target === "react-native" ? "Required callbacks receive the typed ADS request object, for example onCheckedChangeRequest({value: true}). The caller updates checked; emitting a request never adopts its value. Body slots are React nodes and required bodies must be supplied." : "Native value callbacks unwrap the single ADS payload.value field into the declared Swift/Kotlin argument; zero-field requests take no arguments. Values remain consumer-owned. Required body slots are AnyView (SwiftUI) or composable lambdas (Compose). Collection items use public AxiomCatalogItem with stable key, label and disabled fields."}\n\n${target === "react" ? "Place catalog overlays inside AxiomOverlayHost. Dialog uses native showModal/cancel and delegates open changes. Tabs use manual activation: Arrow/Home/End move focus, Enter/Space selects. Choice collections and menus need stable unique keys; passive tooltip content must not contain focusable controls." : "Native catalog inner controls retain platform presentation. This profile maps root visuals only; edited internal-part appearance/layout and custom pressed styling are rejected. React Native select is an inline accessible choice group rather than a platform popup picker."}\n\nCatalog timelines are authored data; only the unchanged default motion policy is accepted for this source profile, with system-owned control feedback. Full provider-specific behavior, automatic overlay scheduling, native compiler/device and assistive-technology verification remain separate requirements.\n`;
  if (target === "react" || target === "react-native") {
    const dependencies = TARGET_DEPENDENCIES[target];
    // Node/Metro export conditions have ordered semantics; canonical ADS key sorting is inapplicable here.
    files.push({ path: "package.json", text: `${JSON.stringify({ name: packageName, version: TARGET_PACK_VERSION, private: true, type: "module", main: "./dist/index.js", types: "./dist/index.d.ts", ...(target === "react-native" ? { "react-native": "./src/index.tsx" } : {}), exports: { ".": { types: "./dist/index.d.ts", ...(target === "react-native" ? { "react-native": "./src/index.tsx" } : {}), default: "./dist/index.js" }, ...(target === "react" ? { "./styles.css": "./src/styles.css" } : {}) }, files: ["dist", "src", "tokens.json", "axiom.delivery.json", "NOTICE.md", "README.md"], sideEffects: target === "react" ? ["**/*.css"] : false, scripts: { build: "tsc -p tsconfig.json" }, peerDependencies: target === "react" ? { react: dependencies.react, "react-dom": TARGET_DEPENDENCIES.react["react-dom"] } : { react: dependencies.react, "react-native": TARGET_DEPENDENCIES["react-native"]["react-native"], expo: TARGET_DEPENDENCIES["react-native"].expo }, devDependencies: target === "react" ? TARGET_DEPENDENCIES.react : TARGET_DEPENDENCIES["react-native"] },null,2)}\n` });
    files.push({ path: "tsconfig.json", text: `${canonicalJson({ compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "Bundler", jsx: "react-jsx", strict: true, declaration: true, outDir: "dist", rootDir: "src", lib: target === "react" ? ["ES2022", "DOM"] : ["ES2022"], types: ["react"], skipLibCheck: false }, include: ["src"] })}\n` });
    files.push({ path: "src/tokens.ts", text: `// Resolved DTCG values are data; unsupported target conversions remain explicit.\nexport const tokens = ${canonicalJson(Object.fromEntries(projection.foundation.tokens.map((token) => [token.id, { name: token.name, type: token.type, value: token.value }])))} as const;\nexport const themeContexts = ${canonicalJson(projection.foundation.contexts)} as const;\n` });
  } else if (target === "swiftui") {
    files.push({ path: "Package.swift", text: `// swift-tools-version: ${TARGET_DEPENDENCIES.swiftui.swiftTools}\nimport PackageDescription\nlet package = Package(name: "AxiomDesign", platforms: [.iOS(.v17)], products: [.library(name: "AxiomDesign", targets: ["AxiomDesign"])], targets: [.target(name: "AxiomDesign", resources: [.copy("Resources/tokens.json")])])\n` });
    files.push({ path: "Sources/AxiomDesign/Resources/tokens.json", text: tokenJson });
    files.push({ path: "Sources/AxiomDesign/Tokens.swift", text: `// Full DTCG data is preserved without unsupported type conversion.\npublic enum AxiomTokens { public static let definitionJSON = ${sourceLiteral(tokenJson,"swift")} }\n` });
  } else {
    const pins = TARGET_DEPENDENCIES.compose;
    files.push({ path: "settings.gradle.kts", text: `pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nrootProject.name = "AxiomDesign"\n` });
    files.push({ path: "build.gradle.kts", text: `plugins { id("com.android.library") version "${pins.agp}"; id("org.jetbrains.kotlin.plugin.compose") version "${pins.kotlin}" }\nandroid { namespace = "design.axiom"; compileSdk = ${pins.compileSdk}; buildToolsVersion = "${pins.buildTools}"; defaultConfig { minSdk = ${pins.minSdk} }; buildFeatures { compose = true }; compileOptions { sourceCompatibility = JavaVersion.VERSION_17; targetCompatibility = JavaVersion.VERSION_17 } }\nkotlin { compilerOptions { jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17) } }\ndependencies { implementation(platform("androidx.compose:compose-bom:${pins.composeBom}")); implementation("androidx.compose.material3:material3"); implementation("androidx.compose.foundation:foundation"); implementation("androidx.compose.animation:animation-core") }\ndependencyLocking { lockAllConfigurations() }\n` });
    files.push({ path: "src/main/AndroidManifest.xml", text: `<manifest xmlns:android="http://schemas.android.com/apk/res/android" />\n` });
    files.push({ path: "src/main/assets/axiom-tokens.json", text: tokenJson });
    files.push({ path: "src/main/kotlin/design/axiom/AxiomTokens.kt", text: `package design.axiom\n// Full token data stays in an Android asset, avoiding JVM constant-pool string limits.\npublic object AxiomTokens { public const val assetPath: String = "axiom-tokens.json" }\n` });
  }
  return files;
}
