/** Generated from the pinned Mantine first-demo source manifest. */
export const referenceTemplates = [
  {
    "sourceRow": 2,
    "catalogId": "catalog.datepickerinput",
    "name": "DatePickerInput",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/date-picker-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/_shared/picker-input-usage.demo.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 3,
    "catalogId": "catalog.datetimepicker",
    "name": "DateTimePicker",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/date-time-picker/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/DateTimePicker/DateTimePicker.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 4,
    "catalogId": "catalog.inlinedatetimepicker",
    "name": "InlineDateTimePicker",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/inline-date-time-picker/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/InlineDateTimePicker/InlineDateTimePicker.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 5,
    "catalogId": "catalog.dateinput",
    "name": "DateInput",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/date-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/DateInput/DateInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 6,
    "catalogId": "catalog.monthpicker",
    "name": "MonthPicker",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/month-picker/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/_shared/picker-usage.demo.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 7,
    "catalogId": "catalog.monthpickerinput",
    "name": "MonthPickerInput",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/month-picker-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/_shared/picker-input-usage.demo.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 8,
    "catalogId": "catalog.yearpicker",
    "name": "YearPicker",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/year-picker/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/_shared/picker-usage.demo.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 9,
    "catalogId": "catalog.yearpickerinput",
    "name": "YearPickerInput",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/year-picker-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/_shared/picker-input-usage.demo.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 10,
    "catalogId": "catalog.timeinput",
    "name": "TimeInput",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/time-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/TimeInput/TimeInput.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 11,
    "catalogId": "catalog.timepicker",
    "name": "TimePicker",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/time-picker/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/TimePicker/TimePicker.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 12,
    "catalogId": "catalog.timegrid",
    "name": "TimeGrid",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/time-grid/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/TimeGrid/TimeGrid.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 13,
    "catalogId": "catalog.timevalue",
    "name": "TimeValue",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/time-value/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/TimeValue/TimeValue.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 14,
    "catalogId": "catalog.minicalendar",
    "name": "MiniCalendar",
    "provider": "Mantine Dates",
    "package": "@mantine/dates",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/dates/mini-calendar/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dates/MiniCalendar/MiniCalendar.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 16,
    "catalogId": "catalog.areachart",
    "name": "AreaChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/area-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/AreaChart/AreaChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 17,
    "catalogId": "catalog.barchart",
    "name": "BarChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/bar-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/BarChart/BarChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 18,
    "catalogId": "catalog.linechart",
    "name": "LineChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/line-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/LineChart/LineChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 19,
    "catalogId": "catalog.compositechart",
    "name": "CompositeChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/composite-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/CompositeChart/CompositeChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 20,
    "catalogId": "catalog.candlestickchart",
    "name": "CandlestickChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/candlestick-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/CandlestickChart/CandlestickChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 21,
    "catalogId": "catalog.donutchart",
    "name": "DonutChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/donut-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/DonutChart/DonutChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 22,
    "catalogId": "catalog.piechart",
    "name": "PieChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/pie-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/PieChart/PieChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 23,
    "catalogId": "catalog.funnelchart",
    "name": "FunnelChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/funnel-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/FunnelChart/FunnelChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 24,
    "catalogId": "catalog.radarchart",
    "name": "RadarChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/radar-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/RadarChart/RadarChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 25,
    "catalogId": "catalog.scatterchart",
    "name": "ScatterChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/scatter-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/ScatterChart/ScatterChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 26,
    "catalogId": "catalog.bubblechart",
    "name": "BubbleChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/bubble-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/BubbleChart/BubbleChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 27,
    "catalogId": "catalog.radialbarchart",
    "name": "RadialBarChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/radial-bar-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/RadialBarChart/RadialBarChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 28,
    "catalogId": "catalog.sparkline",
    "name": "Sparkline",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/sparkline/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/Sparkline/Sparkline.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 29,
    "catalogId": "catalog.heatmap",
    "name": "Heatmap",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/heatmap/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/Heatmap/Heatmap.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 30,
    "catalogId": "catalog.barslist",
    "name": "BarsList",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/bars-list/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/BarsList/BarsList.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 31,
    "catalogId": "catalog.bulletchart",
    "name": "BulletChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/bullet-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/BulletChart/BulletChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 32,
    "catalogId": "catalog.gaugechart",
    "name": "GaugeChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/gauge-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/GaugeChart/GaugeChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 33,
    "catalogId": "catalog.wafflechart",
    "name": "WaffleChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/waffle-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/WaffleChart/WaffleChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 34,
    "catalogId": "catalog.treemap",
    "name": "Treemap",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/treemap/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/Treemap/Treemap.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 35,
    "catalogId": "catalog.sunburstchart",
    "name": "SunburstChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/sunburst-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/SunburstChart/SunburstChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 36,
    "catalogId": "catalog.sankeychart",
    "name": "SankeyChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/sankey-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/SankeyChart/SankeyChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 37,
    "catalogId": "catalog.matrixchart",
    "name": "MatrixChart",
    "provider": "Mantine Charts",
    "package": "@mantine/charts",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/charts/matrix-chart/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/charts/MatrixChart/MatrixChart.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 38,
    "catalogId": "catalog.schedule",
    "name": "Schedule",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/schedule/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/Schedule/Schedule.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 39,
    "catalogId": "catalog.dayview",
    "name": "DayView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/day-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/DayView/DayView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 40,
    "catalogId": "catalog.monthview",
    "name": "MonthView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/month-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/MonthView/MonthView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 41,
    "catalogId": "catalog.weekview",
    "name": "WeekView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/week-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/WeekView/WeekView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 42,
    "catalogId": "catalog.yearview",
    "name": "YearView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/year-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/YearView/YearView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 43,
    "catalogId": "catalog.mobilemonthview",
    "name": "MobileMonthView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/mobile-month-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/MobileMonthView/MobileMonthView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 44,
    "catalogId": "catalog.agendaview",
    "name": "AgendaView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/agenda-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/AgendaView/AgendaView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 45,
    "catalogId": "catalog.resourcesdayview",
    "name": "ResourcesDayView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/resources-day-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/ResourcesDayView/ResourcesDayView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 46,
    "catalogId": "catalog.resourcesweekview",
    "name": "ResourcesWeekView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/resources-week-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/ResourcesWeekView/ResourcesWeekView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 47,
    "catalogId": "catalog.resourcesmonthview",
    "name": "ResourcesMonthView",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/resources-month-view/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/ResourcesMonthView/ResourcesMonthView.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 48,
    "catalogId": "catalog.resourcesschedule",
    "name": "ResourcesSchedule",
    "provider": "Mantine Schedule",
    "package": "@mantine/schedule",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/schedule/resources-schedule/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/schedule/ResourcesSchedule/ResourcesSchedule.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 49,
    "catalogId": "catalog.codehighlight",
    "name": "CodeHighlight",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/code-highlight",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/code-highlight/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/code-highlight/CodeHighlight.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 50,
    "catalogId": "catalog.notificationssystem",
    "name": "Notifications system",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/notifications",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/notifications/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/notifications/Notifications.demo.base.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 51,
    "catalogId": "catalog.spotlight",
    "name": "Spotlight",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/spotlight",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/spotlight/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/spotlight/Spotlight.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 53,
    "catalogId": "catalog.lightbox",
    "name": "Lightbox",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/lightbox",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/lightbox/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/lightbox/Lightbox.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 54,
    "catalogId": "catalog.dropzone",
    "name": "Dropzone",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/dropzone",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/dropzone/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/dropzone/Dropzone.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 55,
    "catalogId": "catalog.navigationprogress",
    "name": "NavigationProgress",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/nprogress",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/nprogress/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/nprogress/NProgress.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 56,
    "catalogId": "catalog.modalsmanager",
    "name": "Modals manager",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/modals",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/modals/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/modals/Modals.demo.confirm.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 57,
    "catalogId": "catalog.richtexteditor",
    "name": "Rich text editor",
    "provider": "Mantine Other Extensions",
    "package": "@mantine/tiptap",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/x/tiptap/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/tiptap/TipTap.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 122,
    "catalogId": "catalog.appshell",
    "name": "AppShell",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/app-shell/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/apps/mantine.dev/src/app-shell-examples/examples/BasicAppShell/BasicAppShell.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 124,
    "catalogId": "catalog.center",
    "name": "Center",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/center/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Center/Center.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 125,
    "catalogId": "catalog.container",
    "name": "Container",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/container/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Container/Container.demo.breakout.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 126,
    "catalogId": "catalog.flex",
    "name": "Flex",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/flex/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Flex/Flex.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 127,
    "catalogId": "catalog.grid",
    "name": "Grid",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/grid/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Grid/Grid.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 128,
    "catalogId": "catalog.group",
    "name": "Group",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/group/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Group/Group.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 129,
    "catalogId": "catalog.simplegrid",
    "name": "SimpleGrid",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/simple-grid/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/SimpleGrid/SimpleGrid.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 130,
    "catalogId": "catalog.space",
    "name": "Space",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/space/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Space/Space.demo.horizontal.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 132,
    "catalogId": "catalog.stack",
    "name": "Stack",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/stack/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Stack/Stack.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 133,
    "catalogId": "catalog.alphaslider",
    "name": "AlphaSlider",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/alpha-slider/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ColorPicker/ColorPicker.demo.alphaSlider.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 134,
    "catalogId": "catalog.angleslider",
    "name": "AngleSlider",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/angle-slider/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/AngleSlider/AngleSlider.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 136,
    "catalogId": "catalog.chip",
    "name": "Chip",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/chip/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Chip/Chip.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 137,
    "catalogId": "catalog.colorinput",
    "name": "ColorInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/color-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ColorInput/ColorInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 138,
    "catalogId": "catalog.colorpicker",
    "name": "ColorPicker",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/color-picker/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ColorPicker/ColorPicker.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 139,
    "catalogId": "catalog.fieldset",
    "name": "Fieldset",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/fieldset/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Fieldset/Fieldset.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 140,
    "catalogId": "catalog.fileinput",
    "name": "FileInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/file-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/FileInput/FileInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 141,
    "catalogId": "catalog.hueslider",
    "name": "HueSlider",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/hue-slider/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ColorPicker/ColorPicker.demo.hueSlider.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 143,
    "catalogId": "catalog.jsoninput",
    "name": "JsonInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/json-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/JsonInput/JsonInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 144,
    "catalogId": "catalog.maskinput",
    "name": "MaskInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/mask-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/MaskInput/MaskInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 146,
    "catalogId": "catalog.numberinput",
    "name": "NumberInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/number-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/NumberInput/NumberInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 147,
    "catalogId": "catalog.passwordinput",
    "name": "PasswordInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/password-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/PasswordInput/PasswordInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 148,
    "catalogId": "catalog.pininput",
    "name": "PinInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/pin-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/PinInput/PinInput.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 149,
    "catalogId": "catalog.radio",
    "name": "Radio",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/radio/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Radio/Radio.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 150,
    "catalogId": "catalog.rangeslider",
    "name": "RangeSlider",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/range-slider/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/RangeSlider/RangeSlider.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 151,
    "catalogId": "catalog.rating",
    "name": "Rating",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/rating/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Rating/Rating.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 152,
    "catalogId": "catalog.segmentedcontrol",
    "name": "SegmentedControl",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/segmented-control/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/SegmentedControl/SegmentedControl.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 156,
    "catalogId": "catalog.textinput",
    "name": "TextInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/text-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/TextInput/TextInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 157,
    "catalogId": "catalog.autocomplete",
    "name": "Autocomplete",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/autocomplete/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Autocomplete/Autocomplete.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 158,
    "catalogId": "catalog.cascader",
    "name": "Cascader",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/cascader/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Cascader/Cascader.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 160,
    "catalogId": "catalog.comboboxpopover",
    "name": "ComboboxPopover",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/combobox-popover/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ComboboxPopover/ComboboxPopover.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 161,
    "catalogId": "catalog.multiselect",
    "name": "MultiSelect",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/multi-select/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/MultiSelect/MultiSelect.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 162,
    "catalogId": "catalog.pill",
    "name": "Pill",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/pill/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Pill/Pill.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 163,
    "catalogId": "catalog.pillsinput",
    "name": "PillsInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/pills-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/PillsInput/PillsInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 165,
    "catalogId": "catalog.tagsinput",
    "name": "TagsInput",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/tags-input/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/TagsInput/TagsInput.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 166,
    "catalogId": "catalog.treeselect",
    "name": "TreeSelect",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/tree-select/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/TreeSelect/TreeSelect.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 167,
    "catalogId": "catalog.actionicon",
    "name": "ActionIcon",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/action-icon/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ActionIcon/ActionIcon.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 169,
    "catalogId": "catalog.closebutton",
    "name": "CloseButton",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/close-button/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/CloseButton/CloseButton.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 170,
    "catalogId": "catalog.copybutton",
    "name": "CopyButton",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/copy-button/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/CopyButton/CopyButton.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 171,
    "catalogId": "catalog.filebutton",
    "name": "FileButton",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/file-button/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/FileButton/FileButton.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 172,
    "catalogId": "catalog.unstyledbutton",
    "name": "UnstyledButton",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/unstyled-button/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/UnstyledButton/UnstyledButton.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 173,
    "catalogId": "catalog.anchor",
    "name": "Anchor",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/anchor/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Anchor/Anchor.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 175,
    "catalogId": "catalog.burger",
    "name": "Burger",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/burger/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Burger/Burger.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 176,
    "catalogId": "catalog.navlink",
    "name": "NavLink",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/nav-link/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/NavLink/NavLink.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 178,
    "catalogId": "catalog.stepper",
    "name": "Stepper",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/stepper/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Stepper/Stepper.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 179,
    "catalogId": "catalog.tableofcontents",
    "name": "TableOfContents",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/table-of-contents/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/TableOfContents/TableOfContents.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 181,
    "catalogId": "catalog.tree",
    "name": "Tree",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/tree/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Tree/Tree.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 184,
    "catalogId": "catalog.loader",
    "name": "Loader",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/loader/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Loader/Loader.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 185,
    "catalogId": "catalog.notification",
    "name": "Notification",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/notification/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Notification/Notification.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 187,
    "catalogId": "catalog.ringprogress",
    "name": "RingProgress",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/ring-progress/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/RingProgress/RingProgress.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 188,
    "catalogId": "catalog.semicircleprogress",
    "name": "SemiCircleProgress",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/semi-circle-progress/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/SemiCircleProgress/SemiCircleProgress.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 190,
    "catalogId": "catalog.actionbar",
    "name": "ActionBar",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/action-bar/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ActionBar/ActionBar.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 191,
    "catalogId": "catalog.affix",
    "name": "Affix",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/affix/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Affix/Affix.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 194,
    "catalogId": "catalog.floatingindicator",
    "name": "FloatingIndicator",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/floating-indicator/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/FloatingIndicator/FloatingIndicator.demo.segmented.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 195,
    "catalogId": "catalog.floatingwindow",
    "name": "FloatingWindow",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/floating-window/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/FloatingWindow/FloatingWindow.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 197,
    "catalogId": "catalog.loadingoverlay",
    "name": "LoadingOverlay",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/loading-overlay/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/LoadingOverlay/LoadingOverlay.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 200,
    "catalogId": "catalog.modal",
    "name": "Modal",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/modal/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Modal/Modal.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 201,
    "catalogId": "catalog.overlay",
    "name": "Overlay",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/overlay/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Overlay/Overlay.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 206,
    "catalogId": "catalog.backgroundimage",
    "name": "BackgroundImage",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/background-image/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/BackgroundImage/BackgroundImage.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 209,
    "catalogId": "catalog.colorswatch",
    "name": "ColorSwatch",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/color-swatch/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ColorSwatch/ColorSwatch.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 210,
    "catalogId": "catalog.datalist",
    "name": "DataList",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/data-list/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/DataList/DataList.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 211,
    "catalogId": "catalog.image",
    "name": "Image",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/image/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Image/Image.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 212,
    "catalogId": "catalog.indicator",
    "name": "Indicator",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/indicator/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Indicator/Indicator.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 214,
    "catalogId": "catalog.numberformatter",
    "name": "NumberFormatter",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/number-formatter/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/NumberFormatter/NumberFormatter.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 215,
    "catalogId": "catalog.overflowlist",
    "name": "OverflowList",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/overflow-list/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/OverflowList/OverflowList.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 216,
    "catalogId": "catalog.rollingnumber",
    "name": "RollingNumber",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/rolling-number/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/RollingNumber/RollingNumber.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 217,
    "catalogId": "catalog.spoiler",
    "name": "Spoiler",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/spoiler/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Spoiler/Spoiler.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 218,
    "catalogId": "catalog.themeicon",
    "name": "ThemeIcon",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/theme-icon/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/ThemeIcon/ThemeIcon.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 219,
    "catalogId": "catalog.timeline",
    "name": "Timeline",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/timeline/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Timeline/Timeline.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 220,
    "catalogId": "catalog.blockquote",
    "name": "Blockquote",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/blockquote/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Blockquote/Blockquote.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 221,
    "catalogId": "catalog.code",
    "name": "Code",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/code/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Code/Code.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 222,
    "catalogId": "catalog.highlight",
    "name": "Highlight",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/highlight/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Highlight/Highlight.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 223,
    "catalogId": "catalog.list",
    "name": "List",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/list/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/List/List.demo.configurator.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 224,
    "catalogId": "catalog.mark",
    "name": "Mark",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/mark/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Mark/Mark.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 226,
    "catalogId": "catalog.text",
    "name": "Text",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/text/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Text/Text.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 227,
    "catalogId": "catalog.title",
    "name": "Title",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/title/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Title/Title.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 229,
    "catalogId": "catalog.box",
    "name": "Box",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/box/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/apps/mantine.dev/src/pages/core/box.mdx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 230,
    "catalogId": "catalog.collapse",
    "name": "Collapse",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/collapse/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Collapse/Collapse.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 232,
    "catalogId": "catalog.focustrap",
    "name": "FocusTrap",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/focus-trap/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/FocusTrap/FocusTrap.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 233,
    "catalogId": "catalog.marquee",
    "name": "Marquee",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/marquee/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Marquee/Marquee.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 234,
    "catalogId": "catalog.paper",
    "name": "Paper",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/paper/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Paper/Paper.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 235,
    "catalogId": "catalog.portal",
    "name": "Portal",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/portal/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/apps/mantine.dev/src/pages/core/portal.mdx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 237,
    "catalogId": "catalog.scroller",
    "name": "Scroller",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/scroller/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Scroller/Scroller.demo.usage.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 238,
    "catalogId": "catalog.transition",
    "name": "Transition",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/transition/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/packages/@docs/demos/src/demos/core/Tooltip/Tooltip.demo.transitions.tsx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  },
  {
    "sourceRow": 239,
    "catalogId": "catalog.visuallyhidden",
    "name": "VisuallyHidden",
    "provider": "Mantine Core",
    "package": "@mantine/core",
    "version": "9.6.1",
    "docsUrl": "https://mantine.dev/core/visually-hidden/",
    "sourceUrl": "https://github.com/mantinedev/mantine/blob/61049ecd950f6fb9ddc631decfec2edbdffe58e1/apps/mantine.dev/src/pages/core/visually-hidden.mdx",
    "upstreamCommit": "61049ecd950f6fb9ddc631decfec2edbdffe58e1"
  }
] as const;

export const demoLoaders: Record<number, () => Promise<{ default: any }>> = {
  2: () => import('./generated/row-2.tsx'),
  3: () => import('./generated/row-3.tsx'),
  4: () => import('./generated/row-4.tsx'),
  5: () => import('./generated/row-5.tsx'),
  6: () => import('./generated/row-6.tsx'),
  7: () => import('./generated/row-7.tsx'),
  8: () => import('./generated/row-8.tsx'),
  9: () => import('./generated/row-9.tsx'),
  10: () => import('./generated/row-10.tsx'),
  11: () => import('./generated/row-11.tsx'),
  12: () => import('./generated/row-12.tsx'),
  13: () => import('./generated/row-13.tsx'),
  14: () => import('./generated/row-14.tsx'),
  16: () => import('./generated/row-16.tsx'),
  17: () => import('./generated/row-17.tsx'),
  18: () => import('./generated/row-18.tsx'),
  19: () => import('./generated/row-19.tsx'),
  20: () => import('./generated/row-20.tsx'),
  21: () => import('./generated/row-21.tsx'),
  22: () => import('./generated/row-22.tsx'),
  23: () => import('./generated/row-23.tsx'),
  24: () => import('./generated/row-24.tsx'),
  25: () => import('./generated/row-25.tsx'),
  26: () => import('./generated/row-26.tsx'),
  27: () => import('./generated/row-27.tsx'),
  28: () => import('./generated/row-28.tsx'),
  29: () => import('./generated/row-29.tsx'),
  30: () => import('./generated/row-30.tsx'),
  31: () => import('./generated/row-31.tsx'),
  32: () => import('./generated/row-32.tsx'),
  33: () => import('./generated/row-33.tsx'),
  34: () => import('./generated/row-34.tsx'),
  35: () => import('./generated/row-35.tsx'),
  36: () => import('./generated/row-36.tsx'),
  37: () => import('./generated/row-37.tsx'),
  38: () => import('./generated/row-38.tsx'),
  39: () => import('./generated/row-39.tsx'),
  40: () => import('./generated/row-40.tsx'),
  41: () => import('./generated/row-41.tsx'),
  42: () => import('./generated/row-42.tsx'),
  43: () => import('./generated/row-43.tsx'),
  44: () => import('./generated/row-44.tsx'),
  45: () => import('./generated/row-45.tsx'),
  46: () => import('./generated/row-46.tsx'),
  47: () => import('./generated/row-47.tsx'),
  48: () => import('./generated/row-48.tsx'),
  49: () => import('./generated/row-49.tsx'),
  50: () => import('./generated/row-50.tsx'),
  51: () => import('./generated/row-51.tsx'),
  53: () => import('./generated/row-53.tsx'),
  54: () => import('./generated/row-54.tsx'),
  55: () => import('./generated/row-55.tsx'),
  56: () => import('./generated/row-56.tsx'),
  57: () => import('./generated/row-57.tsx'),
  122: () => import('./generated/row-122.tsx'),
  124: () => import('./generated/row-124.tsx'),
  125: () => import('./generated/row-125.tsx'),
  126: () => import('./generated/row-126.tsx'),
  127: () => import('./generated/row-127.tsx'),
  128: () => import('./generated/row-128.tsx'),
  129: () => import('./generated/row-129.tsx'),
  130: () => import('./generated/row-130.tsx'),
  132: () => import('./generated/row-132.tsx'),
  133: () => import('./generated/row-133.tsx'),
  134: () => import('./generated/row-134.tsx'),
  136: () => import('./generated/row-136.tsx'),
  137: () => import('./generated/row-137.tsx'),
  138: () => import('./generated/row-138.tsx'),
  139: () => import('./generated/row-139.tsx'),
  140: () => import('./generated/row-140.tsx'),
  141: () => import('./generated/row-141.tsx'),
  143: () => import('./generated/row-143.tsx'),
  144: () => import('./generated/row-144.tsx'),
  146: () => import('./generated/row-146.tsx'),
  147: () => import('./generated/row-147.tsx'),
  148: () => import('./generated/row-148.tsx'),
  149: () => import('./generated/row-149.tsx'),
  150: () => import('./generated/row-150.tsx'),
  151: () => import('./generated/row-151.tsx'),
  152: () => import('./generated/row-152.tsx'),
  156: () => import('./generated/row-156.tsx'),
  157: () => import('./generated/row-157.tsx'),
  158: () => import('./generated/row-158.tsx'),
  160: () => import('./generated/row-160.tsx'),
  161: () => import('./generated/row-161.tsx'),
  162: () => import('./generated/row-162.tsx'),
  163: () => import('./generated/row-163.tsx'),
  165: () => import('./generated/row-165.tsx'),
  166: () => import('./generated/row-166.tsx'),
  167: () => import('./generated/row-167.tsx'),
  169: () => import('./generated/row-169.tsx'),
  170: () => import('./generated/row-170.tsx'),
  171: () => import('./generated/row-171.tsx'),
  172: () => import('./generated/row-172.tsx'),
  173: () => import('./generated/row-173.tsx'),
  175: () => import('./generated/row-175.tsx'),
  176: () => import('./generated/row-176.tsx'),
  178: () => import('./generated/row-178.tsx'),
  179: () => import('./generated/row-179.tsx'),
  181: () => import('./generated/row-181.tsx'),
  184: () => import('./generated/row-184.tsx'),
  185: () => import('./generated/row-185.tsx'),
  187: () => import('./generated/row-187.tsx'),
  188: () => import('./generated/row-188.tsx'),
  190: () => import('./generated/row-190.tsx'),
  191: () => import('./generated/row-191.tsx'),
  194: () => import('./generated/row-194.tsx'),
  195: () => import('./generated/row-195.tsx'),
  197: () => import('./generated/row-197.tsx'),
  200: () => import('./generated/row-200.tsx'),
  201: () => import('./generated/row-201.tsx'),
  206: () => import('./generated/row-206.tsx'),
  209: () => import('./generated/row-209.tsx'),
  210: () => import('./generated/row-210.tsx'),
  211: () => import('./generated/row-211.tsx'),
  212: () => import('./generated/row-212.tsx'),
  214: () => import('./generated/row-214.tsx'),
  215: () => import('./generated/row-215.tsx'),
  216: () => import('./generated/row-216.tsx'),
  217: () => import('./generated/row-217.tsx'),
  218: () => import('./generated/row-218.tsx'),
  219: () => import('./generated/row-219.tsx'),
  220: () => import('./generated/row-220.tsx'),
  221: () => import('./generated/row-221.tsx'),
  222: () => import('./generated/row-222.tsx'),
  223: () => import('./generated/row-223.tsx'),
  224: () => import('./generated/row-224.tsx'),
  226: () => import('./generated/row-226.tsx'),
  227: () => import('./generated/row-227.tsx'),
  229: () => import('./generated/row-229.tsx'),
  230: () => import('./generated/row-230.tsx'),
  232: () => import('./generated/row-232.tsx'),
  233: () => import('./generated/row-233.tsx'),
  234: () => import('./generated/row-234.tsx'),
  235: () => import('./generated/row-235.tsx'),
  237: () => import('./generated/row-237.tsx'),
  238: () => import('./generated/row-238.tsx'),
  239: () => import('./generated/row-239.tsx'),
};
