import { useEffect, useState, useSyncExternalStore } from "react";
import type { KernelServices, StudioCategory } from "../../../modules/ads-core/src/index.ts";
import type { StudioController, StudioState } from "./controller.ts";
import { ExportDialog, ReviewDialog } from "./dialogs.tsx";
import { Icon } from "./icons.tsx";
import { Inspector } from "./inspector.tsx";
import { translate } from "./locales.ts";
import type { Locale, MessageKey } from "./locales.ts";
import { Preview } from "./preview.tsx";
import { colorHex, downloadText, editingTarget, object } from "./ui-utils.ts";

function Wordmark() { return <div className="wordmark"><span className="logo-mark" aria-hidden="true">A</span>axiom<span className="eyebrow" style={{ margin: "4px 0 0", fontSize: 8 }}>STUDIO</span></div>; }
function ErrorPanel({ state, controller, locale }: { state: StudioState; controller: StudioController; locale: Locale }) {
  if (!state.error) return null;
  const t = (key: MessageKey) => translate(locale, key);
  return <div className="error-panel" role="alert" data-testid="operation-error">{t(state.message ?? "unknownError")}<p><code>{state.error}</code></p>{state.retryable ? <button className="button secondary" data-testid="retry-operation" disabled={state.busy} onClick={() => void controller.retry()}>{t("retrySave")}</button> : state.error === "REVISION_CONFLICT" && <button className="button secondary" disabled={state.busy} onClick={() => void controller.rebase()}>{t("compareCurrent")}</button>}</div>;
}

export function App({ controller, services }: { controller: StudioController; services: KernelServices }) {
  const state = useSyncExternalStore(controller.subscribe, controller.getSnapshot);
  const [locale, setLocale] = useState<Locale>("ko"), [name, setName] = useState("");
  const [tokenId, setTokenId] = useState<string | null>(null), [componentId, setComponentId] = useState<string | null>(null), [selectedPart, setSelectedPart] = useState<string | null>(null);
  const [category, setCategory] = useState<StudioCategory>("Web"), [mode, setMode] = useState<"edit" | "run">("edit");
  const [reviewOpen, setReviewOpen] = useState(false), [exportOpen, setExportOpen] = useState(false), [downloadError, setDownloadError] = useState(false);
  const t = (key: MessageKey) => translate(locale, key);
  useEffect(() => { void controller.connect(); }, [controller]);
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  useEffect(() => { if (state.candidate) setReviewOpen(true); else setReviewOpen(false); }, [state.candidate?.id]);
  useEffect(() => {
    const keyboard = (event: KeyboardEvent) => {
      if (!(event.target instanceof Element && event.target.closest("dialog")) && !event.isComposing && !editingTarget(event.target) && (event.ctrlKey || event.metaKey) && !event.altKey && event.key.toLowerCase() === "z") {
        event.preventDefault(); void (event.shiftKey ? controller.redo() : controller.undo());
      }
    };
    const leaving = (event: BeforeUnloadEvent) => { if (controller.dirty) { event.preventDefault(); event.returnValue = ""; } };
    const refresh = () => { if (document.visibilityState === "visible") void controller.refresh(); };
    window.addEventListener("keydown", keyboard); window.addEventListener("beforeunload", leaving); window.addEventListener("focus", refresh);
    return () => { window.removeEventListener("keydown", keyboard); window.removeEventListener("beforeunload", leaving); window.removeEventListener("focus", refresh); };
  }, [controller]);
  const projection = state.projection;
  useEffect(() => { if (projection && !tokenId && !componentId) setTokenId(projection.foundation.tokens[0]?.id ?? null); }, [projection, tokenId, componentId]);
  const component = projection?.components.find(item => item.id === componentId) ?? (tokenId ? null : projection?.components[0] ?? null);
  const selectComponent = (id: string, partId?: string) => {
    setTokenId(null); setComponentId(id); setSelectedPart(partId ?? projection?.components.find(item => item.id === id)?.parts.find(part => part.role === "root")?.id ?? null);
  };
  const languageButton = <button className="locale-button" data-testid="locale-toggle" aria-label={t("language")} onClick={() => setLocale(locale === "ko" ? "en" : "ko")}>{locale === "ko" ? "EN" : "KO"}</button>;
  if (state.loading) return <div className="loading-screen" role="status"><div><div className="logo-mark">A</div>{t("loading")}</div></div>;
  if (!state.project || !Object.keys(state.project.documents).length) return <main className="onboarding" data-testid="onboarding"><section className="welcome-left"><Wordmark /><span className="eyebrow">{t("beginning")}</span><h1>{t("title")}</h1><p>{t("intro")}</p><div className="welcome-art" aria-hidden="true"><span /><span /><span /></div></section><section className="welcome-form">{languageButton}<span className="eyebrow">01 / {t("foundation")}</span><h2>{t("starter")}</h2><p>{t("starterDescription")}</p><div className="starter-tokens" aria-hidden="true"><i /><i /><i /><i /></div><ErrorPanel state={state} controller={controller} locale={locale} /><form onSubmit={event => { event.preventDefault(); void controller.createProject(name || (locale === "ko" ? "나의 디자인 시스템" : "My design system")); }}><div className="field"><label htmlFor="project-name">{t("projectName")}</label><input id="project-name" data-testid="project-name" maxLength={120} value={name} disabled={state.busy || Boolean(state.project)} placeholder={t("projectPlaceholder")} onChange={event => setName(event.target.value)} /></div><div className="storage-choice"><strong><span className="dot" />{t("browserStorage")}</strong><p>{t("browserStorageHelp")}</p></div><button className="button primary" style={{ width: "100%" }} data-testid="start-project" disabled={state.busy || state.retryable} type="submit">{state.busy ? t("saving") : t("create")}<Icon name="arrow" /></button></form><p className="help">{t("folderPending")}</p></section></main>;

  const working = state.plan?.project ?? state.project;
  const foundation = projection?.foundation.foundationId ? working.documents[projection.foundation.foundationId]?.document : undefined;
  const themes = Array.isArray(foundation?.themeSets) ? foundation.themeSets.filter(object).filter(item => typeof item.id === "string") : [];
  const dirty = controller.dirty;
  const savedLabel = state.busy ? t("saving") : state.error ? t("failedSave") : state.candidate ? t("reviewing") : dirty ? t("unsaved") : t("saved");
  const pending = state.authoring.pendingCandidates.find(item => item.baseRevision === state.project!.revision) ?? state.authoring.pendingCandidates.at(-1);
  const reviewAvailable = Boolean(state.plan?.updates.length) && !state.error && !state.pendingBuffers.length && !state.busy && !state.retryable;
  const downloadProject = async () => {
    setDownloadError(false);
    try { const bundle = await controller.exportProject(); if (!bundle) throw new Error("No project source"); downloadText("axiom-project.json", JSON.stringify(bundle, null, 2)); } catch { setDownloadError(true); }
  };
  return <div className="app" data-testid="studio-app">
    <aside className="sidebar" aria-label={t("workspace")}><Wordmark /><div className="workspace-pill"><span className="dot" />{t("localOnly")}</div><div className="eyebrow">{t("foundation")}</div><nav aria-label={t("tokens")}>{projection?.foundation.tokens.map(token => <button key={token.id} data-testid={`token-${token.id}`} aria-pressed={tokenId === token.id} className={`nav-item ${tokenId === token.id ? "active" : ""}`} onClick={() => { setTokenId(token.id); setComponentId(null); setSelectedPart(null); }}><span className="nav-icon">{colorHex(token.value) ? <i className="swatch" style={{ background: colorHex(token.value)! }} /> : <Icon name="token" size={13} />}</span>{token.name}</button>)}</nav><div className="eyebrow">{t("components")}</div><nav aria-label={t("components")}>{projection?.components.map(item => <button key={item.id} data-testid={`component-${item.id}`} aria-pressed={component?.id === item.id} className={`nav-item ${component?.id === item.id ? "active" : ""}`} onClick={() => selectComponent(item.id)}><Icon name="component" size={13} />{item.name}<span className="nav-count">{item.parts.length}</span></button>)}</nav>{component && <><div className="eyebrow">{t("layers")}</div><nav aria-label={t("layers")}>{component.parts.map(part => <button key={part.id} data-testid={`part-${part.id}`} aria-pressed={selectedPart === part.id} className={`nav-item nav-part ${selectedPart === part.id ? "active" : ""}`} onClick={() => selectComponent(component.id, part.id)}>{part.name}</button>)}</nav></>}<footer className="sidebar-footer"><div className="row"><span className="avatar" aria-hidden="true">A</span><span>Axiom Studio<br />{t("browserStorage")}</span></div></footer></aside>
    <header className="topbar"><div><div className="project-title">{state.project.name}</div><div className="project-meta"><span className="dot" /><span data-testid="save-status">{savedLabel}</span></div></div><div className="top-actions"><button className="icon-button" data-testid="undo" aria-label={t("undo")} title={`${t("undo")} · Ctrl/⌘ Z`} disabled={state.busy || dirty || Boolean(state.candidate) || !state.authoring.undoHandle} onClick={() => void controller.undo()}><Icon name="undo" /></button><button className="icon-button" data-testid="redo" aria-label={t("redo")} title={`${t("redo")} · Ctrl/⌘ ⇧ Z`} disabled={state.busy || dirty || Boolean(state.candidate) || !state.authoring.redoHandle} onClick={() => void controller.redo()}><Icon name="redo" /></button><button className="icon-button project-export" title={t("sourceBundle")} aria-label={t("sourceBundle")} data-testid="project-download" disabled={state.busy || dirty || Boolean(state.candidate)} onClick={() => void downloadProject()}><Icon name="code" /></button>{languageButton}<button className="button primary" data-testid="open-export" title={dirty ? t("noExportDirty") : t("exportSources")} disabled={state.busy || dirty || Boolean(state.candidate) || !projection?.valid} onClick={() => setExportOpen(true)}><Icon name="download" />{t("export")}</button></div></header>
    <main className="workarea" aria-label={t("canvas")}><div className="canvas-toolbar"><div className="breadcrumb"><Icon name="layers" size={13} />{t("workspace")}<Icon name="chevron" size={10} /><strong>{t("components")}</strong></div><div className="row"><div className="segmented" role="group" aria-label={t("preview")}><button data-testid="category-web" aria-pressed={category === "Web"} className={category === "Web" ? "active" : ""} onClick={() => setCategory("Web")}>{t("web")}</button><button data-testid="category-mobile" aria-pressed={category === "Mobile"} className={category === "Mobile" ? "active" : ""} onClick={() => setCategory("Mobile")}>{t("mobile")}</button></div><div className="segmented" role="group" aria-label={t("simulation")}><button data-testid="mode-edit" aria-pressed={mode === "edit"} className={mode === "edit" ? "active" : ""} onClick={() => setMode("edit")}>{t("editMode")}</button><button data-testid="mode-run" aria-pressed={mode === "run"} className={mode === "run" ? "active" : ""} onClick={() => setMode("run")}>{t("runMode")}</button></div></div></div><div className="stage"><ErrorPanel state={state} controller={controller} locale={locale} />{downloadError && <p className="error-panel" role="alert">{t("downloadFailed")}</p>}<div className="stage-heading"><div><span className="eyebrow">{category === "Web" ? "01" : "02"} / {t("preview")}</span><h1>{t("components")}</h1><p>{mode === "edit" ? t("previewHelp") : t("runHelp")}</p></div>{themes.length > 0 && <div><label className="sr-only" htmlFor="theme-select">{t("theme")}</label><select id="theme-select" data-testid="theme-select" className="theme-select" value={state.selection.themeSetId ?? String(themes[0]!.id)} onChange={event => controller.setSelection({ themeSetId: event.target.value })}>{themes.map(theme => <option key={String(theme.id)} value={String(theme.id)}>{typeof theme.name === "string" ? theme.name : String(theme.id).split(".").at(-1)}</option>)}</select></div>}</div><div className={`artboard ${category === "Mobile" ? "mobile" : ""}`}><div className="artboard-top" aria-hidden="true"><i className="window-dot" /><i className="window-dot" /><i className="window-dot" /><span>{category} · {dirty ? t("pendingPreview") : t("appliedPreview")}</span></div>{projection?.valid ? <Preview components={projection.components} category={category} mode={mode} selectedPart={selectedPart} onSelect={selectComponent} locale={locale} /> : <p className="empty-note">{t("unsupported")}</p>}</div><div className="stage-footnote"><span>{category === "Mobile" ? t("mobileApproximation") : t("simulation")}</span><span>{dirty ? t("pendingPreview") : t("appliedPreview")}</span></div></div>
      {(dirty || state.candidate || pending) && <div className="review-strip" data-testid="review-strip"><div><strong>{state.candidate || pending && !dirty ? t("reviewPending") : t("unsaved")}</strong><p>{state.plan ? `${t("changedDocuments")} · ${state.plan.updates.length}` : t("reviewDescription")}</p></div><div className="row"><button className="button subtle danger" data-testid="discard-changes" disabled={state.busy || state.retryable} onClick={() => { if (!state.candidate && pending && !dirty) controller.resume(pending); void controller.discard(); }}>{t("discard")}</button>{state.candidate || pending && !dirty ? <button className="button primary" data-testid="resume-review" disabled={state.busy} onClick={() => { if (!state.candidate && pending) controller.resume(pending); setReviewOpen(true); }}>{t("resumeReview")}</button> : <button className="button primary" data-testid="review-changes" disabled={!reviewAvailable} onClick={() => void controller.review()}>{t("review")}<Icon name="arrow" size={12} /></button>}</div></div>}
    </main>
    <Inspector state={state} controller={controller} tokenId={tokenId} component={component} selectedPart={selectedPart} category={category} locale={locale} />
    <footer className="statusbar" aria-label={t("status")}><span className={`status-message ${state.error ? "error" : ""}`} role="status" aria-live="polite" data-testid="status-message">{state.message ? t(state.message) : savedLabel}</span><span title={state.project.revision} data-testid="project-revision">{state.project.revision.slice(-8)}</span></footer>
    {reviewOpen && state.candidate && <ReviewDialog state={state} controller={controller} locale={locale} onClose={() => setReviewOpen(false)} />}
    {exportOpen && !dirty && !state.candidate && <ExportDialog project={state.project} selection={state.selection} services={services} locale={locale} onClose={() => setExportOpen(false)} />}
  </div>;
}
