import type { CSSProperties } from "react";
import { SidebarTokens } from "./sidebar-tokens.tsx";
import { SidebarResize, sidebarWidth, SIDEBAR_DEFAULT } from "./sidebar-resize.tsx";
import { StudioScrollAreas, StudioTooltips } from "./studio-overlays.tsx";
import type { TokenCreationContext } from "./token-atlas.tsx";
import { Select, SelectionPill } from "./ui.tsx";
import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import type { KernelServices, StudioCategory } from "../../../modules/ads-core/src/index.ts";
import type { StudioController, StudioState } from "./controller.ts";
import { Canvas } from "./canvas.tsx";
import { canvasFrames } from "./canvas-frames.ts";
import { BindingRepairDialog, ExportDialog, ReviewDialog } from "./dialogs.tsx";
import { FoundationInspector } from "./foundation-inspector.tsx";
import { FoundationPanel } from "./foundation-panel.tsx";
import { Icon } from "./icons.tsx";
import type { IconName } from "./icons.tsx";
import { Inspector } from "./inspector.tsx";
import { translate } from "./locales.ts";
import type { Locale, MessageKey } from "./locales.ts";
import { colorHex, downloadText, editingTarget, object } from "./ui-utils.ts";
import { Button, EmptyState, IconButton, copy } from "./ui.tsx";
import { CATALOG, CatalogInspector, LibraryPanel, SystemPanel, WorkbenchDialog } from "./workbench-panels.tsx";
import { StarterOptions, DEFAULT_STARTER } from "./foundation-starter-panel.tsx";
import { FormDraftProvider, useDraftRegistry } from "./form-drafts.tsx";

type View = "canvas" | "foundation" | "library" | "system";
function preference(key: string, fallback: string): string { try { return localStorage.getItem(key) ?? fallback; } catch { return fallback; } }
function Wordmark() { return <div className="wordmark"><span className="logo-mark" aria-hidden="true">A</span>axiom <small>Studio</small></div>; }
function ErrorPanel({ state, controller, locale }: { state: StudioState; controller: StudioController; locale: Locale }) {
  if (!state.error) return null;
  const t = (key: MessageKey) => translate(locale, key);
  return <div className="error-panel" role="alert" data-testid="operation-error">{t(state.message ?? "unknownError")}<details><summary>{t("details")}</summary><code>{state.error}</code></details>{state.retryable ? <Button data-testid="retry-operation" disabled={state.busy} onClick={() => void controller.retry()}>{t("retrySave")}</Button> : state.error === "REVISION_CONFLICT" && <Button disabled={state.busy} onClick={() => void controller.rebase()}>{t("compareCurrent")}</Button>}</div>;
}

export function App({ controller, services }: { controller: StudioController; services: KernelServices }) {
  return <FormDraftProvider><Workspace controller={controller} services={services} /><StudioScrollAreas /><StudioTooltips /></FormDraftProvider>;
}
function Workspace({ controller, services }: { controller: StudioController; services: KernelServices }) {
  const drafts = useDraftRegistry(), pendingForms = useSyncExternalStore(drafts.subscribe, drafts.getSnapshot);
  const state = useSyncExternalStore(controller.subscribe, controller.getSnapshot);
  const [creationContext, setCreationContext] = useState<TokenCreationContext>({});
  const [starter, setStarter] = useState(DEFAULT_STARTER), [starterEnabled, setStarterEnabled] = useState(true);
  const [locale, setLocale] = useState<Locale>(() => preference("axiom.ui.locale", "ko") === "en" ? "en" : "ko");
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() => preference("axiom.ui.sidebarCollapsed", "false") === "true");
  const [navigationWidth, setNavigationWidth] = useState(() => sidebarWidth(Number(preference("axiom.ui.sidebarWidth", String(SIDEBAR_DEFAULT)))));
  const [inspectorCollapsed, setInspectorCollapsed] = useState(() => preference("axiom.ui.inspectorCollapsed", "false") === "true");
  const [theme, setTheme] = useState(() => preference("axiom.ui.theme", "dark"));
  const [view, setView] = useState<View>("canvas"), [name, setName] = useState(""), [search, setSearch] = useState("");
  const [tokenId, setTokenId] = useState<string | null>(null), [selectedIds, setSelectedIds] = useState<string[]>([]), [selectedPart, setSelectedPart] = useState<string | null>(null);
  const [catalogId, setCatalogId] = useState("catalog.button"), [creatingToken, setCreatingToken] = useState(false);
  const [category, setCategory] = useState<StudioCategory>("Web"), [mode, setMode] = useState<"edit" | "run">("edit");
  const [reviewOpen, setReviewOpen] = useState(false), [exportOpen, setExportOpen] = useState(false), [helpOpen, setHelpOpen] = useState(false), [commandOpen, setCommandOpen] = useState(false);
  const [bindingRepairOpen, setBindingRepairOpen] = useState(false);
  const [commandQuery, setCommandQuery] = useState(""), [downloadError, setDownloadError] = useState(false);
  const [inspectorDirty, setLocalDirty] = useState(false), [navigationMessage, setNavigationMessage] = useState(false), [mobilePanel, setMobilePanel] = useState("canvas");
  const [panelDirty, setPanelDirty] = useState(false); const localDirty = inspectorDirty || panelDirty || pendingForms.length > 0;
  const dirtyRef = useRef(localDirty); dirtyRef.current = localDirty;
  const t = (key: MessageKey) => translate(locale, key), c = (ko: string, en: string) => copy(locale, ko, en);
  const projection = state.projection, component = projection?.components.find(item => item.id === selectedIds[0]) ?? null;
  useEffect(() => {
    if (!projection) return;
    setSelectedIds(before => { const next = before.filter(id => projection.components.some(item => item.id === id)); return next.length === before.length ? before : next; });
    if (selectedPart && !projection.components.some(item => item.parts.some(part => part.id === selectedPart))) setSelectedPart(null);
  }, [projection, selectedPart]);
  useEffect(() => { void controller.connect(); }, [controller]);
  useEffect(() => { document.documentElement.lang = locale; document.documentElement.dataset.theme = theme; try { localStorage.setItem("axiom.ui.locale", locale); localStorage.setItem("axiom.ui.theme", theme); } catch { /* Preferences do not affect project storage. */ } }, [locale, theme]);
  useEffect(() => setReviewOpen(Boolean(state.candidate)), [state.candidate?.id]);
  useEffect(() => {
    const keyboard = (event: KeyboardEvent) => {
      if (event.isComposing || document.querySelector("dialog[open]")) return;
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandQuery(""); setCommandOpen(true); return; }
      if (!editingTarget(event.target) && !dirtyRef.current && (event.ctrlKey || event.metaKey) && !event.altKey && event.key.toLowerCase() === "z") { event.preventDefault(); void (event.shiftKey ? controller.redo() : controller.undo()); }
      if (!editingTarget(event.target) && event.key === "?") { event.preventDefault(); setHelpOpen(true); }
    };
    const leaving = (event: BeforeUnloadEvent) => { if (controller.dirty || dirtyRef.current) { event.preventDefault(); event.returnValue = ""; } };
    const refresh = () => { if (document.visibilityState === "visible" && !dirtyRef.current) void controller.refresh(); };
    window.addEventListener("keydown", keyboard); window.addEventListener("beforeunload", leaving); window.addEventListener("focus", refresh);
    return () => { window.removeEventListener("keydown", keyboard); window.removeEventListener("beforeunload", leaving); window.removeEventListener("focus", refresh); };
  }, [controller]);
  useEffect(() => { try { localStorage.setItem("axiom.ui.sidebarCollapsed", String(sidebarCollapsed)); localStorage.setItem("axiom.ui.inspectorCollapsed", String(inspectorCollapsed)); } catch { /* Layout preferences never affect project storage. */ } }, [sidebarCollapsed, inspectorCollapsed]);
  useEffect(() => { try { localStorage.setItem("axiom.ui.sidebarWidth", String(navigationWidth)); } catch { /* Layout only. */ } }, [navigationWidth]);
  const showInspector = () => { setInspectorCollapsed(false); setMobilePanel("inspector"); };
  const navigate = (action: () => void) => { if (localDirty && !drafts.flush()) { setNavigationMessage(true); return; } setNavigationMessage(false); action(); };
  const selectComponent = (id: string, partId?: string, designCategory?: StudioCategory) => navigate(() => {
    if (designCategory) setCategory(designCategory); setView("canvas"); setTokenId(null); setSelectedIds([id]); setSelectedPart(partId ?? projection?.components.find(item => item.id === id)?.parts.find(part => part.role === "root")?.id ?? null); showInspector();
  });
  const selectToken = (id: string) => navigate(() => { setView("foundation"); setTokenId(id); setCreatingToken(false); showInspector(); });
  const addComponent = (id: string, name?: string) => navigate(() => {
    const before = new Set(projection?.components.map(item => item.id)); controller.createComponent(id, name);
    const added = controller.getSnapshot().projection?.components.find(item => !before.has(item.id));
    if (added) { setView("canvas"); setSelectedIds([added.id]); setSelectedPart(added.parts.find(part => part.role === "root")?.id ?? null); setMobilePanel("canvas"); }
  });
  const duplicate = () => { if (localDirty) return; for (const id of selectedIds) controller.duplicateComponent(id); };
  const remove = () => { if (localDirty) return; for (const id of selectedIds) { controller.deleteComponent(id); if (controller.getSnapshot().error) return; } setSelectedIds([]); setSelectedPart(null); };
  const languageButton = <button className="locale-button" data-testid="locale-toggle" aria-label={t("language")} onClick={() => setLocale(locale === "ko" ? "en" : "ko")}>{locale === "ko" ? "EN" : "KO"}</button>;
  const themeButton = <IconButton icon={theme === "light" ? "moon" : "sun"} data-testid="studio-theme-toggle" label={theme === "light" ? c("어두운 테마", "Use dark theme") : c("밝은 테마", "Use light theme")} onClick={() => setTheme(theme === "light" ? "dark" : "light")} />;
  if (state.loading) return <div className="loading-screen" role="status"><Wordmark /><p>{t("loading")}</p></div>;
  if (!state.project || !Object.keys(state.project.documents).length) return <main className="onboarding" data-testid="onboarding"><section className="welcome-left"><Wordmark /><div><h1>{c("디자인의 기준을,\n하나의 시스템으로.", "One foundation.\nA system of your own.")}</h1><p>{c("토큰부터 컴포넌트까지. 직접 설계하고, 작동을 확인하고, 제품에 사용할 코드를 만드세요.", "Design tokens and components, test how they behave, and generate code for your product.")}</p></div><div className="welcome-specimen"><span className="badge">Foundation</span><div className="welcome-swatches">{["#171717", "#355a26", "#8dfc52", "#c6f9ad", "#eff9e9"].map(color => <i key={color} style={{ background: color }} />)}</div><strong>Aa</strong><small>Geist Variable · 100—900</small></div></section><section className="welcome-form"><div className="row">{themeButton}{languageButton}</div><h2>{c("새 디자인 시스템", "Create a design system")}</h2><p>{c("기본 스케일과 의미 토큰을 함께 준비합니다. 브랜드와 밀도를 선택하면 나머지는 시작한 뒤 조정할 수 있습니다.", "Start with primitive scales and semantic tokens. Choose your brand and density; refine the details in the editor.")}</p><ErrorPanel state={state} controller={controller} locale={locale} /><form onSubmit={event => { event.preventDefault(); void controller.createProject(name || c("나의 디자인 시스템", "My design system"), starterEnabled && starter.domains.length ? starter : undefined); }}><div className="field"><label htmlFor="project-name">{t("projectName")}</label><input id="project-name" data-testid="project-name" maxLength={120} value={name} disabled={state.busy || Boolean(state.project)} placeholder={t("projectPlaceholder")} onChange={event => setName(event.target.value)} /></div><label className="check-row"><input type="checkbox" data-testid="starter-enabled" checked={starterEnabled} onChange={event => setStarterEnabled(event.target.checked)} />{c("기본 토큰 템플릿 포함", "Include foundation starter")}</label>{starterEnabled && <StarterOptions compact locale={locale} value={starter} onChange={setStarter} />}<div className="storage-choice"><strong><span className="dot" />{t("browserStorage")}</strong><p>{t("browserStorageHelp")}</p></div><Button tone="primary" icon="arrow" style={{ width: "100%" }} data-testid="start-project" disabled={state.busy || state.retryable} type="submit">{state.busy ? t("saving") : t("create")}</Button></form><p className="help">{t("folderPending")}</p></section></main>;
  const working = state.plan?.project ?? state.project, foundation = projection?.foundation.foundationId ? working.documents[projection.foundation.foundationId]?.document : undefined;
  const themes = Array.isArray(foundation?.themeSets) ? foundation.themeSets.filter(object).filter(item => typeof item.id === "string") : [];
  const dirty = controller.dirty || localDirty, locked = state.busy || state.retryable || Boolean(state.candidate);
  const bindingErrors = projection?.diagnostics.filter(item => item.severity === "error") ?? [];
  const canRepairBindings = bindingErrors.length > 0 && bindingErrors.every(item => item.code === "STUDIO_TOKEN_BINDING");
  const savedLabel = state.busy ? t("saving") : state.error ? t("failedSave") : state.candidate ? t("reviewing") : dirty ? t("unsaved") : t("saved");
  const pending = state.authoring.pendingCandidates.find(item => item.baseRevision === state.project!.revision) ?? state.authoring.pendingCandidates.at(-1);
  const changeCount = state.plan?.changes ? state.plan.changes.upserts.length + state.plan.changes.deletes.length : state.plan?.updates.length ?? 0;
  const reviewAvailable = (changeCount > 0 || localDirty) && !state.pendingBuffers.length && !locked;
  const frames = canvasFrames(projection?.components ?? [], category);
  const downloadProject = async () => { setDownloadError(false); try { const bundle = await controller.exportProject(); if (!bundle) throw new Error("No project source"); downloadText("axiom-project.json", JSON.stringify(bundle, null, 2)); } catch { setDownloadError(true); } };
  const views: { id: View; label: string; icon: IconName }[] = [{ id: "canvas", label: c("컴포넌트", "Components"), icon: "layers" }, { id: "foundation", label: c("파운데이션", "Foundation"), icon: "token" }, { id: "library", label: c("라이브러리", "Library"), icon: "library" }];
  const actions = [{ id: "system", name: "Axiom UI", icon: "palette" as const, run: () => navigate(() => { setView("system"); setMobilePanel("canvas"); }) }, ...views.map(item => ({ id: item.id, name: item.label, icon: item.icon, run: () => navigate(() => { setView(item.id); setMobilePanel("canvas"); }) })), { id: "new-token", name: c("새 토큰 만들기", "Create a token"), icon: "plus" as const, run: () => navigate(() => { setView("foundation"); setCreationContext({}); setCreatingToken(true); showInspector(); }) }, ...(projection?.components ?? []).map(item => ({ id: item.id, name: item.name, icon: "component" as const, run: () => selectComponent(item.id) })), ...(projection?.foundation.tokens ?? []).map(item => ({ id: item.id, name: item.name, icon: "token" as const, run: () => selectToken(item.id) }))].filter(item => item.name.toLowerCase().includes(commandQuery.toLowerCase())).slice(0, 40);
  return <div className="app" data-testid="studio-app" data-mobile-panel={mobilePanel} data-sidebar-collapsed={sidebarCollapsed} data-inspector-collapsed={inspectorCollapsed} style={{ "--sidebar-user-width": `${navigationWidth}px` } as CSSProperties}>
    <header className="topbar"><div className="topbar-left"><IconButton icon="panel-left" className="panel-toggle" data-testid="toggle-sidebar" aria-controls="studio-sidebar" aria-expanded={!sidebarCollapsed} label={sidebarCollapsed ? c("탐색 패널 펼치기", "Show navigation panel") : c("탐색 패널 접기", "Hide navigation panel")} onClick={() => setSidebarCollapsed(value => !value)} /><Wordmark /><span className="toolbar-divider" /><span className="project-title">{state.project.name}</span></div><div className="top-actions"><span className="save-label" data-testid="save-status"><span className={`dot ${dirty ? "pending" : ""}`} />{savedLabel}</span><IconButton icon="undo" data-testid="undo" label={`${t("undo")} · Ctrl/⌘ Z`} disabled={!controller.canUndo || localDirty} onClick={() => void controller.undo()} /><IconButton icon="redo" data-testid="redo" label={`${t("redo")} · Ctrl/⌘ ⇧ Z`} disabled={!controller.canRedo || localDirty} onClick={() => void controller.redo()} /><span className="toolbar-divider" /><IconButton icon="search" label={c("빠른 검색 · Ctrl/⌘ K", "Quick search · Ctrl/⌘ K")} onClick={() => { setCommandQuery(""); setCommandOpen(true); }} />{themeButton}{languageButton}<IconButton icon="panel" className="panel-toggle" data-testid="toggle-inspector" aria-controls="studio-inspector" aria-expanded={!inspectorCollapsed} label={inspectorCollapsed ? c("속성 패널 펼치기", "Show inspector panel") : c("속성 패널 접기", "Hide inspector panel")} onClick={() => setInspectorCollapsed(value => !value)} /><IconButton icon="help" label={c("단축키와 도움말", "Shortcuts and help")} onClick={() => setHelpOpen(true)} /><IconButton icon="code" className="project-export" data-testid="project-download" label={t("sourceBundle")} disabled={locked || dirty} onClick={() => void downloadProject()} /><Button tone="primary" icon="download" data-testid="open-export" disabled={locked || dirty || !projection?.valid} onClick={() => setExportOpen(true)}>{t("export")}</Button></div></header>
    <nav className="mobile-panel-tabs" aria-label={c("작업 패널", "Workspace panels")}>{[["library", c("탐색", "Browse")], ["canvas", c("작업 영역", "Workspace")], ["inspector", c("속성", "Inspect")]].map(([id, label]) => <button key={id} aria-pressed={mobilePanel === id} onClick={() => setMobilePanel(id!)}>{label}</button>)}</nav>
    <aside id="studio-sidebar" className="sidebar" aria-label={t("workspace")}><nav className="workspace-nav" aria-label={c("작업 영역", "Workspace")}><SelectionPill value={view} />{views.map(item => <button key={item.id} className={`nav-item ${view === item.id ? "active" : ""}`} aria-pressed={view === item.id} data-testid={`view-${item.id}`} onClick={() => navigate(() => { setView(item.id); setMobilePanel("canvas"); })}><Icon name={item.icon} size={15} />{item.label}<span className="nav-count">{item.id === "canvas" ? projection?.components.length : item.id === "foundation" ? projection?.foundation.tokens.length : 239}</span></button>)}</nav><div className="sidebar-search"><Icon name="search" size={14} /><input aria-label={c("프로젝트 검색", "Search project")} placeholder={c("이름으로 검색…", "Search by name…")} value={search} onChange={event => setSearch(event.target.value)} /></div><div className="sidebar-scroll"><div className="sidebar-section-header"><span>{t("components")}</span><IconButton icon="plus" label={c("컴포넌트 추가", "Add component")} onClick={() => navigate(() => { setView("library"); setMobilePanel("canvas"); })} /></div>{projection?.components.filter(item => item.name.toLowerCase().includes(search.toLowerCase())).map(item => <div key={item.id}><button data-testid={`component-${item.id}`} aria-pressed={selectedIds.includes(item.id) && view === "canvas"} className={`nav-item ${selectedIds.includes(item.id) && view === "canvas" ? "active" : ""}`} onClick={() => selectComponent(item.id)}><Icon name="component" size={14} /><span className="nav-name">{item.name}</span><span className="nav-count">{item.parts.length}</span></button>{selectedIds.includes(item.id) && view === "canvas" && item.parts.map(part => <button key={part.id} data-testid={`part-${part.id}`} aria-pressed={selectedPart === part.id} className={`nav-item nav-part ${selectedPart === part.id ? "active" : ""}`} style={{ paddingLeft: part.parent ? 36 : 24 }} onClick={() => selectComponent(item.id, part.id)}><Icon name="layers" size={11} /><span className="nav-name">{part.name}</span></button>)}</div>)}<div className="sidebar-section-header"><span>{t("tokens")}</span><IconButton icon="plus" label={c("토큰 만들기", "Create token")} data-testid="new-token" onClick={() => navigate(() => { setView("foundation"); setCreationContext({}); setCreatingToken(true); showInspector(); })} /></div>{projection && <SidebarTokens tokens={projection.foundation.tokens} foundation={foundation} query={search} selected={view === "foundation" ? tokenId : null} locale={locale} onSelect={selectToken} />}</div><SidebarResize width={navigationWidth} onChange={setNavigationWidth} locale={locale} /></aside>
    <main className="workarea" aria-label={t("canvas")}>
      {view === "canvas" && <div className="canvas-toolbar"><div className="breadcrumb"><Icon name="layers" size={14} /><strong>{c("컴포넌트", "Components")}</strong></div><div className="row"><div className="segmented" role="group" aria-label={c("미리보기 대상", "Preview target")}>{(["Web", "Mobile"] as const).map(value => <button key={value} data-testid={`category-${value.toLowerCase()}`} aria-pressed={category === value} className={category === value ? "active" : ""} aria-label={value} data-tooltip={value === "Web" ? c("웹 디자인 미리보기", "Preview Web design") : c("모바일 디자인 미리보기", "Preview Mobile design")} onClick={() => navigate(() => setCategory(value))}><Icon name={value === "Web" ? "monitor" : "phone"} /></button>)}</div><div className="segmented canvas-mode-switch" role="group" aria-label={t("simulation")}>{(["edit", "run"] as const).map(value => <button key={value} data-testid={`mode-${value}`} aria-pressed={mode === value} className={mode === value ? "active" : ""} aria-label={value === "edit" ? t("editMode") : t("runMode")} data-tooltip={value === "edit" ? c("디자인 편집 · 파트 선택, 이동, 크기 조절", "Design · Select parts, move and resize") : c("동작 체험 · 클릭과 입력을 시험합니다. 프로젝트는 변경되지 않습니다.", "Interact · Try clicks and input without changing the project")} onClick={() => setMode(value)}><Icon name={value === "edit" ? "edit" : "play"} /><span className="mode-label">{value === "edit" ? c("디자인", "Design") : c("동작", "Interact")}</span></button>)}</div>{themes.length > 0 && <Select iconOnly triggerIcon={String(themes.find(item => item.id === (state.selection.themeSetId ?? themes[0]?.id))?.name ?? "").toLowerCase().includes("dark") ? "moon" : "sun"} data-testid="theme-select" className="theme-select" aria-label={t("theme")} value={state.selection.themeSetId ?? String(themes[0]!.id)} onChange={event => navigate(() => controller.setSelection({ themeSetId: event.target.value }))}>{themes.map(item => <option key={String(item.id)} value={String(item.id)}>{String(item.name ?? item.id).split(".").at(-1)}</option>)}</Select>}</div></div>}
      <ErrorPanel state={state} controller={controller} locale={locale} />
      {canRepairBindings && <div className="input-notice" role="status"><strong>{c("용도에 맞지 않는 토큰 연결이 있습니다.", "Some token bindings use an incompatible purpose.")}</strong><p>{localDirty || state.pendingBuffers.length ? c("미반영 입력을 완료하거나 초기화한 뒤 연결을 함께 복구하세요.", "Finish or reset pending input before repairing the bindings together.") : c("여러 컴포넌트의 연결을 한 번에 복구할 수 있습니다.", "Repair bindings across components in one proposal.")}</p><Button data-testid="open-binding-repair" disabled={locked || localDirty || state.pendingBuffers.length > 0} onClick={() => setBindingRepairOpen(true)}>{c("토큰 연결 복구", "Repair token bindings")}</Button></div>}
      {navigationMessage && localDirty && <div className="input-notice" role="alert"><strong>{c("아직 반영하지 못한 입력이 있습니다.", "Some input needs your attention.")}</strong><p>{c("수정 중인 값은 보존되어 있습니다. 해당 폼에서 수정하거나 입력만 되돌릴 수 있습니다.", "Your input is preserved. Correct the form or reset only its uncommitted input.")}</p>{pendingForms.map(form => <div className="row" key={form.id}><Button onClick={() => { if (form.id.startsWith("foundation-manager")) setMobilePanel("canvas"); else showInspector(); requestAnimationFrame(() => form.focus()); }}>{form.label}</Button><Button data-testid="reset-pending-input" onClick={() => { form.reset(); setNavigationMessage(false); }}>{c("입력 초기화", "Reset input")}</Button></div>)}</div>}
      {downloadError && <p className="error-panel" role="alert">{t("downloadFailed")}</p>}
      {view === "canvas" ? projection?.valid ? <Canvas previewForeground={colorHex(projection.foundation.tokens.find(token => token.id === "token.content")?.value) ?? undefined} previewBackground={colorHex(projection.foundation.tokens.find(token => token.id === "token.surface")?.value) ?? undefined} components={projection.components} category={category} mode={mode} locale={locale} selectedIds={selectedIds} selectedPart={selectedPart} frames={frames} disabled={locked || localDirty} onSelect={(ids, partId) => navigate(() => { if (ids.length) setInspectorCollapsed(false); setSelectedIds(ids); setSelectedPart(partId ?? projection.components.find(item => item.id === ids[0])?.parts.find(part => part.role === "root")?.id ?? null); })} onFrames={next => controller.component(Object.entries(next).map(([componentId, frame]) => ({ componentId, edit: { kind: "frame", category, frame } })))} onDuplicate={duplicate} onDelete={remove} /> : <EmptyState title={t("unsupported")} description={c("진단을 확인하고 원본을 보존한 상태에서 수정하세요.", "Inspect diagnostics and repair the source without discarding it.")} /> : view === "foundation" ? <FoundationPanel onSelectComponent={selectComponent} externalDirty={inspectorDirty} onDirtyChange={setPanelDirty} state={state} controller={controller} locale={locale} tokenId={tokenId} onSelect={selectToken} onCreate={context => navigate(() => { setCreationContext(context ?? {}); setCreatingToken(true); showInspector(); })} /> : view === "library" ? <LibraryPanel locale={locale} selected={catalogId} onSelect={id => { setCatalogId(id); showInspector(); }} onAdd={addComponent} disabled={locked} /> : <SystemPanel locale={locale} />}
      {(dirty || state.candidate || pending) && <div className="review-strip" data-testid="review-strip"><div><strong>{state.candidate || pending && !dirty ? t("reviewPending") : t("unsaved")}</strong><p>{localDirty ? c("검토할 때 정상 입력을 함께 반영합니다.", "Valid form input joins the review.") : state.plan ? `${t("changedDocuments")} · ${changeCount}` : t("reviewDescription")}</p></div><div className="row"><Button tone="subtle" data-testid="discard-changes" disabled={state.busy || state.retryable} onClick={() => { drafts.resetAll(); if (!state.candidate && pending && !dirty) controller.resume(pending); void controller.discard(); }}>{t("discard")}</Button>{state.candidate || pending && !dirty ? <Button tone="primary" data-testid="resume-review" disabled={state.busy} onClick={() => { if (!state.candidate && pending) controller.resume(pending); setReviewOpen(true); }}>{t("resumeReview")}</Button> : <Button tone="primary" icon="arrow" data-testid="review-changes" disabled={!reviewAvailable} onClick={() => { if (drafts.flush()) { setNavigationMessage(false); void controller.review(); } else setNavigationMessage(true); }}>{t("review")}</Button>}</div></div>}
    </main>
    <div id="studio-inspector" className="inspector-host">{view === "foundation" ? <aside className="inspector" aria-label={t("inspector")}><FoundationInspector creationContext={creationContext} externalDirty={panelDirty} state={state} controller={controller} locale={locale} tokenId={tokenId} creating={creatingToken} onCreated={id => { setLocalDirty(false); setTokenId(id); setCreatingToken(false); }} onCancel={() => { setLocalDirty(false); setCreatingToken(false); }} onSelectComponent={selectComponent} onDirtyChange={setLocalDirty} /></aside> : view === "library" ? <CatalogInspector entry={CATALOG.find(item => item.id === catalogId)} locale={locale} onAdd={addComponent} disabled={locked} /> : view === "canvas" ? <div className="inspector-container">{selectedIds.length > 0 && <div className="selection-actions"><span>{selectedIds.length} {c("개 선택", "selected")}</span><IconButton icon="copy" label={c("선택 복제", "Duplicate selection")} disabled={locked || localDirty} onClick={duplicate} /><IconButton icon="trash" label={c("선택 삭제", "Delete selection")} disabled={locked || localDirty} onClick={remove} /></div>}<Inspector onDirtyChange={setLocalDirty} onSelectToken={selectToken} onSelectPart={id => { if (component) selectComponent(component.id, id); }} state={state} controller={controller} tokenId={null} component={component} selectedPart={selectedPart} category={category} locale={locale} /></div> : <aside className="inspector"><EmptyState icon="palette" title="Axiom UI" description={c("공통 토큰과 컨트롤이 파운데이션, 캔버스, 속성 패널에 함께 적용됩니다.", "Shared tokens and controls power Foundation, canvas and inspector.")} /></aside>}</div>
    <footer className="statusbar" aria-label={t("status")}><span className={`status-message ${state.error ? "error" : ""}`} role="status" aria-live="polite" data-testid="status-message">{state.message ? t(state.message) : savedLabel}</span><span>{category === "Mobile" && view === "canvas" ? t("mobileApproximation") : t("browserStorage")}</span><span title={state.project.revision} data-testid="project-revision">{state.project.revision.slice(-8)}</span></footer>
    {bindingRepairOpen && <BindingRepairDialog state={state} controller={controller} locale={locale} onClose={() => setBindingRepairOpen(false)} />}
    {reviewOpen && state.candidate && <ReviewDialog state={state} controller={controller} locale={locale} onClose={() => setReviewOpen(false)} />}
    {exportOpen && !dirty && !state.candidate && <ExportDialog project={state.project} selection={state.selection} services={services} locale={locale} onClose={() => setExportOpen(false)} />}
    {helpOpen && <WorkbenchDialog title={c("키보드 단축키", "Keyboard shortcuts")} onClose={() => setHelpOpen(false)}><div className="shortcut-list">{[[c("빠른 검색", "Quick search"), "Ctrl / ⌘ K"], [t("undo"), "Ctrl / ⌘ Z"], [t("redo"), "Ctrl / ⌘ Shift Z"], [c("선택 / 이동 도구", "Select / pan tool"), "V / H"], [c("캔버스 이동", "Pan canvas"), "Space + drag"], [c("확대 / 축소 / 100%", "Zoom in / out / 100%"), "+ / − / 0"], [c("전체 / 선택 보기", "Fit all / selection"), "Shift 1 / 2"], [c("모두 선택 / 복제", "Select all / duplicate"), "Ctrl / ⌘ A / D"], [c("이동 / 빠른 이동", "Move / move faster"), "↑↓←→ / Shift"], [c("격자 스냅 무시", "Bypass snap"), "Alt + drag"]].map(([label, keys]) => <div className="property-row" key={keys}><span>{label}</span><kbd>{keys}</kbd></div>)}<p className="help">{c("프로젝트는 이 브라우저에 저장됩니다. 소스 번들을 내려받아 별도로 보관하세요. 모바일 미리보기는 네이티브 실행 증거가 아닙니다.", "Projects are stored in this browser. Download a source bundle for a separate backup. Mobile preview does not establish native execution.")}</p></div></WorkbenchDialog>}
    {commandOpen && <WorkbenchDialog title={c("빠른 검색", "Quick search")} onClose={() => setCommandOpen(false)}><div className="command-search"><input autoFocus aria-label={c("명령 또는 항목 검색", "Search commands or objects")} value={commandQuery} onChange={event => setCommandQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && actions[0]) { actions[0].run(); setCommandOpen(false); } }} placeholder={c("명령, 컴포넌트, 토큰 검색…", "Search commands, components, tokens…")} /></div><div className="command-results">{actions.map(action => <button key={action.id} className="command-result" onClick={() => { action.run(); setCommandOpen(false); }}><Icon name={action.icon} size={15} /><span>{action.name}</span><Icon name="arrow" size={12} /></button>)}{!actions.length && <p className="nav-empty">{c("검색 결과가 없습니다.", "No results found.")}</p>}</div></WorkbenchDialog>}
  </div>;
}
