import { useEffect, useRef, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import type { JsonValue, StudioCategory, StudioComponent } from "../../../modules/ads-core/src/index.ts";
import type { Locale } from "./locales.ts";
import { object } from "./ui-utils.ts";
import { copy } from "./ui.tsx";
import { getStudioCatalogEntry, studioCatalogPresentation } from "../../../modules/ads-core/src/index.ts";
import { CatalogStructurePreview } from "./catalog-structure-preview.tsx";

interface Props { component: StudioComponent; category: StudioCategory; mode: "edit" | "run"; selectedPart: string | null; onSelect(componentId: string, partId: string): void; locale: Locale }
/** Isolated consumer simulation; interaction never writes the authored defaults. */
export function CatalogPreview({ component, category, mode, selectedPart, onSelect, locale }: Props) {
  const catalog = component.catalog!, kind = catalog.semantic.kind;
  const presentation = studioCatalogPresentation(getStudioCatalogEntry(catalog.catalogId)!, kind), shape = presentation.shape;
  const defaults = Object.fromEntries(catalog.values.map(value => [String(value.name), value.defaultValue ?? null]));
  const signature = JSON.stringify(defaults), [values, setValues] = useState<Record<string, JsonValue>>(defaults), [requests, setRequests] = useState(0), [lastRequest, setLastRequest] = useState("");
  const [numberDraft, setNumberDraft] = useState(String(defaults.draft ?? defaults.value ?? "")), [numberInvalid, setNumberInvalid] = useState(false);
  const [imageFailed, setImageFailed] = useState(false), [hover, setHover] = useState(false);
  const checkbox = useRef<HTMLInputElement>(null), dialog = useRef<HTMLDialogElement>(null), trigger = useRef<HTMLButtonElement>(null);
  const t = (ko: string, en: string) => copy(locale, ko, en), run = mode === "run", disabled = Boolean(values.disabled);
  const read = (name: string, fallback = "") => typeof values[name] === "string" ? String(values[name]) : fallback;
  const number = (name: string, fallback: number) => typeof values[name] === "number" ? values[name] as number : fallback;
  const request = (name: string, value: JsonValue) => { if (!run || disabled) return; setValues(before => ({ ...before, [name]: value })); setRequests(before => before + 1); setLastRequest(`${name}ChangeRequest`); };
  const activate = (name = "activate") => { if (run && !disabled) { setRequests(before => before + 1); setLastRequest(name); } };
  useEffect(() => { setValues(defaults); setRequests(0); setLastRequest(""); setNumberDraft(String(defaults.draft ?? defaults.value ?? "")); setNumberInvalid(false); }, [component.id, signature, mode]);
  useEffect(() => { if (checkbox.current) checkbox.current.indeterminate = Boolean(values.indeterminate); }, [values.indeterminate]);
  useEffect(() => { setImageFailed(false); }, [values.src]);
  useEffect(() => { const element = dialog.current; if (!element) return; if (run && values.open && !element.open) { if (catalog.semantic.modal) element.showModal(); else element.show(); } else if ((!run || !values.open) && element.open) element.close(); }, [run, values.open, catalog.semantic.modal]);
  const design = category === "Web" ? component.web : component.mobile, rootPart = component.parts.find(part => part.role === "root");
  const props = (role: string) => {
    const part = component.parts.find(item => item.role === role), layout = part ? design.layout[part.id] : undefined, presentation = part ? design.parts[part.id] : undefined;
    const appearance = presentation?.combinations[`${component.defaults.variant}${disabled ? "-disabled" : ""}`] ?? presentation?.base ?? {};
    const style: CSSProperties = { ...appearance, borderStyle: appearance.borderStyle ?? (appearance.borderWidth ? "solid" : undefined), ...(layout ? { padding: layout.padding, gap: layout.gap, minHeight: layout.minHeight, ...(layout.width?.mode === "fixed" ? { width: layout.width.value } : layout.width?.mode === "fill" ? { width: "100%" } : {}), ...(layout.height?.mode === "fixed" ? { height: layout.height.value } : {}), alignItems: layout.alignment === "start" ? "flex-start" : layout.alignment === "end" ? "flex-end" : layout.alignment } : {}) };
    if (layout && (["root", "body", "actions", "panel", "list"].includes(role) || component.parts.some(item => item.parent === part?.id)) && !["table", "separator"].includes(kind)) {
      style.display = "flex"; style.flexDirection = layout.axis === "horizontal" ? "row" : "column";
    }
    if (part?.parent) { const parent = design.layout[part.parent]; if (parent) style.order = parent.childOrder.indexOf(part.id); }
    return { "data-preview-role": role, "data-part-id": part?.id, "data-testid": `preview-part-${part?.id}`, className: `selectable-part ${selectedPart === part?.id ? "selected-part" : ""}`, style };
  };
  const valueName = catalog.semantic.valueName ?? "value", items = Array.isArray(values.items) ? values.items.filter(object) : [];
  const label = String(component.parts.find(part => part.role === "label")?.text ?? (catalog.accessibility.label || component.sampleContent.label || component.name)), description = String(catalog.accessibility.description || "");
  const id = `simulation-${component.id}`, editable = { disabled, tabIndex: run ? 0 : -1 };
  const selected = values.selectedKeys ?? values.selectedKey, selectedKeys = Array.isArray(selected) ? selected.map(String) : [String(selected ?? "")];
  const choose = (key: string) => request(valueName, catalog.semantic.selection === "multiple" ? selectedKeys.includes(key) ? selectedKeys.filter(item => item !== key) : [...selectedKeys, key] : key);
  const fieldLabel = <label {...props("label")} htmlFor={`${id}-input`}>{label}</label>;
  const body = component.parts.find(part => part.role === "body")?.text ?? component.sampleContent.body, content = <div {...props("body")}>{body}</div>;
  let node: ReactNode;
  switch (kind) {
    case "button": node = <button {...props("root")} {...editable} onClick={() => activate()}><span {...props("label")}>{shape === "icon-button" ? <span aria-label={label}>＋</span> : shape === "close-button" ? <span aria-label={label}>×</span> : label}</span></button>; break;
    case "surface": node = <article {...props("root")}>{shape === "empty" && <span className="catalog-empty-icon" aria-hidden="true">□</span>}{shape !== "paper" && <h3 {...props("header")}>{component.sampleContent.title}</h3>}{content}{shape !== "paper" && <div {...props("actions")}><button {...editable} onClick={() => activate()}>{component.sampleContent.actionLabel}</button></div>}</article>; break;
    case "text-input": case "textarea": node = <div {...props("root")}>{fieldLabel}{kind === "textarea" ? <textarea {...props("input")} {...editable} id={`${id}-input`} value={read("value")} placeholder={read("placeholder")} readOnly={!run || Boolean(values.readOnly)} aria-invalid={Boolean(values.invalid)} aria-describedby={description ? `${id}-description` : undefined} onChange={event => request("value", event.target.value)} /> : <input {...props("input")} {...editable} id={`${id}-input`} type={catalog.semantic.inputType ?? "text"} value={read("value")} placeholder={read("placeholder")} readOnly={!run || Boolean(values.readOnly)} aria-invalid={Boolean(values.invalid)} aria-describedby={description ? `${id}-description` : undefined} onChange={event => request("value", event.target.value)} />}{description && <small {...props("description")} id={`${id}-description`}>{description}</small>}{Boolean(values.invalid) && <p {...props("error")}>{t("입력값을 확인하세요.", "Check this value.")}</p>}</div>; break;
    case "number-input": node = <div {...props("root")}>{fieldLabel}<div className="catalog-control-row"><button {...props("decrement")} {...editable} aria-label={t("값 감소", "Decrease value")} onClick={() => { const next = Math.max(number("min", 0), number("value", 0) - number("step", 1)); setNumberDraft(String(next)); setNumberInvalid(false); request("value", next); }}>−</button><input {...props("input")} {...editable} id={`${id}-input`} role="spinbutton" inputMode="decimal" aria-valuenow={typeof values.value === "number" ? values.value : undefined} aria-valuemin={number("min", 0)} aria-valuemax={number("max", 100)} aria-invalid={numberInvalid} readOnly={!run} value={numberDraft} onChange={event => { const text = event.target.value; setNumberDraft(text); request("draft", text); const valid = text.trim() === "" || /^[-+]?(?:\d+\.?\d*|\.\d+)$/.test(text) && Number(text) >= number("min", 0) && Number(text) <= number("max", 100); setNumberInvalid(!valid); if (valid) request("value", text.trim() === "" ? null : Number(text)); }} /><button {...props("increment")} {...editable} aria-label={t("값 증가", "Increase value")} onClick={() => { const next = Math.min(number("max", 100), number("value", 0) + number("step", 1)); setNumberDraft(String(next)); setNumberInvalid(false); request("value", next); }}>+</button></div>{numberInvalid && <small role="status">{t("완전한 숫자를 입력하세요. 이전 값은 유지됩니다.", "Enter a complete number. The previous value is retained.")}</small>}</div>; break;
    case "checkbox": case "radio": case "switch": node = <label {...props("root")} className={`catalog-check ${props("root").className}`}><input {...props("control")} {...editable} ref={checkbox} type={kind === "radio" ? "radio" : "checkbox"} role={kind === "switch" ? "switch" : undefined} name={kind === "radio" ? `${id}-${read("groupName")}` : undefined} checked={Boolean(values.checked)} onChange={event => request("checked", event.target.checked)} /><span {...props("label")}>{label}</span></label>; break;
    case "toggle": node = <button {...props("root")} {...editable} aria-pressed={Boolean(values.pressed)} onClick={() => request("pressed", !values.pressed)}><span {...props("label")}>{label}</span></button>; break;
    case "choice-group": node = <fieldset {...props("root")}><legend {...props("label")}>{label}</legend>{["segmented", "toggle-group"].includes(shape) ? <div {...props("list")} className={`${props("list").className} catalog-segmented`} role={catalog.semantic.selection === "single" ? "radiogroup" : "group"} aria-label={label}>{items.map(item => <button {...props("item")} {...editable} key={String(item.key)} disabled={disabled || Boolean(item.disabled)} {...(catalog.semantic.selection === "single" ? { role: "radio", "aria-checked": selectedKeys.includes(String(item.key)) } : { "aria-pressed": selectedKeys.includes(String(item.key)) })} onClick={() => choose(String(item.key))}>{String(item.label)}</button>)}</div> : <div {...props("list")}>{items.map(item => <label key={String(item.key)} {...props("item")} className="catalog-check"><input type={catalog.semantic.selection === "multiple" ? "checkbox" : "radio"} name={id} disabled={disabled || Boolean(item.disabled)} tabIndex={run ? 0 : -1} checked={selectedKeys.includes(String(item.key))} onChange={() => choose(String(item.key))} />{String(item.label)}</label>)}</div>}</fieldset>; break;
    case "select": node = <div {...props("root")}>{fieldLabel}<select {...props("trigger")} {...editable} id={`${id}-input`} multiple={catalog.semantic.selection === "multiple"} value={catalog.semantic.selection === "multiple" ? selectedKeys : selectedKeys[0] ?? ""} onChange={event => request(valueName, event.target.multiple ? [...event.target.selectedOptions].map(option => option.value) : event.target.value)}>{items.map(item => <option key={String(item.key)} value={String(item.key)} disabled={Boolean(item.disabled)}>{String(item.label)}</option>)}</select></div>; break;
    case "combobox": case "token-choice": node = <div {...props("root")}>{fieldLabel}<input {...props("trigger")} {...editable} id={`${id}-input`} type="search" aria-controls={`${id}-choices`} value={read("query")} readOnly={!run} onChange={event => request("query", event.target.value)} /><div {...props("list")} id={`${id}-choices`} role="group" aria-label={label}>{items.filter(item => String(item.label).toLowerCase().includes(read("query").toLowerCase())).map(item => <button {...props("item")} {...editable} key={String(item.key)} disabled={disabled || Boolean(item.disabled)} aria-pressed={selectedKeys.includes(String(item.key))} onClick={() => choose(String(item.key))}>{String(item.label)}</button>)}</div><output>{selectedKeys.filter(Boolean).join(", ")}</output></div>; break;
    case "rating": node = <div {...props("root")}><span {...props("label")}>{label}</span><div {...props("track")} className={`${props("track").className} catalog-rating`} role="radiogroup" aria-label={label}>{Array.from({ length: Math.max(1, Math.min(10, number("max", 5))) }, (_, i) => i + 1).map(value => <button {...props("thumb")} {...editable} key={value} role="radio" aria-checked={number("value", 3) === value} aria-label={`${value} ${t("점", "stars")}`} className={`${props("thumb").className} ${value <= number("value", 3) ? "is-filled" : ""}`} onClick={() => request("value", value)}>★</button>)}</div><output {...props("value")}>{String(values.value)} / {number("max", 5)}</output></div>; break;
    case "slider": case "range-slider": node = <div {...props("root")}>{fieldLabel}{(kind === "range-slider" ? Array.isArray(values.value) ? values.value : [20, 80] : [values.value ?? 50]).map((value, index) => <input {...props("thumb")} {...editable} key={index} id={index === 0 ? `${id}-input` : undefined} aria-label={kind === "range-slider" ? `${label} ${index === 0 ? t("최솟값", "lower bound") : t("최댓값", "upper bound")}` : label} type="range" min={kind === "range-slider" && index === 1 && Array.isArray(values.value) ? Number(values.value[0]) : number("min", 0)} max={kind === "range-slider" && index === 0 && Array.isArray(values.value) ? Number(values.value[1]) : number("max", 100)} step={number("step", 1)} value={Number(value)} onChange={event => request("value", kind === "range-slider" && Array.isArray(values.value) ? values.value.map((current, i) => i === index ? event.target.valueAsNumber : current) : event.target.valueAsNumber)} />)}<output {...props("value")}>{Array.isArray(values.value) ? values.value.join(" – ") : String(values.value)}</output></div>; break;
    case "progress": case "meter": {
      const ratio = Math.max(0, Math.min(1, (number("value", 50) - number("min", 0)) / Math.max(1, number("max", 100) - number("min", 0))));
      node = <div {...props("root")}><span {...props("label")}>{label}</span>{["ring-progress", "semi-progress"].includes(shape) ? <svg {...props("track")} className={`${props("track").className} catalog-ring`} viewBox={shape === "semi-progress" ? "0 0 112 70" : "0 0 112 112"} role="progressbar" aria-label={label} aria-valuenow={values.indeterminate ? undefined : number("value", 50)} aria-valuemin={number("min", 0)} aria-valuemax={number("max", 100)} fill="none" stroke="currentColor" strokeWidth="8">{shape === "semi-progress" ? <><path d="M12 58a44 44 0 0 1 88 0" opacity=".12" /><path {...props("indicator")} d="M12 58a44 44 0 0 1 88 0" pathLength="100" strokeDasharray={`${ratio * 100} 100`} /></> : <><circle cx="56" cy="56" r="43" opacity=".12" /><circle {...props("indicator")} cx="56" cy="56" r="43" pathLength="100" strokeDasharray={`${ratio * 100} 100`} transform="rotate(-90 56 56)" /></>}</svg> : kind === "progress" ? <progress {...props("track")} aria-label={label} max={number("max", 100)} value={values.indeterminate ? undefined : number("value", 50)} /> : <meter {...props("track")} aria-label={label} min={number("min", 0)} max={number("max", 100)} value={number("value", 50)} />}<output {...props("value")}>{String(values.value)}</output></div>; break;
    }
    case "loading": node = <div {...props("root")} role="status" aria-busy={Boolean(values.loading)}>{shape === "skeleton" ? <span {...props("indicator")} className={`${props("indicator").className} catalog-skeleton`} aria-hidden="true"><i /><i /><i /><i /></span> : shape === "loader" ? <span {...props("indicator")} className={`${props("indicator").className} catalog-loading-dots`} aria-hidden="true"><i /><i /><i /></span> : <span {...props("indicator")} className={`${props("indicator").className} catalog-spinner`} />}<span {...props("label")}>{label}</span></div>; break;
    case "badge": case "text": {
      const text = component.parts.find(part => part.role === "body")?.text ?? read("text", label);
      node = <div {...props("root")}>{shape === "heading" ? <h2 {...props("body")}>{text}</h2> : shape === "kbd" ? <kbd {...props("body")}>{text}</kbd> : shape === "code" || shape === "code-block" ? <code {...props("body")}>{text}</code> : shape === "blockquote" ? <blockquote {...props("body")}>{text}</blockquote> : ["highlight", "mark"].includes(shape) ? <mark {...props("body")}>{text}</mark> : <span {...props("body")}>{text}</span>}</div>; break;
    }
    case "avatar": case "image": node = <div {...props("root")}>{read("src") && !imageFailed ? <img {...props("image")} src={read("src")} alt={read("alt")} onError={() => setImageFailed(true)} /> : <span {...props("fallback")} role="img" aria-label={read("alt", label)}>{read("fallback", "AX")}</span>}</div>; break;
    case "separator": node = <hr {...props("root")} aria-orientation={values.orientation === "vertical" ? "vertical" : "horizontal"} />; break;
    case "tabs": node = <div {...props("root")}><div {...props("list")} role="tablist" aria-label={label} onKeyDown={event => { if (!run || !["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return; event.preventDefault(); const enabled = items.filter(item => !item.disabled), index = enabled.findIndex(item => item.key === values.selectedKey); const next = event.key === "Home" ? 0 : event.key === "End" ? enabled.length - 1 : (index + (event.key === "ArrowRight" ? 1 : -1) + enabled.length) % enabled.length; const item = enabled[next]; if (item) { request("selectedKey", String(item.key)); event.currentTarget.querySelectorAll<HTMLButtonElement>("button:not(:disabled)")[next]?.focus(); } }}>{items.map(item => <button {...props("trigger")} key={String(item.key)} role="tab" id={`${id}-tab-${item.key}`} aria-controls={`${id}-panel`} aria-selected={values.selectedKey === item.key} tabIndex={run && values.selectedKey === item.key ? 0 : -1} disabled={disabled || Boolean(item.disabled)} onClick={() => request("selectedKey", String(item.key))}>{String(item.label)}</button>)}</div><div {...props("panel")} role="tabpanel" id={`${id}-panel`} aria-labelledby={`${id}-tab-${values.selectedKey}`} tabIndex={run ? 0 : -1}>{String(items.find(item => item.key === values.selectedKey)?.label ?? "")} · {body}</div></div>; break;
    case "accordion": node = <div {...props("root")}>{items.map(item => { const expanded = Array.isArray(values.expandedKeys) && values.expandedKeys.includes(item.key!); return <div key={String(item.key)}><button {...props("trigger")} {...editable} disabled={disabled || Boolean(item.disabled)} aria-expanded={expanded} aria-controls={`${id}-${item.key}`} onClick={() => request("expandedKeys", expanded ? (values.expandedKeys as JsonValue[]).filter(key => key !== item.key) : values.multiple ? [...Array.isArray(values.expandedKeys) ? values.expandedKeys : [], item.key!] : [item.key!])}>{String(item.label)} <span aria-hidden="true">{expanded ? "−" : "+"}</span></button><div {...props("panel")} id={`${id}-${item.key}`} hidden={!expanded}>{body}</div></div>; })}</div>; break;
    case "dialog": case "popover": node = <div {...props("root")}><button {...props("trigger")} {...editable} ref={trigger} aria-haspopup="dialog" aria-expanded={Boolean(values.open)} onClick={() => request("open", !values.open)}>{label}</button><dialog ref={dialog} className="catalog-dialog" aria-labelledby={`${id}-title`} aria-describedby={`${id}-body`} onCancel={event => { event.preventDefault(); request("open", false); trigger.current?.focus(); }}><h2 {...props("title")} id={`${id}-title`}>{component.sampleContent.title}</h2><div {...props("body")} id={`${id}-body`}>{body}</div><button {...props("close")} autoFocus onClick={() => { request("open", false); trigger.current?.focus(); }}>{component.sampleContent.closeLabel}</button></dialog>{!run && <div className="catalog-overlay-edit"><h3 {...props("title")}>{component.sampleContent.title}</h3>{content}<button {...props("close")} tabIndex={-1}>{component.sampleContent.closeLabel}</button></div>}</div>; break;
    case "tooltip": node = <div {...props("root")}><button {...props("trigger")} {...editable} aria-describedby={run && (hover || values.open) ? `${id}-tooltip` : undefined} onPointerEnter={() => { if (run) setHover(true); }} onPointerLeave={() => setHover(false)} onFocus={() => { if (run) setHover(true); }} onBlur={() => setHover(false)} onKeyDown={event => { if (event.key === "Escape") { setHover(false); request("open", false); } }}>{label}</button>{(!run || hover || values.open) && <span {...props("content")} id={`${id}-tooltip`} role="tooltip">{body}</span>}</div>; break;
    case "menu": node = <div {...props("root")}><button {...props("trigger")} {...editable} ref={trigger} aria-haspopup="menu" aria-expanded={Boolean(values.open)} onClick={() => request("open", !values.open)} onKeyDown={event => { if (run && event.key === "ArrowDown") { event.preventDefault(); request("open", true); } }}>{label}</button>{(!run || Boolean(values.open)) && <div {...props("list")} role="menu" aria-label={label} onKeyDown={event => { if (event.key === "Escape") { request("open", false); trigger.current?.focus(); } const buttons = [...event.currentTarget.querySelectorAll<HTMLButtonElement>("button:not(:disabled)")], index = buttons.indexOf(document.activeElement as HTMLButtonElement); if (["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) { event.preventDefault(); buttons[event.key === "Home" ? 0 : event.key === "End" ? buttons.length - 1 : (index + (event.key === "ArrowDown" ? 1 : -1) + buttons.length) % buttons.length]?.focus(); } }}>{items.map((item, index) => <button {...props("item")} key={String(item.key)} autoFocus={run && index === 0} role="menuitem" disabled={Boolean(item.disabled)} tabIndex={run ? 0 : -1} onClick={() => { activate(`actionRequest: ${item.key}`); request("open", false); trigger.current?.focus(); }}>{String(item.label)}</button>)}</div>}</div>; break;
    case "link": node = <a {...props("root")} href={read("href", "#destination")} tabIndex={run ? 0 : -1} onClick={event => { event.preventDefault(); activate("navigationRequest"); }}><span {...props("label")}>{label}</span></a>; break;
    case "navigation": node = <nav {...props("root")} aria-label={label}><div {...props("list")}>{items.map(item => <a {...props("item")} key={String(item.key)} href={`#${item.key}`} tabIndex={run ? 0 : -1} aria-current={values.currentKey === item.key ? "page" : undefined} onClick={event => { event.preventDefault(); request("currentKey", String(item.key)); }}>{String(item.label)}</a>)}</div></nav>; break;
    case "table": node = <table {...props("root")}><caption>{label}</caption><thead {...props("header")}><tr>{(Array.isArray(values.columns) ? values.columns.filter(object) : []).map(column => <th key={String(column.key)} scope="col">{String(column.label)}</th>)}</tr></thead><tbody>{(Array.isArray(values.rows) ? values.rows.filter(object) : []).map(row => <tr {...props("row")} key={String(row.key)}>{(Array.isArray(row.cells) ? row.cells : []).map((cell, index) => <td {...props("cell")} key={index}>{String(cell)}</td>)}</tr>)}</tbody></table>; break;
    case "list": node = <ul {...props("root")}>{items.map(item => <li {...props("item")} key={String(item.key)}>{String(item.label)}</li>)}</ul>; break;
    case "toast": case "alert": node = <div {...props("root")}>{kind === "toast" && run && !values.open ? <button {...editable} onClick={() => request("open", true)}>{t("다시 표시", "Show again")}</button> : <div role={run ? "status" : undefined}><strong {...props("title")}>{component.sampleContent.title}</strong>{content}{(kind === "toast" || values.dismissible) && <button {...props("close")} {...editable} onClick={() => kind === "toast" ? request("open", false) : activate("dismissRequest")}>{component.sampleContent.closeLabel}</button>}</div>}</div>; break;
    case "field": node = <fieldset {...props("root")}><legend {...props("label")}>{label}{values.required ? " *" : ""}</legend>{content}<small {...props("description")}>{description}</small>{values.invalid && <p {...props("error")}>{t("입력값을 확인하세요.", "Check this value.")}</p>}</fieldset>; break;
    case "layout": {
      const renderPart = (partId: string): ReactNode => {
        const part = component.parts.find(part => part.id === partId)!;
        const children = design.layout[part.id]?.childOrder ?? [];
        return <div key={part.id} {...props(part.role)}>{part.text !== undefined ? part.text : part.role === "body" ? body : children.length ? null : part.name}{children.map(renderPart)}</div>;
      };
      node = rootPart ? renderPart(rootPart.id) : null; break;
    }
    case "toolbar": node = <div {...props("root")} role="toolbar" aria-label={label}>{content}</div>; break;
    default: node = <CatalogStructurePreview component={component} category={category} locale={locale} partProps={props} />;
  }
  return <section className="preview-section catalog-component-preview" data-catalog-id={catalog.catalogId} data-preview-shape={shape} aria-label={component.name} data-testid={`preview-${component.id}`}><div className={`component-root ${run ? "" : "edit-surface"}`} onPointerDownCapture={event => { if (run) return; const part = event.target instanceof Element ? event.target.closest<HTMLElement>("[data-part-id]")?.dataset.partId : undefined; if (part ?? rootPart?.id) { event.preventDefault(); event.stopPropagation(); onSelect(component.id, part ?? rootPart!.id); } }} onClickCapture={event => { if (!run) { event.preventDefault(); event.stopPropagation(); } }}>{node}</div>{catalog.semantic.contract === "unimplemented" && <p className="catalog-capability-note" data-testid="catalog-structure-limit">{t("편집 가능한 구조 · 전용 동작과 타깃 출력은 아직 지원하지 않습니다.", "Editable structure · dedicated interactions and target output are not yet supported.")}</p>}<dl className="preview-metadata"><div><dt>{t("변형", "Variant")}</dt><dd>{component.defaults.variant}</dd></div><div><dt>{t("파트", "Parts")}</dt><dd>{component.parts.length}</dd></div><div><dt>{t("동작", "Interaction")}</dt><dd>{catalog.semantic.contract === "defined" ? kind : t("구조만 제공", "Structure only")}</dd></div></dl>{run && catalog.semantic.contract === "defined" && <div className="run-controls"><dl className="catalog-runtime-labels"><div><dt>{t("실행 범위", "Runtime")}</dt><dd>{t("Axiom 소비자 시뮬레이션", "Axiom consumer simulation")}</dd></div><div><dt>{t("요청 이벤트", "Request events")}</dt><dd><output aria-live="polite" data-testid={`catalog-requests-${component.id}`}>{requests} {lastRequest}</output></dd></div></dl></div>}</section>;
}
