import { useMemo, useState } from "react";
import type { ProjectSnapshot } from "../../../modules/ads-core/src/index.ts";
import { inspectFoundationPolicies, FOUNDATION_POLICY_PROPERTIES } from "../../../modules/ads-core/src/index.ts";
import type { FoundationPolicyEdit, FoundationPolicyRule, FoundationPolicyViolation, FoundationTokenType } from "../../../modules/ads-core/src/index.ts";
import type { Locale } from "./locales.ts";
import { Button, Field, Select, copy } from "./ui.tsx";
import { useFormDraft } from "./form-drafts.tsx";

type RuleFields = Omit<FoundationPolicyRule, "ruleId">;
const initialRule = (): RuleFields => ({ name: "", scope: { kind: "design" }, predicate: { kind: "token-binding", properties: ["gap", "padding"], mode: "token-only" }, severity: "warning", rationale: "", exceptionRef: null });
const records = (value: unknown): { id: string; name: string }[] => Array.isArray(value) ? value.filter((item): item is { id: string; name: string } => !!item && typeof item === "object" && typeof item.id === "string" && typeof item.name === "string") : [];
const TYPES: FoundationTokenType[] = ["color", "dimension", "number", "fontFamily", "fontWeight", "duration", "cubicBezier", "strokeStyle", "border", "transition", "shadow", "gradient", "typography"];

export interface FoundationPolicyPanelProps {
  project: ProjectSnapshot; locale: Locale; disabled: boolean; onEdit(edit: FoundationPolicyEdit): boolean;
  onSelectToken?(id: string): void;
  onSelectComponent?(id: string, partId: string, category?: "Web" | "Mobile"): void;
}
/** Rules are source changes; violation severity controls delivery while the author can keep editing. */
export function FoundationPolicyPanel({ project, locale, disabled, onEdit, onSelectToken, onSelectComponent }: FoundationPolicyPanelProps) {
  const t = (ko: string, en: string) => copy(locale, ko, en), report = useMemo(() => inspectFoundationPolicies(project), [project]);
  const [editor, setEditor] = useState<{ id?: string; key: number; value: RuleFields } | null>(null), [notice, setNotice] = useState("");
  const foundation = Object.values(project.documents).find(entry => entry.document.kind === "foundation")?.document;
  const domains = records(foundation?.domains), tiers = records(foundation?.tiers);
  const components = Object.values(project.documents).filter(entry => entry.document.kind === "component").map(entry => ({ id: entry.document.id, name: entry.document.name }));
  const locationLabel = (violation: FoundationPolicyViolation) => {
    const component = violation.componentId ? project.documents[violation.componentId]?.document : undefined;
    const element = records(component?.parts).find(part => part.id === violation.partId);
    return [component?.name ?? foundation?.name, element?.name, violation.category].filter(Boolean).join(" · ");
  };
  const jump = (violation: FoundationPolicyViolation) => {
    if (violation.componentId && violation.partId && onSelectComponent) onSelectComponent(violation.componentId, violation.partId, violation.category);
    else if (violation.tokenId && onSelectToken) onSelectToken(violation.tokenId);
  };
  return <section className="foundation-policies" data-testid="foundation-policies">
    <header className="policy-heading"><div><h2>{t("시스템 정책", "System policies")}</h2><p>{t("토큰과 사용처의 규격을 정하세요. 편집은 계속하고, 필수 규칙을 통과한 결과만 출력합니다.", "Set standards for tokens and their use. Keep editing; deliver once required rules pass.")}</p></div><Button icon="plus" size="sm" disabled={disabled || !!editor} onClick={() => { setEditor({ key: Date.now(), value: initialRule() }); setNotice(""); }}>{t("규칙 추가", "Add rule")}</Button></header>
    <div className="policy-status" data-state={!report.valid || !report.canDeliver ? "blocked" : "ready"} role="status"><strong>{!report.valid ? t("정책 원본 확인 필요", "Policy source needs attention") : !report.canDeliver ? t("출력 전 수정 필요", "Changes required before delivery") : t("필수 정책 충족", "Required policies pass")}</strong><span>{report.rules.length} {t("규칙", "rules")} · {report.violations.length} {t("발견 사항", "findings")}</span></div>
    {editor && <PolicyEditor key={editor.key} {...(editor.id ? { id: editor.id } : {})} initial={editor.value} locale={locale} domains={domains} tiers={tiers} components={components} disabled={disabled} onCancel={() => setEditor(null)} onSubmit={rule => { const applied = onEdit(editor.id ? { kind: "policy-update", ruleId: editor.id, rule } : { kind: "policy-create", rule }); if (applied) { setEditor(null); setNotice(t("정책이 변경안에 추가되었습니다. 변경 검토에서 저장하세요.", "The policy joined your proposal. Save it through the shared review.")); } return applied; }} />}
    {notice && <p role="status" className="form-success">{notice}</p>}
    {!report.rules.length && !editor && <div className="policy-empty"><h3>{t("필요한 기준부터 시작하세요", "Start with the standards you need")}</h3><p>{t("간격은 토큰으로, 의미 토큰은 기본 토큰 참조로, 필수 도메인은 최소 개수로 관리할 수 있습니다. 새 규칙은 경고부터 시작합니다.", "Require spacing tokens, keep semantic tokens linked to primitives, or set a minimum inventory. New rules start as warnings.")}</p></div>}
    <div className="policy-rule-list">{report.rules.map(rule => { const findings = report.violations.filter(item => item.ruleId === rule.ruleId); return <article className="policy-rule" data-rule-id={rule.ruleId} key={rule.ruleId}><header><div><h3>{rule.name}</h3><p>{rule.rationale}</p></div><span className="badge">{rule.severity === "error" ? t("필수", "Required") : t("권장", "Advisory")}</span><Button size="sm" tone="subtle" icon="edit" aria-label={`${t("편집", "Edit")} ${rule.name}`} disabled={disabled || !!editor} onClick={() => { const { ruleId, ...value } = rule; setEditor({ id: ruleId, key: Date.now(), value }); }} /><Button size="sm" tone="subtle" icon="trash" aria-label={`${t("삭제", "Delete")} ${rule.name}`} disabled={disabled || !!editor} onClick={() => onEdit({ kind: "policy-delete", ruleId: rule.ruleId })} /></header><div className="policy-rule-summary"><span>{rule.predicate.kind === "token-minimum" ? `${t("최소 토큰", "Minimum tokens")} · ${rule.predicate.count}` : rule.predicate.kind === "token-alias" ? t("토큰 계층 참조", "Token layer references") : `${rule.predicate.properties.join(", ")} · ${rule.predicate.mode === "token-only" ? t("토큰 참조만", "Token references only") : rule.predicate.mode === "literal-only" ? t("직접 입력만", "Literals only") : t("토큰 또는 직접 입력", "Tokens or literals")}`}</span><span>{rule.scope.kind === "foundation" ? "Foundation" : [components.find(component => component.id === (rule.scope as { componentId?: string }).componentId)?.name ?? t("전체 컴포넌트", "All components"), rule.scope.category ?? "Web + Mobile"].join(" · ")}</span></div>{findings.length > 0 ? <ul className="policy-findings">{findings.slice(0, 8).map((finding, index) => <li data-document-id={finding.documentId} data-part-id={finding.partId} data-component-id={finding.componentId} data-category={finding.category} data-path={finding.path} key={`${finding.documentId}:${finding.path}:${index}`}><span className="policy-finding-mark" data-severity={finding.severity} aria-hidden="true" /><span>{finding.message}<small>{locationLabel(finding)}</small></span>{(finding.componentId && finding.partId && onSelectComponent || finding.tokenId && onSelectToken) && <Button size="sm" tone="subtle" onClick={() => jump(finding)}>{t("수정 위치", "Locate")}</Button>}</li>)}{findings.length > 8 && <li>{t(`추가 ${findings.length - 8}개. 표시된 항목을 수정하면 나머지를 볼 수 있습니다.`, `${findings.length - 8} more. Resolve these findings to reveal the rest.`)}</li>}</ul> : <p className="policy-pass">{t("이 규칙의 발견 사항이 없습니다.", "No findings for this rule.")}</p>}</article>; })}</div>
    {!report.valid && <ul className="policy-findings">{report.diagnostics.map((item, index) => <li key={index}>{item.message}</li>)}</ul>}
    <p className="field-hint policy-boundary">{t("규칙은 원본 속성 전체와 테마 재정의를 검사합니다. 예외 승인과 사용자 실행 스크립트는 아직 지원하지 않습니다. 접근성·동작 필수 검사는 정책과 별개로 유지됩니다.", "Rules inspect authored properties and theme overrides. Exception approval and executable scripts are not yet supported. Accessibility and behavior obligations remain independent.")}</p>
  </section>;
}

function PolicyEditor({ id, initial, locale, domains, tiers, components, disabled, onCancel, onSubmit }: { id?: string; initial: RuleFields; locale: Locale; domains: { id: string; name: string }[]; tiers: { id: string; name: string }[]; components: { id: string; name: string }[]; disabled: boolean; onCancel(): void; onSubmit(rule: RuleFields): boolean }) {
  const [value, setValue] = useState(initial), t = (ko: string, en: string) => copy(locale, ko, en), predicate = value.predicate;
  const valid = !!value.name.trim() && !!value.rationale.trim() && (predicate.kind !== "token-binding" || predicate.properties.length > 0) && (predicate.kind !== "token-alias" || !!predicate.tier) && (predicate.kind !== "token-minimum" || Number.isInteger(predicate.count) && predicate.count >= 1 && predicate.count <= 4096);
  const draftId = "foundation-policy-editor";
  useFormDraft({ id: draftId, label: t("시스템 정책", "System policy"), dirty: JSON.stringify(value) !== JSON.stringify(initial), valid, apply: () => valid && onSubmit(value), reset: onCancel });
  const classify = (key: "domain" | "tier" | "type", selected: string) => { const next = { ...predicate }; if (selected) Object.assign(next, { [key]: selected }); else delete (next as unknown as Record<string, unknown>)[key]; setValue({ ...value, predicate: next }); };
  return <form className="policy-editor" data-draft-form={draftId} onSubmit={event => { event.preventDefault(); if (valid) onSubmit(value); }}><fieldset disabled={disabled}><legend>{id ? t("정책 편집", "Edit policy") : t("정책 만들기", "Create policy")}</legend><div className="policy-editor-grid"><Field label={t("규칙 이름", "Rule name")}><input data-testid="policy-name" aria-label={t("규칙 이름", "Rule name")} value={value.name} maxLength={120} required placeholder={t("예: 간격은 의미 토큰 사용", "For example: Use semantic spacing")} onChange={event => setValue({ ...value, name: event.target.value })} /></Field><Field label={t("규칙 종류", "Rule type")}><Select data-testid="policy-type" aria-label={t("규칙 종류", "Rule type")} value={predicate.kind} onChange={event => { const kind = event.target.value; setValue({ ...value, scope: { kind: kind === "token-binding" ? "design" : "foundation" }, predicate: kind === "token-minimum" ? { kind, count: 1 } : kind === "token-alias" ? { kind, tier: tiers[0]?.id ?? "" } : { kind: "token-binding", properties: ["gap", "padding"], mode: "token-only" } }); }}><option value="token-binding">{t("속성의 토큰 사용", "Property token usage")}</option><option value="token-minimum">{t("최소 토큰 개수", "Minimum token inventory")}</option><option value="token-alias">{t("계층 간 참조", "Token layer references")}</option></Select></Field>
      <Field label={t("엄격도", "Severity")}><Select data-testid="policy-severity" aria-label={t("엄격도", "Severity")} value={value.severity} onChange={event => setValue({ ...value, severity: event.target.value as "warning" | "error" })}><option value="warning">{t("권장 · 출력 가능", "Advisory · delivery allowed")}</option><option value="error">{t("필수 · 위반 시 출력 차단", "Required · blocks delivery")}</option></Select></Field>
      {predicate.kind === "token-minimum" && <Field label={t("필요한 최소 개수", "Minimum count")}><input type="number" aria-label={t("필요한 최소 개수", "Minimum count")} min={1} max={4096} step={1} value={Number.isNaN(predicate.count) ? "" : predicate.count} onChange={event => setValue({ ...value, predicate: { ...predicate, count: event.target.valueAsNumber } })} /></Field>}
      {predicate.kind === "token-binding" && <Field label={t("허용 값", "Allowed values")}><Select value={predicate.mode} onChange={event => { const mode = event.target.value as "any" | "token-only" | "literal-only"; setValue({ ...value, predicate: mode === "literal-only" ? { kind: "token-binding", properties: predicate.properties, mode } : { ...predicate, mode } }); }}><option value="token-only">{t("토큰 참조만", "Token references only")}</option><option value="any">{t("토큰 또는 직접 입력", "Tokens or literals")}</option><option value="literal-only">{t("직접 입력만", "Literals only")}</option></Select></Field>}
      {(predicate.kind !== "token-binding" || predicate.mode !== "literal-only") && <><Field label={t("도메인", "Domain")}><Select value={predicate.domain ?? ""} onChange={event => classify("domain", event.target.value)}><option value="">{t("모든 도메인", "Any domain")}</option>{domains.map(domain => <option key={domain.id} value={domain.id}>{domain.name}</option>)}</Select></Field><Field label={t("토큰 계층", "Token tier")}><Select value={predicate.tier ?? ""} onChange={event => classify("tier", event.target.value)}>{predicate.kind !== "token-alias" && <option value="">{t("모든 계층", "Any tier")}</option>}{tiers.map(tier => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</Select></Field>{predicate.kind !== "token-alias" ? <Field label={t("토큰 타입", "Token type")}><Select value={predicate.type ?? ""} onChange={event => classify("type", event.target.value)}><option value="">{t("모든 타입", "Any type")}</option>{TYPES.map(type => <option key={type}>{type}</option>)}</Select></Field> : <Field label={t("참조 대상 계층", "Referenced tier")}><Select value={predicate.targetTier ?? ""} onChange={event => { const next = { ...predicate }; if (event.target.value) next.targetTier = event.target.value; else delete next.targetTier; setValue({ ...value, predicate: next }); }}><option value="">{t("모든 계층", "Any tier")}</option>{tiers.map(tier => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</Select></Field>}</>}
      {value.scope.kind === "design" && <><Field label={t("컴포넌트 범위", "Component scope")}><Select data-testid="policy-component" aria-label={t("컴포넌트 범위", "Component scope")} value={value.scope.componentId ?? ""} onChange={event => { const next: Extract<FoundationPolicyRule["scope"], { kind: "design" }> = value.scope.kind === "design" ? { ...value.scope } : { kind: "design" }; if (event.target.value) next.componentId = event.target.value; else delete next.componentId; setValue({ ...value, scope: next }); }}><option value="">{t("전체 컴포넌트", "All components")}</option>{components.map(component => <option key={component.id} value={component.id}>{component.name}</option>)}</Select></Field><Field label={t("디자인 범주", "Design category")}><Select data-testid="policy-category" aria-label={t("디자인 범주", "Design category")} value={value.scope.category ?? ""} onChange={event => { const next: FoundationPolicyRule["scope"] = { ...value.scope, kind: "design" }; if (event.target.value) next.category = event.target.value as "Web" | "Mobile"; else delete next.category; setValue({ ...value, scope: next }); }}><option value="">Web + Mobile</option><option>Web</option><option>Mobile</option></Select></Field></>}
    </div>{predicate.kind === "token-binding" && <fieldset className="policy-properties"><legend>{t("적용 속성", "Properties to check")}</legend><div className="policy-property-choices">{FOUNDATION_POLICY_PROPERTIES.map(property => <label key={property}><input type="checkbox" checked={predicate.properties.includes(property)} onChange={event => setValue({ ...value, predicate: { ...predicate, properties: event.target.checked ? [...predicate.properties, property] : predicate.properties.filter(item => item !== property) } })} /><span>{property}</span></label>)}</div></fieldset>}<Field label={t("이 규칙이 필요한 이유", "Why this rule matters")}><textarea data-testid="policy-rationale" aria-label={t("이 규칙이 필요한 이유", "Why this rule matters")} value={value.rationale} maxLength={2000} required rows={2} placeholder={t("규칙을 따르거나 수정할 때 참고할 이유", "Explain the standard so authors can act on findings")} onChange={event => setValue({ ...value, rationale: event.target.value })} /></Field><div className="form-actions"><Button data-testid="policy-apply" type="submit" tone="primary" disabled={!valid}>{t("변경안에 추가", "Add to proposal")}</Button><Button tone="subtle" onClick={onCancel}>{t("취소", "Cancel")}</Button></div></fieldset></form>;
}
