import { useState } from "react";
import { getFoundationRole, getFoundationRoles } from "../../../modules/ads-core/src/index.ts";
import type { FoundationAuthoringEdit, FoundationAuthoringProjection, FoundationTokenType } from "../../../modules/ads-core/src/index.ts";
import type { Locale } from "./locales.ts";
import { Button, Field, Select, copy } from "./ui.tsx";
import { foundationRoleLabel } from "./foundation-role-labels.ts";

type Mappings = NonNullable<Extract<FoundationAuthoringEdit, { kind: "dtcg-import" }>["mappings"]>;
export function FoundationImportMappings({ tokens, model, value, retained, locale, disabled, onChange }: { tokens: { path: string; name: string; type: FoundationTokenType }[]; model: FoundationAuthoringProjection; value: Mappings; retained: Record<string, string>; locale: Locale; disabled: boolean; onChange(value: Mappings): void }) {
  const t = (ko: string, en: string) => copy(locale, ko, en);
  const [batchDomain, setBatchDomain] = useState(model.domains.find(item => item.bindingCategory === "color")?.id ?? ""), [batchRole, setBatchRole] = useState("");
  const defaultTier = model.tiers.find(item => item.role === "semantic")?.id ?? model.tiers[0]?.id;
  const batchCategory = model.domains.find(item => item.id === batchDomain)?.bindingCategory;
  const remaining = tokens.filter(token => !retained[token.path] && !value[token.path]);
  const setDomain = (path: string, domain: string) => { const next = { ...value }; if (domain) next[path] = { domain, role: "", ...(defaultTier ? { tier: defaultTier } : {}) }; else delete next[path]; onChange(next); };
  return <section className="import-mappings"><h3>{t("시스템에 연결하기", "Connect to your system")}</h3><p className="field-hint">{t("가져오는 토큰의 도메인·용도·레이어를 지정합니다. 원본 값과 참조는 보존하고, 규격에 맞지 않는 값은 반영 전에 알려드립니다.", "Assign each imported token a domain, purpose and layer. Values and references are preserved; incompatible values are reported before applying.")}</p><div className="import-batch-mapping"><Field label={t("일괄 도메인", "Batch domain")}><Select aria-label={t("일괄 가져오기 도메인", "Batch import domain")} disabled={disabled} value={batchDomain} onChange={event => { setBatchDomain(event.target.value); setBatchRole(""); }}>{model.domains.filter(domain => domain.bindingCategory && domain.bindingCategory !== "unrestricted").map(domain => <option key={domain.id} value={domain.id}>{domain.name}</option>)}</Select></Field><Field label={t("일괄 용도", "Batch purpose")}><Select aria-label={t("일괄 가져오기 용도", "Batch import purpose")} disabled={disabled} value={batchRole} onChange={event => setBatchRole(event.target.value)}><option value="">{t("용도 선택", "Choose purpose")}</option>{getFoundationRoles(batchCategory).map(role => <option key={role.id} value={role.id}>{foundationRoleLabel(role, locale)}</option>)}</Select></Field><Button size="sm" disabled={disabled || !batchRole} onClick={() => { const role = getFoundationRole(batchRole); if (!role) return; const next = { ...value }; for (const token of remaining) if (token.type === role.type) next[token.path] = { domain: batchDomain, role: role.id, ...(defaultTier ? { tier: defaultTier } : {}) }; onChange(next); }}>{t("호환되는 미분류 토큰에 적용", "Apply to compatible unassigned tokens")}</Button></div>
    <div className="import-mapping-list">{tokens.map(token => { const existing = model.tokens.find(item => item.id === retained[token.path]); const mapping = value[token.path]; const domain = model.domains.find(item => item.id === (existing?.domain ?? mapping?.domain)); const roleId = existing?.role ?? mapping?.role ?? ""; const roles = getFoundationRoles(domain?.bindingCategory).filter(role => role.type === token.type); return <div className="import-mapping-row" key={token.path}><span title={token.path}>{token.name}{existing && <small>{t("원본 연결 유지", "Existing source mapping")}</small>}</span><Select aria-label={t(`${token.name} 가져오기 도메인`, `${token.name} import domain`)} disabled={disabled || !!existing} value={domain?.id ?? ""} onChange={event => setDomain(token.path, event.target.value)}><option value="">{t("도메인 선택", "Choose domain")}</option>{model.domains.filter(domain => domain.bindingCategory && domain.bindingCategory !== "unrestricted" && getFoundationRoles(domain.bindingCategory).some(role => role.type === token.type)).map(domain => <option key={domain.id} value={domain.id}>{domain.name}</option>)}</Select><Select aria-label={t(`${token.name} 가져오기 용도`, `${token.name} import purpose`)} disabled={disabled || !!existing || !domain} value={roleId} onChange={event => { if (mapping) onChange({ ...value, [token.path]: { ...mapping, role: event.target.value } }); }}><option value="">{t("용도 선택", "Choose purpose")}</option>{roles.map(role => <option key={role.id} value={role.id}>{foundationRoleLabel(role, locale)}</option>)}</Select><Select aria-label={t(`${token.name} 가져오기 레이어`, `${token.name} import layer`)} disabled={disabled || !!existing || !mapping} value={existing?.tier ?? mapping?.tier ?? defaultTier ?? ""} onChange={event => { if (mapping) onChange({ ...value, [token.path]: { ...mapping, tier: event.target.value } }); }}>{model.tiers.map(tier => <option key={tier.id} value={tier.id}>{tier.name}</option>)}</Select></div>; })}</div>
  </section>;
}
