import { useEffect, useMemo, useState } from "react";
import { exportSelectedFoundationDtcg, resolveDtcgResolver } from "../../../modules/ads-core/src/index.ts";
import type { FoundationAuthoringEdit, FoundationAuthoringProjection, FoundationToken, JsonObject } from "../../../modules/ads-core/src/index.ts";
import type { StudioController, StudioState } from "./controller.ts";
import type { Locale } from "./locales.ts";
import { Select, Button, Field, TabBar, TextInput, copy } from "./ui.tsx";
import { downloadText, object } from "./ui-utils.ts";

const EXAMPLE = JSON.stringify({ space: { $type: "dimension", base: { $value: { value: 8, unit: "px" } }, control: { $value: "{space.base}" } }, measure: { $type: "number", $value: { $ref: "#/space/base/$value/value" } } }, null, 2);
type ImportEdit = Extract<FoundationAuthoringEdit, { kind: "dtcg-import" }>;
const fileLimit = 1_000_000;

export function FoundationExchangePanel({ model, state, controller, locale, disabled }: { model: FoundationAuthoringProjection; state: StudioState; controller: StudioController; locale: Locale; disabled: boolean }) {
  const t = (ko: string, en: string) => copy(locale, ko, en);
  const [direction, setDirection] = useState("import"), [sourceText, setSourceText] = useState(""), [sourceName, setSourceName] = useState("tokens.json");
  const [format, setFormat] = useState<"dtcg" | "resolver">("dtcg"), [prefix, setPrefix] = useState(""), [conflicts, setConflicts] = useState<ImportEdit["conflicts"]>("keep");
  const [inputs, setInputs] = useState<Record<string, string>>({}), [sources, setSources] = useState<Record<string, string>>({}), [fileError, setFileError] = useState(false), [applied, setApplied] = useState(false);
  const [values, setValues] = useState<"references" | "resolved">("references"), [downloadError, setDownloadError] = useState(false);
  const resolver = useMemo(() => format === "resolver" && sourceText ? resolveDtcgResolver(sourceText, inputs, sources) : null, [format, sourceText, inputs, sources]);
  const edit = useMemo<ImportEdit>(() => ({ kind: "dtcg-import", sourceText, sourceName, conflicts, ...(prefix.trim() ? { prefix: prefix.trim() } : {}), format, ...(format === "resolver" ? { inputs, sources } : {}) }), [sourceText, sourceName, conflicts, prefix, format, inputs, sources]);
  const project = state.plan?.project ?? state.project;
  const preview = useMemo(() => sourceText.trim() && !fileError ? controller.previewFoundation(edit) : null, [controller, edit, project, state.selection, fileError]);
  const foundation = model.foundationId ? project?.documents[model.foundationId]?.document : undefined;
  const after = model.foundationId ? preview?.project.documents[model.foundationId]?.document.tokens as unknown as FoundationToken[] | undefined : undefined;
  const changes = (after ?? []).filter(token => JSON.stringify(model.tokens.find(before => before.id === token.id)?.value) !== JSON.stringify(token.value) || !model.tokens.some(before => before.id === token.id));
  useEffect(() => { if (changes.length) setApplied(false); }, [changes.length]);
  const added = changes.filter(token => !model.tokens.some(before => before.id === token.id)).length;
  const exported = useMemo(() => direction === "export" && foundation ? exportSelectedFoundationDtcg(foundation, state.selection, values) : null, [direction, foundation, state.selection, values]);
  const originals = Array.isArray(foundation?.originalSources) ? foundation.originalSources.filter(object) : [];
  const download = (name: string, text: string) => { setDownloadError(false); try { downloadText(name, text); } catch { setDownloadError(true); } };
  const changeSource = (text: string, name = sourceName) => { setSourceText(text); setSourceName(name); setFileError(false); setApplied(false); };
  const loadFiles = async (files: File[], support = false) => {
    try {
      if (!files.length || files.length > (support ? 32 : 1) || files.some(file => file.size > fileLimit) || files.reduce((sum, file) => sum + file.size, 0) > fileLimit) throw new Error("File limit");
      const loaded = await Promise.all(files.map(async file => [file.name, await file.text()] as const));
      if (support) { setSources(Object.fromEntries(loaded)); setApplied(false); setFileError(false); }
      else { const [name, text] = loaded[0]!; changeSource(text, name); try { const data = JSON.parse(text); setFormat(data.version === "2025.10" && data.resolutionOrder ? "resolver" : "dtcg"); } catch { /* The preview provides JSON diagnostics. */ } }
    } catch { setFileError(true); }
  };
  return <div className="exchange-panel" data-testid="foundation-exchange"><header className="section-heading"><h2>{t("토큰 파일", "Token files")}</h2><p>{t("외부 토큰을 현재 시스템에 연결하고, 선택한 테마를 다른 도구로 전달하세요.", "Bring external tokens into your system and share a selected theme with other tools.")}</p></header>
    <TabBar label={t("파일 작업", "File action")} value={direction} onChange={setDirection} options={[{ value: "import", label: t("가져오기", "Import") }, { value: "export", label: t("내보내기", "Export") }]} />
    {direction === "import" ? <div className="exchange-layout"><fieldset className="plain-fieldset exchange-source" disabled={disabled}>
      <div className="exchange-heading"><h3>{t("원본 선택", "Choose a source")}</h3><Button tone="subtle" onClick={() => { changeSource(EXAMPLE, "example.tokens.json"); setFormat("dtcg"); }}>{t("예제로 살펴보기", "Try an example")}</Button></div>
      <Field label={t("JSON 파일", "JSON file")} hint={t("최대 1 MB. 파일은 이 브라우저에서 처리됩니다.", "Up to 1 MB. Files are processed in this browser.")}><input type="file" accept=".json,application/json" aria-label={t("토큰 파일 선택", "Choose token file")} onChange={event => { void loadFiles(Array.from(event.target.files ?? []));  }} /></Field>
      <Field label={t("파일 형식", "File format")}><Select aria-label={t("파일 형식", "File format")} value={format} onChange={event => { setFormat(event.target.value as typeof format); setApplied(false); }}><option value="dtcg">DTCG Format 2025.10</option><option value="resolver">DTCG Resolver 2025.10</option></Select></Field>
      <Field label={sourceName} hint={t("JSON을 붙여 넣어도 됩니다. ‘가져오기 반영’을 누르기 전에는 프로젝트가 바뀌지 않습니다.", "You can paste JSON. Your project changes only when you apply this import.")}><textarea data-testid="dtcg-source" aria-label={t("토큰 JSON 원본", "Token JSON source")} value={sourceText} rows={12} maxLength={fileLimit} spellCheck={false} placeholder={t("토큰 JSON을 붙여 넣으세요", "Paste token JSON")} onChange={event => changeSource(event.target.value)} /></Field>
      {format === "resolver" && <><Field label={t("참조하는 JSON 파일", "Referenced JSON files")} hint={t("최대 32개, 합계 1 MB. 외부 URL은 불러오지 않습니다.", "Up to 32 files, 1 MB total. External URLs are not fetched.")}><input type="file" multiple accept=".json,application/json" aria-label={t("참조 파일 선택", "Choose referenced files")} onChange={event => { void loadFiles(Array.from(event.target.files ?? []), true);  }} /></Field><div className="choice-chips">{Object.keys(sources).map(name => <span className="value-badge" key={name}>{name}</span>)}</div>{resolver?.modifiers.map(modifier => <Field key={modifier.name} label={modifier.name}><div className="choice-chips">{modifier.contexts.map(context => <Button key={context} aria-pressed={(inputs[modifier.name] ?? modifier.default) === context} onClick={() => { setInputs(previous => ({ ...previous, [modifier.name]: context })); setApplied(false); }}>{context}</Button>)}</div></Field>)}<p className="field-hint">{t("선택한 조합을 기본 토큰으로 가져옵니다. Resolver 설정과 원본 파일은 함께 보존됩니다.", "The selected combination becomes base tokens. Resolver settings and source files are preserved alongside it.")}</p></>}
      {fileError && <p role="alert" className="field-error">{t("파일을 읽지 못했거나 크기 제한을 넘었습니다. 1 MB 이하 JSON 파일을 다시 선택하세요.", "A file could not be read or exceeds the limit. Choose JSON files within 1 MB.")}</p>}
    </fieldset><div className="exchange-preview"><h3>{t("적용 미리보기", "Import preview")}</h3><fieldset className="plain-fieldset" disabled={disabled}>
      <Field label={t("같은 이름의 토큰", "Matching token names")}><div className="choice-chips">{([ ["keep", t("기존 유지", "Keep existing")], ["update", t("값 업데이트", "Update values")], ["reject", t("충돌 시 거부", "Reject conflicts")] ] as const).map(([value, label]) => <Button key={value} aria-pressed={conflicts === value} onClick={() => { setConflicts(value); setApplied(false); }}>{label}</Button>)}</div></Field><p className="field-hint">{t("업데이트는 기존 ID와 분류, 테마 설정을 유지합니다. 유형이 다르면 접두어를 지정하세요.", "Updates retain identities, classifications and theme overrides. Use a prefix when types differ.")}</p>
      <details className="optional-field"><summary>{t("이름 접두어 추가", "Add a name prefix")}</summary><TextInput label={t("가져오기 접두어", "Import prefix")} value={prefix} placeholder="brand" onCommit={value => { setPrefix(value); setApplied(false); }} /></details>
      {!sourceText.trim() && <p className="exchange-empty">{t("원본을 선택하면 추가·변경할 토큰과 참조 오류를 확인할 수 있습니다.", "Choose a source to see new tokens, updates and reference errors.")}</p>}
      {preview?.valid && <><p className="import-count" role="status">{t(`${added}개 추가 · ${changes.length - added}개 값 변경`, `${added} added · ${changes.length - added} values updated`)}</p><ul className="exchange-token-list">{changes.slice(0, 12).map(token => <li key={token.id}><span>{token.name}</span><small>{token.typeRef.id}</small></li>)}</ul>{changes.length > 12 && <p className="field-hint">{t(`외 ${changes.length - 12}개. 전체 변경은 검토 화면에서 확인하세요.`, `${changes.length - 12} more. Review the full change before saving.`)}</p>}</>}
      {preview && !preview.valid && <div className="inline-error" role="alert"><p>{t("아직 가져올 수 없습니다. 아래 항목을 수정하세요.", "This source needs a correction before importing.")}</p>{preview.diagnostics.filter(item => item.severity === "error").slice(0, 3).map((item, i) => <p key={i}>{item.message}</p>)}</div>}
      <Button tone="primary" icon="upload" data-testid="dtcg-import-apply" disabled={disabled || !preview?.valid || fileError || applied} onClick={() => { controller.foundation(edit); if (!controller.getSnapshot().error) setApplied(true); }}>{t("가져오기 반영", "Apply import")}</Button>
      {applied && <p role="status" className="field-hint">{t("미리보기에 반영했습니다. 상단에서 변경을 검토하고 저장하세요.", "Added to the preview. Review the changes in the top bar to save.")}</p>}
    </fieldset></div></div> : <div className="exchange-export"><h3>{t("선택한 테마 내보내기", "Export selected theme")}</h3><p className="field-hint">{Object.values(model.contexts).join(" · ") || t("기본 토큰", "Base tokens")}</p><div className="choice-chips">{([ ["references", t("참조 관계 유지", "Keep references")], ["resolved", t("해석된 값", "Resolved values")] ] as const).map(([value, label]) => <Button key={value} aria-pressed={values === value} onClick={() => setValues(value)}>{label}</Button>)}</div><p className="field-hint">{t("선택한 테마의 토큰을 DTCG JSON으로 만듭니다. 다른 테마·도메인·정책까지 보존하려면 상단의 프로젝트 소스를 내려받으세요.", "Creates DTCG JSON for the selected theme. Download project source from the top bar to retain every theme, domain and policy.")}</p>{state.plan && <p className="field-hint">{t("현재 미리보기의 값을 내보냅니다. 아직 저장하지 않은 변경이 포함됩니다.", "Exports the current preview, including changes that have not been saved.")}</p>}<Button icon="download" tone="primary" disabled={!exported?.valid} data-testid="dtcg-export" onClick={() => download(`axiom-${values}.tokens.json`, exported!.text!)}>{t("토큰 JSON 다운로드", "Download token JSON")}</Button>{exported && !exported.valid && <p role="alert" className="field-error">{exported.diagnostics.filter(item => item.severity === "error").map(item => item.message).join("; ")}</p>}
      <details className="exchange-originals"><summary>{t(`보존된 원본 ${originals.length}개`, `${originals.length} preserved sources`)}</summary>{originals.map((item: JsonObject, index) => <div className="exchange-original" key={index}><span>{String(item.uri ?? `Source ${index + 1}`)}</span>{typeof item.originalText === "string" && <Button icon="download" onClick={() => download(`original-${index + 1}.json`, item.originalText as string)}>{t("가져온 토큰", "Imported tokens")}</Button>}{object(item.resolver) && <Button icon="download" onClick={() => download(`resolver-source-${index + 1}.json`, JSON.stringify(item.resolver, null, 2))}>{t("Resolver 원본 묶음", "Resolver source bundle")}</Button>}</div>)}</details>{downloadError && <p role="alert" className="field-error">{t("다운로드를 준비하지 못했습니다. 다시 시도하세요.", "Could not prepare the download. Try again.")}</p>}
    </div>}
  </div>;
}
