import { useMemo, useState } from "react";
import { getFoundationRole, getFoundationRoles, inferFoundationRole, inspectFoundationAuthoring } from "../../../modules/ads-core/src/index.ts";
import type { FoundationAuthoringEdit, FoundationAuthoringProjection } from "../../../modules/ads-core/src/index.ts";
import type { StudioController, StudioState } from "./controller.ts";
import type { Locale } from "./locales.ts";
import { Button, Select, TextInput, copy } from "./ui.tsx";
import { foundationRoleLabel } from "./foundation-role-labels.ts";

/** Dry-run first. Only the explicit propose action enters the shared atomic review transaction. */
export function FoundationMigrationPanel({ model, state, controller, locale, disabled }: { model: FoundationAuthoringProjection; state: StudioState; controller: StudioController; locale: Locale; disabled: boolean }) {
  const t = (ko: string, en: string) => copy(locale, ko, en);
  const [roles, setRoles] = useState<Record<string, string>>({}), [domains, setDomains] = useState<Record<string, string>>({}), [query, setQuery] = useState("");
  const project = state.plan?.project ?? state.project;
  const edit = useMemo<FoundationAuthoringEdit>(() => ({ kind: "foundation-migrate", roles, domains }), [roles, domains]);
  const preview = useMemo(() => model.authoringProfile ? null : controller.previewFoundation(edit), [controller, edit, project, model.authoringProfile]);
  const after = useMemo(() => preview?.valid ? inspectFoundationAuthoring(preview.project, state.selection) : null, [preview, state.selection]);
  const rows = model.tokens.filter(token => [token.name, token.id].join(" ").toLocaleLowerCase(locale).includes(query.toLocaleLowerCase(locale)));
  const changed = after ? model.tokens.filter(token => { const next = after.tokens.find(item => item.id === token.id); return next && (JSON.stringify(token.value) !== JSON.stringify(next.value) || token.role !== next.role || token.domain !== next.domain); }).length : 0;
  return <section className="foundation-migration"><header className="section-heading"><h2>{t("Foundation 규격 전환", "Migrate your foundation")}</h2><p>{t("현재 프로젝트에 기본 도메인과 용도를 채우고, 길이와 테마 값을 하나의 규격으로 정리합니다.", "Complete this project’s domains and purposes, and organize its lengths and theme values consistently.")}</p></header>
    <div className="migration-contract"><span>{t("11개 기본 도메인", "11 essential domains")}</span><span>{t("용도 기반 작성", "Purpose-based authoring")}</span><span>{t("길이 rem · 테두리 px", "Lengths in rem · borders in px")}</span><span>{t("테마 ↔ 값 그룹", "Themes ↔ value groups")}</span></div>
    {model.authoringProfile ? <p className="form-success" role="status">{t("현재 프로젝트에 작성 규격이 적용되어 있습니다.", "This project already uses the authoring profile.")}</p> : <>
      {after && <div className="migration-summary" role="status"><p><strong>{changed}</strong>{t("개 기존 토큰 정리", " existing tokens updated")}</p><p><strong>{after.tokens.length - model.tokens.length}</strong>{t("개 누락 기본값 추가", " missing defaults added")}</p><p><strong>{after.valueSets.length}</strong>{t("개 테마 값 그룹", " theme value groups")}</p></div>}
      {preview && !preview.valid && <div className="inline-error" role="alert"><h3>{t("용도를 확인할 항목이 있습니다", "Some mappings need your review")}</h3><p>{t("아직 변경하지 않았습니다. 아래 토큰의 용도 또는 도메인을 지정하면 미리보기를 다시 검사합니다.", "Nothing has changed. Choose the purpose or domain below to validate the preview again.")}</p>{preview.diagnostics.filter(item => item.severity === "error").slice(0, 6).map((item, i) => <p key={i}>{item.message}</p>)}</div>}
      <details className="migration-mappings" open={preview?.valid === false}><summary>{t(`기존 토큰 매핑 확인 · ${model.tokens.length}`, `Review existing token mappings · ${model.tokens.length}`)}</summary><TextInput label={t("전환 토큰 검색", "Search migration tokens")} value={query} placeholder={t("토큰 이름 또는 ID", "Token name or ID")} onCommit={setQuery} /><div className="migration-mapping-list">{rows.map(token => { const domain = model.domains.find(item => item.id === (domains[token.id] ?? token.domain)); const inferred = domain?.bindingCategory ? inferFoundationRole(token, domain.bindingCategory) : undefined; const resolved = roles[token.id] ?? after?.tokens.find(item => item.id === token.id)?.role ?? token.role ?? inferred?.id ?? ""; const candidates = getFoundationRoles(domain?.bindingCategory === "unrestricted" ? undefined : domain?.bindingCategory).filter(role => role.type === token.typeRef.id); const role = getFoundationRole(resolved); return <div className="migration-mapping-row" key={token.id}><span title={token.id}>{token.name}<small>{role ? foundationRoleLabel(role, locale) : t("용도를 지정하세요", "Choose a purpose")}</small></span><Select aria-label={t(`${token.name} 도메인`, `${token.name} domain`)} value={domains[token.id] ?? token.domain ?? ""} onChange={event => { setDomains(current => { const next = { ...current }; if (event.target.value) next[token.id] = event.target.value; else delete next[token.id]; return next; }); setRoles(current => { const next = { ...current }; delete next[token.id]; return next; }); }}><option value="">{t("자동 분류", "Automatic")}</option>{model.domains.filter(item => !item.allowedTypes || item.allowedTypes.includes(token.typeRef.id)).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label={t(`${token.name} 용도`, `${token.name} purpose`)} value={resolved} onChange={event => setRoles(current => { const next = { ...current }; if (event.target.value) next[token.id] = event.target.value; else delete next[token.id]; return next; })}><option value="">{t("용도 선택", "Choose a purpose")}</option>{candidates.map(item => <option key={item.id} value={item.id}>{foundationRoleLabel(item, locale)}</option>)}</Select></div>; })}</div></details>
      <Button tone="primary" disabled={disabled || !preview?.valid} data-testid="foundation-migrate" onClick={() => controller.foundation(edit)}>{t("전체 전환을 변경안에 추가", "Add the full migration to review")}</Button>
    </>}
    <p className="field-hint">{t("토큰 ID·참조·원본 출처를 보존합니다. 공통 변경 검토에서 저장하기 전에는 원본이 바뀌지 않으며, 저장한 전체 전환은 실행 취소할 수 있습니다. rem 환산 기준은 16px입니다.", "Token IDs, references and source provenance are preserved. Source changes only after the shared review is saved, and the entire migration can be undone. Rem conversion uses a 16px reference.")}</p>
  </section>;
}
