export type Locale = "ko" | "en";

const en = {
  additionalDiagnostic: "Additional diagnostic", fullDiff: "Full document field comparison", changedValues: "Changed values", beginning: "A considered beginning",
  compareCurrent: "Compare against current revision", padding: "Padding", gap: "Gap", minHeight: "Minimum height", projectRevision: "Project revision", contentTitle: "Title", actionLabel: "Action label", sourcePreparing: "Preparing source…", downloadFailed: "Source download could not be prepared.",
  title: "Design systems, made yours.", intro: "Start with a thoughtful foundation. Make one change, see it everywhere, and keep every decision.",
  projectName: "Project name", projectPlaceholder: "My design system", create: "Create design system", browserStorage: "Keep in this browser", browserStorageHelp: "Your documents stay in this browser. Export a source bundle to keep another copy.", starter: "A foundation to build on", starterDescription: "Shared tokens, two themes, and Button, Card and Toast — ready to make your own.", localOnly: "Local workspace", folderPending: "Folder connection and AI authoring are not available in this editor yet.", loading: "Opening your workspace…", retry: "Try again",
  foundation: "Foundation", components: "Components", layers: "Parts & content", tokens: "Tokens", workspace: "Workspace", preview: "Preview", canvas: "Design canvas", inspector: "Inspector", design: "Design", source: "Source", theme: "Theme", web: "Web", mobile: "Mobile", editMode: "Edit", runMode: "Try it", editModeLabel: "Edit mode", runModeLabel: "Run mode", simulation: "Design simulation", mobileApproximation: "Mobile approximation", pendingPreview: "Previewing changes", appliedPreview: "Applied design", previewHelp: "Select a part on the canvas or in the layer list.", runHelp: "Try the controls. Preview interactions do not change your documents.", emptySelection: "Select a token or component to edit its properties.",
  saved: "Saved in this browser", unsaved: "Unapplied changes", saving: "Saving…", reviewing: "Awaiting review", failedSave: "Changes could not be saved", refresh: "Refresh", undo: "Undo", redo: "Redo", sourceBundle: "Download project source", export: "Export", exportSources: "Export source code", outputTarget: "Output target", download: "Download source archive", generated: "Source generated", notRun: "Not executed in this environment", exportHelp: "Each archive includes source, dependencies and its exact design revision. Native execution is a separate check.", noExportDirty: "Apply or discard your changes before exporting this revision.", outputFiles: "Files",
  value: "Value", tokenValue: "Token value", tokenType: "Type", tokenDescription: "Shared across your system", alias: "Alias", aliasHelp: "This token keeps its reference. Edit its source token, or explicitly replace the alias with a value.", replaceAlias: "Replace alias with a value", usedBy: "Used by", valueSource: "Value source", baseValue: "Base value", contextValue: "Theme override", editContext: "Edit selected theme", editBase: "Edit base value", color: "Color", alpha: "Opacity", tokenJson: "Detailed token value (JSON)", applyInput: "Preview value", sampleContent: "Sample content", sampleHelp: "These words demonstrate the component. They do not define application behavior.", part: "Part", stableId: "Stable ID", clickToSelect: "Select", structure: "Structure", label: "Label", body: "Body", message: "Message", disabled: "Disabled", toastOpen: "Toast visible", closeResponse: "Close request response", accept: "Accept", decline: "Decline", activationCount: "Activation count", closeRequests: "Close requests", showToast: "Show toast", sampleOnly: "Preview state only", contentValue: "Content",
  documentSource: "Document source", sourceHelp: "Edit the current document. Unknown fields are preserved, and every change is reviewed before applying.", previewSource: "Preview source changes", captureDraft: "Keep source as a draft", draftCaptured: "Source draft preserved. Your applied document is unchanged.", original: "First imported original", downloadBuffer: "Download unsaved source", diagnostics: "Diagnostics", noDiagnostics: "No blocking issues in the supported profile.", unsupported: "Not supported by this profile", details: "Technical details", status: "Workspace status",
  review: "Review changes", reviewTitle: "Make this change together.", reviewDescription: "Check what changes and where it is used before updating your design system.", changedDocuments: "Changed documents", before: "Before", after: "After", impact: "Impact", approve: "Approve & apply", reject: "Discard proposal", close: "Close", discard: "Discard changes", reviewPending: "A saved proposal is ready to review.", resumeReview: "Resume review", conflict: "Another change was applied first. Your edits are still here. Compare them with the current document before trying again.", recover: "Keep your work", retrySave: "Retry the same request", changed: "Change applied", undone: "Last change undone", redone: "Change restored", language: "Interface language", unknownError: "The operation could not be completed. Your working text has been kept.", starterFailed: "The starter could not be applied. Retry to finish setting up this project.", invalidValue: "Check the value format before previewing it.", outputUnavailable: "This source cannot be generated for the selected target. Review the diagnostics.",
} as const;

const ko: Record<keyof typeof en, string> = {
  additionalDiagnostic: "추가 진단", fullDiff: "문서 필드 전체 비교", changedValues: "바뀌는 값", beginning: "차분하게 시작하는 기준",
  compareCurrent: "현재 문서에 다시 비교", padding: "안쪽 여백", gap: "간격", minHeight: "최소 높이", projectRevision: "프로젝트 revision", contentTitle: "제목", actionLabel: "동작 이름", sourcePreparing: "소스를 준비하는 중…", downloadFailed: "소스 다운로드를 준비하지 못했습니다.",
  title: "나의 기준으로 만드는 디자인 시스템.", intro: "잘 준비된 기본 시스템에서 시작하세요. 하나를 바꾸고, 전체의 변화를 확인하며, 모든 결정을 남깁니다.",
  projectName: "프로젝트 이름", projectPlaceholder: "나의 디자인 시스템", create: "디자인 시스템 만들기", browserStorage: "브라우저에 보관", browserStorageHelp: "이 브라우저에 문서를 보관합니다. 소스 묶음을 내보내 다른 곳에도 사본을 남길 수 있습니다.", starter: "만들기 좋은 출발점", starterDescription: "공유 토큰, 두 가지 테마, Button·Card·Toast가 준비되어 있습니다.", localOnly: "로컬 작업 공간", folderPending: "폴더 연결과 AI 작성은 아직 이 편집기에서 제공하지 않습니다.", loading: "작업 공간을 여는 중…", retry: "다시 시도",
  foundation: "파운데이션", components: "컴포넌트", layers: "부위와 콘텐츠", tokens: "토큰", workspace: "작업 공간", preview: "미리보기", canvas: "디자인 편집면", inspector: "속성", design: "디자인", source: "원문", theme: "테마", web: "Web", mobile: "Mobile", editMode: "편집", runMode: "직접 실행", editModeLabel: "편집 모드", runModeLabel: "실행 모드", simulation: "디자인 시연", mobileApproximation: "Mobile 근사 시연", pendingPreview: "변경안 미리보기", appliedPreview: "적용된 디자인", previewHelp: "편집면이나 부위 목록에서 수정할 부분을 선택하세요.", runHelp: "컨트롤을 직접 조작해 보세요. 시연 상태는 문서에 저장되지 않습니다.", emptySelection: "토큰이나 컴포넌트를 선택해 속성을 수정하세요.",
  saved: "이 브라우저에 저장됨", unsaved: "아직 적용하지 않은 변경", saving: "저장 중…", reviewing: "검토 대기", failedSave: "변경을 저장하지 못함", refresh: "새로고침", undo: "되돌리기", redo: "다시 실행", sourceBundle: "프로젝트 소스 다운로드", export: "내보내기", exportSources: "소스 코드 내보내기", outputTarget: "출력 타깃", download: "소스 압축파일 다운로드", generated: "소스 생성됨", notRun: "이 환경에서 실행 검증하지 않음", exportHelp: "소스, 의존성, 정확한 디자인 revision을 함께 제공합니다. 네이티브 실행은 별도로 확인합니다.", noExportDirty: "현재 변경을 적용하거나 취소한 뒤 해당 revision을 내보내세요.", outputFiles: "파일",
  value: "값", tokenValue: "토큰 값", tokenType: "타입", tokenDescription: "시스템 전체에서 함께 사용", alias: "참조", aliasHelp: "참조 관계를 유지하는 토큰입니다. 원천 토큰을 수정하거나 명시적으로 값으로 바꾸세요.", replaceAlias: "참조를 끊고 값으로 바꾸기", usedBy: "사용처", valueSource: "값의 출처", baseValue: "기본값", contextValue: "테마별 값", editContext: "선택한 테마 수정", editBase: "기본값 수정", color: "색상", alpha: "불투명도", tokenJson: "토큰 값 상세 (JSON)", applyInput: "값 미리보기", sampleContent: "시연 콘텐츠", sampleHelp: "컴포넌트를 보여 주는 예시 문구입니다. 앱의 업무 동작을 정의하지 않습니다.", part: "부위", stableId: "안정 ID", clickToSelect: "선택", structure: "구조", label: "이름", body: "본문", message: "메시지", disabled: "사용 안 함", toastOpen: "Toast 표시", closeResponse: "닫기 요청 응답", accept: "승인", decline: "거절", activationCount: "활성화 횟수", closeRequests: "닫기 요청 횟수", showToast: "Toast 다시 표시", sampleOnly: "시연에만 적용되는 상태", contentValue: "내용",
  documentSource: "문서 원문", sourceHelp: "현재 문서를 수정합니다. 알 수 없는 필드는 보존하고, 모든 변경은 검토 후 적용합니다.", previewSource: "원문 변경 미리보기", captureDraft: "원문을 초안으로 보관", draftCaptured: "원문 초안을 보관했습니다. 적용된 문서는 바뀌지 않았습니다.", original: "처음 가져온 원본", downloadBuffer: "저장하지 못한 원문 다운로드", diagnostics: "진단", noDiagnostics: "지원 범위에서 적용을 막는 문제가 없습니다.", unsupported: "이 프로필에서 지원하지 않음", details: "기술 정보", status: "작업 공간 상태",
  review: "변경 내용 검토", reviewTitle: "전체의 변화를 함께 확인하세요.", reviewDescription: "디자인 시스템에 적용하기 전에 변경 내용과 사용처를 확인하세요.", changedDocuments: "바뀌는 문서", before: "이전", after: "변경 후", impact: "영향", approve: "승인하고 적용", reject: "변경안 취소", close: "닫기", discard: "변경 취소", reviewPending: "보관된 변경안을 검토할 수 있습니다.", resumeReview: "검토 이어가기", conflict: "다른 변경이 먼저 적용되었습니다. 작성한 내용은 유지했습니다. 현재 문서와 비교한 뒤 다시 시도하세요.", recover: "작성 내용 보존", retrySave: "같은 요청 재시도", changed: "변경을 적용했습니다", undone: "마지막 변경을 되돌렸습니다", redone: "변경을 다시 적용했습니다", language: "화면 언어", unknownError: "작업을 완료하지 못했습니다. 작성 중인 원문은 유지했습니다.", starterFailed: "기본 시스템을 적용하지 못했습니다. 다시 시도해 프로젝트 준비를 마치세요.", invalidValue: "미리보기 전에 값의 형식을 확인하세요.", outputUnavailable: "선택한 타깃의 소스를 만들 수 없습니다. 진단 내용을 확인하세요.",
};

export type MessageKey = keyof typeof en;
export const messages: Record<Locale, Record<MessageKey, string>> = { ko, en };
export const translate = (locale: Locale, key: MessageKey): string => messages[locale][key];
