import { useEffect, useRef, useState } from "react";
import type { JsonValue, StudioComponent, StudioMotionTrack } from "../../../modules/ads-core/src/index.ts";
import type { StudioController, StudioState } from "./controller.ts";
import type { Locale } from "./locales.ts";
import { Select, Button, Field, Section, copy } from "./ui.tsx";
import { useFormDraft } from "./form-drafts.tsx";
import { MotionPreview } from "./motion-preview.ts";
import { object } from "./ui-utils.ts";

const EASINGS = [{ name: "Standard", value: [.2, 0, 0, 1] }, { name: "Ease out", value: [0, 0, .2, 1] }, { name: "Linear", value: [0, 0, 1, 1] }];
const preset = (partId: string, property: StudioMotionTrack["property"] = "opacity"): Omit<StudioMotionTrack, "id"> => ({ targetPartRef: partId, property, trigger: "enter", keyframes: [{ offset: 0, value: property === "opacity" ? 0 : property === "scale" ? .9 : 16 }, { offset: 1, value: property === "translateY" ? 0 : 1 }], timing: { kind: "tween", duration: { value: 240, unit: "ms" }, easing: [.2, 0, 0, 1] }, delay: { value: 0, unit: "ms" }, interruption: "replace-from-current", reducedAlternative: { kind: "snap", value: property === "translateY" ? 0 : 1 } });

export function MotionInspector({ state, controller, component, partId, locale }: { state: StudioState; controller: StudioController; component: StudioComponent; partId: string; locale: Locale }) {
  const t = (ko: string, en: string) => copy(locale, ko, en), project = state.plan?.project ?? state.project;
  const tracks = (project?.documents[component.id]?.document.motion ?? []) as unknown as StudioMotionTrack[];
  const [selected, setSelected] = useState(""), [draft, setDraft] = useState(preset(partId)), [dirty, setDirty] = useState(false), [invalidFields, setInvalidFields] = useState<string[]>([]), [epoch, setEpoch] = useState(0);
  const [reduced, setReduced] = useState(false), [position, setPosition] = useState(0), [playing, setPlaying] = useState(false);
  const player = useRef(new MotionPreview());
  const invalid = invalidFields.length > 0;
  const current = tracks.find(track => track.id === selected);
  useEffect(() => { if (!dirty) setDraft(current ?? preset(partId)); }, [current, partId, dirty]);
  useEffect(() => () => player.current.reset(), [component.id, partId]);
  const update = (patch: Partial<Omit<StudioMotionTrack, "id">>) => { setDraft(before => ({ ...before, ...patch })); setDirty(true); player.current.reset(); setPlaying(false); };
  const reset = () => { setDirty(false); setInvalidFields([]); setEpoch(value => value + 1); setDraft(current ?? preset(partId)); controller.clearInputError(); player.current.reset(); setPlaying(false); };
  const apply = () => { const { id: _id, ...track } = draft as StudioMotionTrack; controller.component([{ componentId: component.id, edit: { kind: "motion-track-set", track, trackId: selected || null } }]); if (controller.getSnapshot().error) return false; setDirty(false); if (!selected) { const source = controller.getSnapshot().plan?.project.documents[component.id]?.document.motion as unknown as StudioMotionTrack[]; setSelected(source?.at(-1)?.id ?? ""); } return true; };
  useFormDraft({ id: "motion-track", label: t("모션 트랙", "Motion track"), dirty, valid: !invalid, apply, reset });
  const resolved = component.motionTracks?.find(track => track.id === selected), duration = resolved ? resolved.durationMs + resolved.delayMs : 0;
  useEffect(() => { if (!playing) return; let handle = 0; const tick = () => { const time = player.current.time; setPosition(time); if (time >= duration || reduced || matchMedia("(prefers-reduced-motion: reduce)").matches) setPlaying(false); else handle = requestAnimationFrame(tick); }; handle = requestAnimationFrame(tick); return () => cancelAnimationFrame(handle); }, [playing, duration, reduced]);
  const play = () => { const root = [...document.querySelectorAll<HTMLElement>(".catalog-component-preview")].find(element => element.dataset.testid === `preview-${component.id}`); if (!root || !resolved) return; player.current.reset(); player.current.play(root, [resolved], reduced || matchMedia("(prefers-reduced-motion: reduce)").matches); setPlaying(true); };
  const numberInput = (label: string, value: number, min: number, max: number, change: (value: number) => void, step = "any") => <Field label={label}><input aria-label={label} type="number" min={min} max={max} step={step} defaultValue={value} key={`${selected}/${label}/${value}/${epoch}`} onBlur={event => { const number = event.currentTarget.valueAsNumber; if (!Number.isFinite(number) || number < min || number > max) { setInvalidFields(before => [...new Set([...before, label])]); setDirty(true); event.currentTarget.setAttribute("aria-invalid", "true"); } else { setInvalidFields(before => before.filter(item => item !== label)); change(number); } }} onChange={event => { setDirty(true); const n = event.currentTarget.valueAsNumber; setInvalidFields(before => !Number.isFinite(n) || n < min || n > max ? [...new Set([...before, label])] : before.filter(item => item !== label)); }} /></Field>;
  const typedDuration = (label: string, value: JsonValue, change: (value: JsonValue) => void) => <div className="property-group"><Field label={label}><Select aria-label={`${label} · ${t("토큰", "Token")}`} value={object(value) && typeof value.tokenRef === "string" ? value.tokenRef : "literal"} onChange={event => change(event.target.value === "literal" ? { value: 240, unit: "ms" } : { tokenRef: event.target.value })}><option value="literal">{t("직접 값 · ms", "Literal · ms")}</option>{state.projection?.foundation.tokens.filter(token => token.type === "duration").map(token => <option value={token.id} key={token.id}>{token.name}</option>)}</Select></Field>{object(value) && typeof value.value === "number" && numberInput(`${label} · ms`, value.value * (value.unit === "s" ? 1000 : 1), 0, 10000, value => change({ value, unit: "ms" }))}</div>;
  return <Section title={t("모션 타임라인", "Motion timeline")} defaultOpen={false}><div className="form-stack" data-draft-form="motion-track">
    <Field label={t("트랙", "Track")}><Select data-testid="motion-track-select" disabled={dirty} value={selected} aria-label={t("모션 트랙", "Motion track")} onChange={event => { setSelected(event.target.value); player.current.reset(); setPlaying(false); }}><option value="">{t("새 모션", "New motion")}</option>{tracks.filter(track => track.targetPartRef === partId).map(track => <option value={track.id} key={track.id}>{track.trigger} · {track.property}</option>)}</Select></Field>
    {!selected && <div className="suggestion-chips" aria-label={t("모션 프리셋", "Motion presets")}>{(["opacity", "translateY", "scale"] as const).map((property, index) => <Button size="sm" data-testid={`motion-preset-${property}`} key={property} onClick={() => { setDraft(preset(partId, property)); setDirty(true); }}>{[t("페이드", "Fade"), t("슬라이드", "Slide"), t("확대", "Scale")][index]}</Button>)}</div>}
    <div className="property-group"><Field label={t("미리보기 트리거", "Preview trigger")}><Select value={draft.trigger} onChange={event => update({ trigger: event.target.value as typeof draft.trigger })}>{["enter", "exit", "state"].map(item => <option key={item}>{item}</option>)}</Select></Field><Field label={t("속성", "Property")}><Select value={draft.property} onChange={event => { setDraft(preset(partId, event.target.value as typeof draft.property)); setDirty(true); }}>{["opacity", "translateY", "scale"].map(item => <option key={item}>{item}</option>)}</Select></Field></div>
    <div className="motion-keyframes"><div className="section-heading">{t("키프레임", "Keyframes")} <span className="badge">{draft.keyframes.length}</span></div>{draft.keyframes.map((frame, index) => <div className="property-group" key={index}>{numberInput(`${t("위치", "Offset")} ${index + 1} · %`, frame.offset * 100, 0, 100, value => update({ keyframes: draft.keyframes.map((item, at) => at === index ? { ...item, offset: value / 100 } : item) }))}{numberInput(`${t("값", "Value")} ${index + 1}`, frame.value, draft.property === "opacity" ? 0 : draft.property === "scale" ? .01 : -4096, draft.property === "opacity" ? 1 : draft.property === "scale" ? 10 : 4096, value => update({ keyframes: draft.keyframes.map((item, at) => at === index ? { ...item, value } : item) }))}{index > 0 && index < draft.keyframes.length - 1 && <Button size="sm" onClick={() => update({ keyframes: draft.keyframes.filter((_, at) => at !== index) })}>{t("제거", "Remove")}</Button>}</div>)}</div>
    {draft.timing.kind === "tween" && draft.keyframes.length < 32 && <Button size="sm" onClick={() => { const frames = [...draft.keyframes], pairs = frames.slice(1).map((frame, index) => ({ index, distance: frame.offset - frames[index]!.offset })), widest = pairs.sort((a, b) => b.distance - a.distance)[0]!; const first = frames[widest.index]!, last = frames[widest.index + 1]!; frames.splice(widest.index + 1, 0, { offset: (first.offset + last.offset) / 2, value: (first.value + last.value) / 2 }); update({ keyframes: frames }); }}>{t("중간 키프레임 추가", "Add midpoint keyframe")}</Button>}
    <Field label={t("타이밍", "Timing")}><Select data-testid="motion-timing" value={draft.timing.kind} onChange={event => update({ timing: event.target.value === "spring" ? { kind: "spring", stiffness: 170, damping: 26, mass: 1 } : { kind: "tween", duration: { value: 240, unit: "ms" }, easing: [.2, 0, 0, 1] }, keyframes: [draft.keyframes[0]!, draft.keyframes.at(-1)!] })}><option value="tween">Tween</option><option value="spring">Spring</option></Select></Field>
    {draft.timing.kind === "tween" ? <>{typedDuration(t("지속 시간", "Duration"), draft.timing.duration, duration => { if (draft.timing.kind === "tween") update({ timing: { ...draft.timing, duration } }); })}<Field label={t("이징 토큰·프리셋", "Easing token or preset")}><Select aria-label={t("이징 토큰·프리셋", "Easing token or preset")} value={object(draft.timing.easing) ? String(draft.timing.easing.tokenRef) : `preset:${JSON.stringify(draft.timing.easing)}`} onChange={event => { if (draft.timing.kind === "tween") update({ timing: { ...draft.timing, easing: event.target.value.startsWith("preset:") ? JSON.parse(event.target.value.slice(7)) as JsonValue : { tokenRef: event.target.value } } }); }}>{!object(draft.timing.easing) && !EASINGS.some(preset => JSON.stringify(preset.value) === JSON.stringify(draft.timing.kind === "tween" ? draft.timing.easing : null)) && <option value={`preset:${JSON.stringify(draft.timing.easing)}`}>{t("사용자 곡선", "Custom curve")}</option>}{EASINGS.map(preset => <option key={preset.name} value={`preset:${JSON.stringify(preset.value)}`}>{preset.name}</option>)}{state.projection?.foundation.tokens.filter(token => token.type === "cubicBezier").map(token => <option value={token.id} key={token.id}>{token.name}</option>)}</Select></Field></> : <div className="property-group">{([['stiffness', 1, 1000], ['damping', 1, 100], ['mass', .1, 10]] as const).map(([field, min, max]) => <div key={field}>{numberInput(field, draft.timing.kind === "spring" ? draft.timing[field] : 1, min, max, value => { if (draft.timing.kind === "spring") update({ timing: { ...draft.timing, [field]: value } }); })}</div>)}</div>}
    {typedDuration(t("지연", "Delay"), draft.delay, delay => update({ delay }))}
    <Field label={t("재실행 정책", "Interruption")}><Select value={draft.interruption} onChange={event => update({ interruption: event.target.value as typeof draft.interruption })}>{["finish-then-next", "replace-from-current", "snap"].map(value => <option key={value}>{value}</option>)}</Select></Field>
    {numberInput(t("동작 줄이기 · 대체값", "Reduced motion · snap value"), draft.reducedAlternative.value, draft.property === "opacity" ? 0 : draft.property === "scale" ? .01 : -4096, draft.property === "opacity" ? 1 : draft.property === "scale" ? 10 : 4096, value => update({ reducedAlternative: { kind: "snap", value } }))}
    {invalid && <p role="alert" className="input-feedback">{t("숫자 범위를 확인하거나 입력을 초기화하세요.", "Check the number range or reset this input.")}</p>}
    <div className="form-actions"><Button tone="primary" data-testid="motion-track-apply" disabled={invalid || !dirty} onClick={apply}>{t("트랙 반영", "Apply track")}</Button>{dirty && <Button onClick={reset}>{t("입력 초기화", "Reset input")}</Button>}{selected && <Button tone="danger" disabled={dirty} onClick={() => { controller.component([{ componentId: component.id, edit: { kind: "motion-track-delete", trackId: selected } }]); if (!controller.getSnapshot().error) { setSelected(""); player.current.reset(); setPlaying(false); } }}>{t("트랙 제거", "Remove track")}</Button>}</div>
    {resolved && <div className="motion-player"><label><input type="checkbox" checked={reduced} onChange={event => { setReduced(event.target.checked); player.current.reset(); setPlaying(false); }} /> {t("동작 줄이기 미리보기", "Preview reduced motion")}</label><div className="form-actions"><Button data-testid="motion-play" disabled={dirty} onClick={play}>{t("재생", "Play")}</Button><Button data-testid="motion-pause" onClick={() => { player.current.pause(); setPlaying(false); }}>{t("일시정지", "Pause")}</Button><Button onClick={() => { player.current.reset(); setPlaying(false); setPosition(0); }}>{t("원위치", "Reset")}</Button></div><input aria-label={t("모션 타임라인", "Motion timeline")} type="range" min={0} max={Math.max(1, duration)} step={1} value={Math.min(position, duration)} onChange={event => { if (!position) play(); player.current.seek(event.target.valueAsNumber); setPosition(event.target.valueAsNumber); setPlaying(false); }} /><output>{Math.round(position)} / {Math.round(duration)} ms</output><Button size="sm" onClick={() => { player.current.seek(Math.min(duration, position + 1000 / 60)); setPosition(player.current.time); setPlaying(false); }}>{t("한 프레임", "Step frame")}</Button></div>}
    <p className="field-hint">{t("실행은 미리보기 파트에만 적용됩니다. 동작 그래프의 이벤트·완료 효과 연결과 타깃 모션 출력은 준비 중입니다.", "Playback affects preview parts. Behavior event/completion bindings and target motion output are pending.")}</p>
  </div></Section>;
}
