import { useState } from "react";
import type { Locale } from "./locales.ts";
import { Button, Field, IconButton, Section, TextInput, copy } from "./ui.tsx";
import { TokenVisual } from "./token-visual.tsx";

export function SystemPanel({ locale }: { locale: Locale }) {
  const [value, setValue] = useState("Axiom Studio"), [selected, setSelected] = useState("md"), [tier, setTier] = useState(0), [notice, setNotice] = useState("");
  const t = (ko: string, en: string) => copy(locale, ko, en);
  return <section className="system-panel"><div className="panel-heading"><div><h1>Axiom UI</h1><p>{t("값에 집중하는 편집기. 하나의 색, 일관된 규격, 필요한 만큼의 움직임.", "An editor built around values. One signal color, consistent controls, purposeful motion.")}</p></div><span className="badge">SUIT Variable</span></div>
    <section className="system-section"><div className="system-brand"><span className="logo-mark">A</span><div><h2>{t("선택을 밝히는 색", "A color that marks your choice")}</h2><p>#B9FF46 · {t("형광 라임", "Signal lime")}</p></div><span className="brand-chip" /></div><p className="help">{t("라임은 주요 실행과 선택에, 중립색은 작업 면과 정보에 사용합니다. 밝은 테마에서도 같은 역할을 유지합니다.", "Lime marks primary actions and selection. Neutral surfaces carry work and information, with the same roles in light mode.")}</p><div className="color-roles">{["surface", "canvas", "ink", "accent", "positive", "warning", "negative", "line", "focus"].map(role => <div key={role}><i style={{ background: `var(--${role})` }} /><span>{role}</span></div>)}</div></section>
    <section className="system-section"><h2>{t("글자 규격", "Type roles")}</h2>{([['heading', '24 / 32 · 650', 'Create a coherent system'], ['title', '18 / 26 · 650', 'Foundation and components'], ['body', '14 / 22 · 450', '명확한 편집, 일관된 결과'], ['label', '13 / 18 · 550', 'Keep the details within reach'], ['caption', '12 / 18 · 450', 'radius.medium · 12 px']] as const).map(([role, spec, content]) => <div className="system-type" key={role}><small>{role}<br />{spec}</small><span className={`type-${role}`}>{content}</span></div>)}</section>
    <section className="system-section"><h2>{t("동작과 상태", "Actions and states")}</h2><div className="row flex-wrap">{(["primary", "secondary", "subtle", "danger"] as const).map(tone => <Button key={tone} tone={tone} onClick={() => setNotice(`${tone} · ${t("선택했습니다", "selected")}`)}>{tone}</Button>)}<Button disabled>{t("사용 불가", "Disabled")}</Button><Button aria-busy="true" disabled>{t("처리 중", "Working")}</Button><IconButton icon="settings" label={t("설정 예제", "Settings example")} onClick={() => setNotice(t("설정 컨트롤을 선택했습니다", "Settings control selected"))} /></div><p role="status" className="help">{notice || t("버튼을 눌러 상태를 확인하세요.", "Use a control to inspect its state.")}</p></section>
    <section className="system-section"><h2>{t("크기와 입력", "Sizes and inputs")}</h2><div className="control-specimens">{(["sm", "md", "lg"] as const).map((size, i) => <div key={size} className="control-specimen" data-control-size={size}><span className="type-caption">{size.toUpperCase()} · {[32, 40, 48][i]} px</span><Button size={size} tone={selected === size ? "primary" : "secondary"} onClick={() => setSelected(size)} aria-pressed={selected === size}>{t("선택", "Select")}</Button><Field label={t("이름", "Name")}><TextInput label={`${size} ${t("이름", "name")}`} value={value} onCommit={setValue} /></Field><Field label={t("규격", "Size")}><select aria-label={`${size} ${t("규격", "size")}`} value={selected} onChange={event => setSelected(event.target.value)}><option value="sm">Compact</option><option value="md">Default</option><option value="lg">Comfortable</option></select></Field></div>)}</div><div className="choice-chips">{["Primitive", "Semantic", "Component"].map((label, index) => <Button key={label} size="sm" aria-pressed={tier === index} onClick={() => setTier(index)}>{label}</Button>)}<span className="badge accent">{t("연결됨", "Linked")}</span><span className="badge amber">{t("검토 필요", "Needs review")}</span></div></section>
    <section className="system-section"><h2>{t("간격과 깊이", "Space and depth")}</h2><div className="system-spacing">{[4, 8, 12, 16, 20, 24, 32, 40].map(space => <div key={space}><span>{space}</span><i style={{ width: space }} /></div>)}</div><div className="system-depth"><div>{t("작업 면", "Surface")}</div><div>{t("떠 있는 도구", "Floating tool")}</div></div></section>
    <section className="system-section"><h2>{t("움직임", "Motion")}</h2><p className="help">{t("피드백 150 ms · 펼치기 250 ms. 동작 줄이기 설정에서는 이동을 생략합니다.", "Feedback 150 ms · disclosure 250 ms. Reduced motion removes movement.")}</p><div className="system-motion"><TokenVisual type="transition" value={{ duration: { value: 250, unit: "ms" }, delay: { value: 0, unit: "ms" }, timingFunction: [.22, 1, .36, 1] }} locale={locale} interactive /><Section title={t("펼치기 미리보기", "Preview disclosure")} defaultOpen={false}><p className="type-body">{t("관련된 속성만 펼쳐 보고, 편집 중인 값은 그대로 유지합니다.", "Reveal related properties while keeping in-progress values intact.")}</p></Section></div></section>
  </section>;
}
