import { useEffect, useRef, useState } from "react";
import type { ReactNode } from "react";
import { getStudioCatalogRecipe, listStudioCatalog, studioCatalogPresentation, studioCatalogProvenance } from "../../../modules/ads-core/src/index.ts";
import type { StudioCatalogEntry } from "../../../modules/ads-core/src/index.ts";
import { CatalogThumbnail } from "./catalog-thumbnail.tsx";
import { Icon } from "./icons.tsx";
import type { Locale } from "./locales.ts";
import { Select, Button, EmptyState, Field, IconButton, Section, copy } from "./ui.tsx";

export const CATALOG = listStudioCatalog();
export function LibraryPanel({ locale, selected, onSelect, onAdd, disabled }: { locale: Locale; selected: string; onSelect(id: string): void; onAdd(id: string, name?: string): void; disabled: boolean }) {
  const [query, setQuery] = useState(""), [kind, setKind] = useState("component"), [family, setFamily] = useState("");
  const t = (ko: string, en: string) => copy(locale, ko, en);
  const families = [...new Set(CATALOG.flatMap(entry => entry.familyIds))].sort();
  const entries = CATALOG.filter(entry => (!kind || entry.kind === kind) && (!family || entry.familyIds.includes(family)) && `${entry.name} ${entry.familyIds.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="library-panel" aria-label={t("컴포넌트 라이브러리", "Component library")}><div className="panel-heading"><div><h1>{t("라이브러리", "Library")}</h1><p>{t("시스템에 필요한 컴포넌트를 찾아 추가하세요.", "Find the components your system needs.")}</p></div><Button tone="primary" icon="plus" data-testid="create-custom-component" disabled={disabled} onClick={() => onAdd("catalog.box", t("새 컴포넌트", "Untitled component"))}>{t("빈 컴포넌트 만들기", "Create blank component")}</Button></div><div className="library-toolbar"><div className="search-field"><Icon name="search" size={14} /><input data-testid="catalog-search" aria-label={t("라이브러리 검색", "Search library")} placeholder={t("이름 또는 패밀리 검색…", "Search names or families…")} value={query} onChange={event => setQuery(event.target.value)} /></div><Select aria-label={t("항목 종류", "Entry kind")} value={kind} onChange={event => setKind(event.target.value)}><option value="component">{t("컴포넌트", "Components")}</option><option value="part">{t("파트", "Parts")}</option><option value="template">{t("템플릿", "Templates")}</option><option value="utility">{t("유틸리티", "Utilities")}</option><option value="">{t("모든 항목", "All entries")}</option></Select><Select aria-label={t("패밀리", "Family")} value={family} onChange={event => setFamily(event.target.value)}><option value="">{t("모든 패밀리", "All families")}</option>{families.map(id => <option key={id}>{id}</option>)}</Select></div><div className="library-results"><span className="help" role="status">{entries.length} {t("개 항목", "entries")}</span><div className="catalog-grid">{entries.map(entry => <article key={entry.id} className={`catalog-card ${selected === entry.id ? "selected" : ""}`}><button className="catalog-select" data-testid={`catalog-${entry.id}`} aria-pressed={selected === entry.id} onClick={() => onSelect(entry.id)}><span className="catalog-symbol"><CatalogThumbnail entry={entry} /></span><strong>{entry.name}</strong><small>{[...new Set(entry.providerVariants.map(variant => variant.provider))].join(" · ")}</small></button><div className="catalog-card-footer"><span className="badge">{getStudioCatalogRecipe(entry.id)?.semantic.contract === "defined" ? t("Axiom 상호작용", "Axiom interaction") : t("구조 편집", "Editable structure")}</span>{entry.kind === "component" && <IconButton icon="plus" label={t(`${entry.name} 추가`, `Add ${entry.name}`)} disabled={disabled} onClick={() => onAdd(entry.id)} />}</div></article>)}</div>{!entries.length && <EmptyState title={t("검색 결과가 없습니다", "No matching entries")} description={t("다른 이름을 검색하거나 필터를 해제하세요.", "Try another name or clear the filters.")}><Button onClick={() => { setQuery(""); setFamily(""); }}>{t("필터 초기화", "Clear filters")}</Button></EmptyState>}</div></section>;
}

export function CatalogInspector({ entry, locale, onAdd, disabled }: { entry: StudioCatalogEntry | undefined; locale: Locale; onAdd(id: string, name?: string): void; disabled: boolean }) {
  const t = (ko: string, en: string) => copy(locale, ko, en), recipe = entry ? getStudioCatalogRecipe(entry.id) : null;
  return <aside className="inspector" aria-label={t("라이브러리 상세", "Library details")}><div className="inspector-header"><h2>{entry?.name ?? t("라이브러리", "Library")}</h2><p>{entry?.kind}</p></div><div className="inspector-body">{entry && recipe ? <><Section title={t("시스템에 추가", "Add to your system")}><CatalogThumbnail entry={entry} /><p className="help">{entry.kind === "component" ? t("Axiom이 작성한 파트·디자인으로 독립 컴포넌트를 만듭니다. 참조 라이브러리의 패키지를 복사하거나 실행하지 않습니다.", "Creates an independent Axiom-authored component and Web/Mobile designs. Reference-library packages are not copied or executed.") : t("이 항목은 패밀리의 참조 구성요소입니다. 독립 컴포넌트 생성은 제공하지 않습니다.", "This is a family reference entry, without standalone component creation.")}</p>{entry.kind === "component" && <Button tone="primary" icon="plus" data-testid="catalog-add" disabled={disabled} onClick={() => onAdd(entry.id)}>{t("컴포넌트 추가", "Add component")}</Button>}</Section><Section title={t("의미와 구조", "Meaning and structure")}><Field label={t("동작", "Interaction")}><span>{recipe.semantic.kind}</span></Field><div className="chip-list">{[...recipe.parts, ...studioCatalogPresentation(entry, recipe.semantic.kind).parts.filter(part => !recipe.parts.some(required => required.role === part.role))].map(part => <span className="badge" key={part.role}>{part.role}</span>)}</div><p className="help">{recipe.semantic.contract === "unimplemented" ? t("전용 상호작용과 접근성 구현이 필요합니다. 구조를 편집할 수 있으며 실행과 타깃 출력은 지원 여부를 확인합니다.", "Dedicated interaction and accessibility implementation is required. Structure can be authored; execution and export check capability.") : t("값·이벤트·파트 계약을 포함합니다. 타깃별 실행 지원은 내보내기 진단으로 확인하세요.", "Includes value, event and part contracts. Export diagnostics report target support.")}</p></Section><Section title={t("값과 이벤트", "Values and events")}>{recipe.values.map(value => <div className="property-row" key={value.name}><span>{value.name}</span><code>{value.type.kind}</code></div>)}{recipe.events.map(event => <p className="help" key={event.name}>{event.name}</p>)}</Section><Section title={t("참조 카탈로그", "Reference catalogs")}><p className="help">{t("이름·의미를 대조한 원본 카탈로그입니다. Axiom 구현과 각 라이브러리의 원본 런타임은 별개입니다.", "Original catalogs used to cross-reference names and intent. Axiom adaptations are separate from each library’s own runtime.")}</p><div className="catalog-provenance-list">{studioCatalogProvenance(entry).map(variant => <a key={variant.sourceRow} href={variant.catalogUrl} target="_blank" rel="noreferrer" data-testid="catalog-provider-reference"><strong>{variant.provider} ↗</strong><span>{variant.name}</span><small>{t("카탈로그 행", "Catalog row")} {variant.sourceRow}</small></a>)}</div></Section></> : <EmptyState title={t("항목을 선택하세요", "Choose an entry")} description={t("구조와 의미 계약을 먼저 살펴보세요.", "Inspect its structure and semantic contract.")} />}</div></aside>;
}

export function WorkbenchDialog({ title, children, onClose }: { title: string; children: ReactNode; onClose(): void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const previous = document.activeElement; ref.current?.showModal(); return () => { ref.current?.close(); if (previous instanceof HTMLElement && previous.isConnected) previous.focus(); }; }, []);
  return <dialog ref={ref} className="workbench-dialog" aria-label={title} onCancel={onClose} onClick={event => { if (event.target === ref.current) onClose(); }}><div className="dialog-header"><h2>{title}</h2><IconButton icon="close" label={title === "Keyboard shortcuts" ? "Close" : "닫기 / Close"} onClick={onClose} /></div>{children}</dialog>;
}

export { SystemPanel } from "./system-panel.tsx";
